### ISSUE TITLE
ASE test has nonzero atomspins

### ISSUE THREAD

**Issue by shivupa** [cclib/cclib#1004]
The ASE test has nonzero `atomspins`. According to upstream these should still be zero (https://gitlab.com/ase/ase/-/commit/23483b9728c5695a7985c90d00283e9b9fecfe3f). This might be happening because we set the `atomspins`/`magmoms` in the cclib->ase path. This probably sets `initial_magmoms`, which is probably supposed to get reset to zero but isn't? 

(@schneiderfelipe any ideas? If not I can just open an issue upstream!)

**Comment by schneiderfelipe** [comment]
I believe that's specifically related to EMT, which seems not to support `atomspins`/`magmoms` (see [here](https://gitlab.com/ase/ase/-/blob/master/ase/calculators/emt.py)). The magnetic moments in the bridge were chosen to match what is done by the interfaces to Gaussian and xTB (see [here](https://gitlab.com/ase/ase/-/blob/master/ase/io/gaussian.py#L110) and [here](https://github.com/grimme-lab/xtb-python/blob/master/xtb/ase/calculator.py#L191)). I think that's the right thing to do in general, but I'm not 100% sure.

**Comment by langner** [comment]
Was there an action item here for us to follow up on? If there's no clear fix, perhaps mitigate by adding a comment at the appropriate location in the code/test.

**Comment by shivupa** [comment]
Not sure if this is even an issue. No planned path forward.
