### ISSUE TITLE
New parser request: NBO

### ISSUE THREAD

**Issue by berquist** [cclib/cclib#1012]
This may need to be split into two issues: there is the standalone program, but also integration with at least Gaussian and Q-Chem. If we could invoke a parser inside another parser (also desirable for #808) then a lot of duplicate work would be avoided.

**Comment by shivupa** [comment]
The parser inside a parser would also be useful for MRCC if we plan to support it.

**Comment by berquist** [comment]
Good catch; I've actually never used MRCC outside of Psi4.
