### ISSUE TITLE
Remove content from SourceForge wiki

### ISSUE THREAD

**Issue by berquist** [cclib/cclib#1016]
http://cclib.sourceforge.net/wiki/index.php/Main_Page appears high in search results for "cclib" and is ~6 years old, so it could be misleading to people searching via Google or similar.

**Comment by ghutchis** [comment]
I can't remember how well MediaWiki supports redirects - but certainly I'd point to the new site.

**Comment by berquist** [comment]
It does point to the new site already, but all the old content is still there. I think it's fine to not have a redirect as long as the content is removed.

**Comment by langner** [comment]
I managed to log in, but not clear what we want to do. Just delete all pages, or main page content?

Also tried to connect to the sftp server to just add a PHP redirect to the site... but not sure why I wasn't successful. The SF docs are a mess these days.

**Comment by berquist** [comment]
Getting this now:
![Screenshot from 2024-01-28 16-45-43](https://github.com/cclib/cclib/assets/727571/a81b4c0d-7257-4eb8-9ca9-4edb85be8df1)
and the wiki no longer appears on the front page of Google.  I think this is ok.
