### ISSUE TITLE
Error reading orbital ranges from ORCA output

### ISSUE THREAD

**Issue by rafaelpap** [cclib/cclib#1036]
Trying to parse ORCA output files with CASSCF calculations I get the following error:

[ORCA ./casscf3.log ERROR] Encountered error when parsing.
[ORCA ./casscf3.log ERROR] Last line read: Determined orbital ranges:

Traceback (most recent call last):
  File "../SCAN5/trj2xyz.py", line 17, in <module>
    data = ORCA(filename).parse()
  File "/home/rafapa/anaconda3/lib/python3.7/site-packages/cclib/parser/logfileparser.py", line 315, in parse
    self.extract(inputfile, line)
  File "/home/rafapa/anaconda3/lib/python3.7/site-packages/cclib/parser/orcaparser.py", line 1465, in extract
    start, end, num = int(vals[1]), int(vals[3]), int(vals[5])
ValueError: invalid literal for int() with base 10: 'orbital'

It seems the parser fails to skip the "Determined orbital ranges:" line and try to assing the string "orbital" to int(vals[1]))

The lines around the one which trigger the error are:

SYSTEM-SPECIFIC SETTINGS:
Number of active electrons          ...    9
Number of active orbitals           ...   10
Total number of electrons           ...   99
Total number of orbitals            ...  394
Total number aux. functions         ... 2060

Determined orbital ranges:
   Internal       0 -   44 (  45 orbitals)
   Active        45 -   54 (  10 orbitals)
   External      55 -  393 ( 339 orbitals)
Number of rotation parameters      ...  19095

CI-STEP:

The code in orcaparser.py
[casscf3.log](https://github.com/cclib/cclib/files/6317103/casscf3.log)

 reads:

            # Determined orbital ranges:
            #    Internal       0 -   -1 (   0 orbitals)
            #    Active         0 -    3 (   4 orbitals)
            #    External       4 -   19 (  16 orbitals)
            self.skip_lines(inputfile, ['b', 'Determined'])
            orbital_ranges = []
            # Parse the orbital ranges for: Internal, Active, and External orbitals.
            for i in range(3):
                vals = next(inputfile).split()
                start, end, num = int(vals[1]), int(vals[3]), int(vals[5])
                # Change from inclusive to exclusive in order to match python.
                end = end + 1
                assert end - start == num
                orbital_ranges.append((start, end, num))

If I include a next(inputfile) line before the for loop the parser correctly assign the orbital_ranges but fails again at the line
    one_el_energy = float(next(inputfile).split()[4])

**Comment by berquist** [comment]
This may be related to #1043 and fixed by #1044.

**Comment by langner** [comment]
> This may be related to #1043 and fixed by #1044.

Was it? Looking to close out before releasing v1.7.1

**Comment by berquist** [comment]
> > This may be related to #1043 and fixed by #1044.
> 
> Was it? Looking to close out before releasing v1.7.1

Yes, that did it.
