### ISSUE TITLE
ORCA parser fails for CASSCF with multiple blocks

### ISSUE THREAD

**Issue by eimrek** [cclib/cclib#1043]
Hi, I ran into the following issue illustrated on the image:

![image](https://user-images.githubusercontent.com/8721264/121196734-02df9980-c871-11eb-87a0-86cf14164295.png)

Basically, the ORCA parser assumes that the CASSCF blocks are right after each other without any new lines between. I'm assuming these new lines have been introduced in a recent ORCA version.

I can make a PR to fix this soon.

**Comment by eimrek** [comment]
Here's also the full log.

[log.txt](https://github.com/cclib/cclib/files/6617648/log.txt)

**Comment by berquist** [comment]
(I'm not sure whether this is a bug or a regression, since ORCA CASSCF is only tested in regressions.)
