### ISSUE TITLE
Julia bindings

### ISSUE THREAD

**Issue by berquist** [cclib/cclib#1053]
Taken from https://wiki.openchemistry.org/GSoC_Ideas_2021:

> Brief explanation: The Julia programming language (https://julialang.org/) is growing in popularity for computational chemistry as a language that both production-level computation and analysis can be performed in seamlessly. In order to analyze computational chemistry outputs from traditional programs in Julia, rather than reimplement all cclib functionality in Julia, we should be able to call cclib from Julia directly and reuse its core functionality.

> Expected results: Julia bindings to cclib IO functionality and a Julia-native representation of cclib data objects, with each cclib attribute accessible as a native Julia type. The bindings should be available on the default Julia package registry. The remainder of the project is more open-ended, but an example application of using the bindings would be ideal.

---

In retrospect, this may have been a bad GSoC project idea. It looks like using PyCall like
```julia
using PyCall

cclib = pyimport("cclib")
p = "/home/eric/development/cclib_berquist/data/QChem/basicQChem5.1/dvb_gopt.out"
data = cclib.io.ccread
# use keys(data) to see all attributes
```
just works:
```julia
julia> data.atomcoords
5×20×3 Array{Float64, 3}:
[:, :, 1] =
 1.36681  0.441649  -0.924918  -1.36681  -0.441649  0.924918  0.790222  -1.6542   -0.790222  1.6542   -2.87586  -3.80079  -3.12383  -4.87694  -3.55281  2.87586  3.80079  3.12383  4.87694  3.55281
 1.41641  0.495705  -0.895149  -1.41641  -0.495705  0.895149  0.879445  -1.57416  -0.879445  1.57416  -2.89877  -3.90815  -3.12116  -4.95754  -3.75036  2.89877  3.90815  3.12116  4.95754  3.75036
 1.41536  0.486544  -0.898104  -1.41536  -0.486544  0.898104  0.865075  -1.58625  -0.865075  1.58625  -2.87799  -3.88297  -3.11503  -4.93074  -3.71352  2.87799  3.88297  3.11503  4.93074  3.71352
 1.41529  0.484334  -0.898219  -1.41529  -0.484334  0.898219  0.861887  -1.58835  -0.861887  1.58835  -2.88202  -3.8854   -3.12554  -4.93362  -3.7126   2.88202  3.8854   3.12554  4.93362  3.7126
 1.4151   0.484141  -0.898537  -1.4151   -0.484141  0.898537  0.86146   -1.58895  -0.86146   1.58895  -2.8817   -3.88463  -3.12527  -4.93286  -3.71174  2.8817   3.88463  3.12527  4.93286  3.71174

[:, :, 2] =
 0.278769  1.32306  1.04428  -0.278769  -1.32306  -1.04428  2.36601  1.86735  -2.36601  -1.86735  -0.586781  0.363252  -1.65668  0.143975   1.43315  0.586781  -0.363252  1.65668  -0.143975   -1.43315
 0.233001  1.31613  1.09069  -0.233001  -1.31613  -1.09069  2.34496  1.94941  -2.34496  -1.94941  -0.542141  0.345349  -1.61915  0.026949   1.42784  0.542141  -0.345349  1.61915  -0.026949   -1.42784
 0.237409  1.31605  1.08646  -0.237409  -1.31605  -1.08646  2.34751  1.94215  -2.34751  -1.94215  -0.541685  0.350403  -1.6166   0.0276862  1.43396  0.541685  -0.350403  1.6166   -0.0276862  -1.43396
 0.240074  1.3155   1.08321  -0.240074  -1.3155   -1.08321  2.34743  1.93676  -2.34743  -1.93676  -0.543308  0.351237  -1.61643  0.03009    1.4337   0.543308  -0.351237  1.61643  -0.03009    -1.4337
 0.240682  1.31611  1.08311  -0.240682  -1.31611  -1.08311  2.34812  1.93631  -2.34812  -1.93631  -0.543525  0.351663  -1.61668  0.0306818  1.43403  0.543525  -0.351663  1.61668  -0.0306818  -1.43403

[:, :, 3] =
 -0.0  -0.0  -0.0  0.0  0.0  0.0  -0.0  -0.0  0.0  0.0  0.0  -0.0  0.0  -0.0  -0.0  -0.0  0.0  -0.0  0.0  0.0
  0.0   0.0   0.0  0.0  0.0  0.0   0.0   0.0  0.0  0.0  0.0   0.0  0.0   0.0   0.0   0.0  0.0   0.0  0.0  0.0
  0.0   0.0   0.0  0.0  0.0  0.0   0.0   0.0  0.0  0.0  0.0   0.0  0.0   0.0   0.0   0.0  0.0   0.0  0.0  0.0
  0.0   0.0   0.0  0.0  0.0  0.0   0.0   0.0  0.0  0.0  0.0   0.0  0.0   0.0   0.0   0.0  0.0   0.0  0.0  0.0
  0.0   0.0   0.0  0.0  0.0  0.0   0.0   0.0  0.0  0.0  0.0   0.0  0.0   0.0   0.0   0.0  0.0   0.0  0.0  0.0

julia> data.atomcoords[1, :, :]
20×3 Matrix{Float64}:
  1.36681    0.278769  -0.0
  0.441649   1.32306   -0.0
 -0.924918   1.04428   -0.0
 -1.36681   -0.278769   0.0
 -0.441649  -1.32306    0.0
  0.924918  -1.04428    0.0
  0.790222   2.36601   -0.0
 -1.6542     1.86735   -0.0
 -0.790222  -2.36601    0.0
  1.6542    -1.86735    0.0
 -2.87586   -0.586781   0.0
 -3.80079    0.363252  -0.0
 -3.12383   -1.65668    0.0
 -4.87694    0.143975  -0.0
 -3.55281    1.43315   -0.0
  2.87586    0.586781  -0.0
  3.80079   -0.363252   0.0
  3.12383    1.65668   -0.0
  4.87694   -0.143975   0.0
  3.55281   -1.43315    0.0
```
If the interface provided by PyCall doesn't require any extra work, then we don't need to provide bindings.

**Comment by mscho527** [comment]
It seems like PyCall is able to interface most (if not all) functionalities of cclib? In addition to the parsing @berquist mentioned, methods (like Mulliken) seem to work fine.

**Comment by berquist** [comment]
Then I think we can call this a non-issue.

**Comment by schneiderfelipe** [comment]
I think it is still useful to have a very thin Julia wrapper:
- Other Julia packages can depend on cclib through the wrapper
- Versioning and testing can be separately done on the Julia side
- Dependency management can be done automatically on the Julia side (no need to have pip or otherwise leave the Julia ecosystem)

For instance, [SymPy.jl uses `pyimport_conda`](https://github.com/JuliaPy/SymPy.jl/blob/aea9fb5568022bbd68fe4b69d670ce2a22413a7c/src/SymPy.jl#L124) for installing sympy if not available ([defined in PyCall.jl](https://github.com/JuliaPy/PyCall.jl#using-pycall-from-julia-modules)).

That would be a ~10 line Julia package (plus one or two tests maybe), so not too hard to maintain.

**Comment by berquist** [comment]
All good points.

**Comment by schneiderfelipe** [comment]
I created a prototype package at https://github.com/schneiderfelipe/Cclib.jl.
I'm happy to publish it to the [general registry](https://github.com/JuliaRegistries/General) and transfer it to the @cclib org. if that's OK.

**Comment by berquist** [comment]
Yep, looks good.  The tests run successfully.  +1 to org transfer and publishing it on the general registry.
```julia
julia> using Cclib                                                                                                                                                                                           [14/473]

help?> Cclib
search: Cclib cclib ConcurrencyViolationError

  No docstring found for module Cclib.

  Exported names
  ≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡

  cclib

  Displaying contents of readme found at /home/eric/development/forks/julia/Cclib.jl/README.md
  ≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡

  Cclib.jl
  ≡≡≡≡≡≡≡≡≡≡

  (Image: Stable) (https://schneiderfelipe.github.io/Cclib.jl/stable) (Image: Dev) (https://schneiderfelipe.github.io/Cclib.jl/dev) (Image: Build Status)
  (https://github.com/schneiderfelipe/Cclib.jl/actions/workflows/CI.yml?query=branch%3Amain) (Image: Coverage) (https://codecov.io/gh/schneiderfelipe/Cclib.jl)

  Julia bindings to cclib (https://github.com/cclib/cclib).

  Temptive implementation of an idea from Open Chemistry's GSoC Ideas 2021 (https://wiki.openchemistry.org/GSoC_Ideas_2021#Project:_Julia_bindings):

    •  [x] bindings to cclib IO functionality

    •  [x] Julia-native representation of cclib data objects, including cclib attributes

    •  [ ] bindings available on the default Julia package registry

    •  [ ] an example application of using the bindings

  See cclib/cclib#1053 (https://github.com/cclib/cclib/issues/1053) for more information (and comment therein (https://github.com/cclib/cclib/issues/1053#issuecomment-1003323272)).

julia> cclib.
__builtins__ __doc__       __loader__    __package__   __spec__      bridge        ccwrite       method        progress
__cached__   __file__      __name__      __path__      __version__   ccopen        io            parser
julia> data = cclib.io.ccread("/home/eric/data/cclib/calculations/polarizability/trithiolane/dalton/trithiolane_polar_abalnr.out")
PyObject <cclib.parser.data.ccData_optdone_bool object at 0x7fca6d1994c0>

julia> data
PyObject <cclib.parser.data.ccData_optdone_bool object at 0x7fca6d1994c0>

help?> data
search: data DataType IndexCartesian RoundNearestTiesAway findlast LOAD_PATH timedwait broadcast! broadcast Broadcast isdirpath code_native isdispatchtuple InvalidStateException @code_native StridedMatrix

This is the version of ccData where optdone is a Boolean.

julia> data.polarizabilities
1-element Vector{Matrix{Float64}}:
 [75.47588 0.00020732453 3.2057406e-5; 0.00017649036 76.06317 0.4362455; 2.7663934e-5 0.4363543 46.63142]

julia> data.scfenergies
1-element Vector{Float64}:
 -34638.06245446732

julia> data.atomcoords
1×9×3 Array{Float64, 3}:
[:, :, 1] =
 -1.74043  1.11311  1.11307  -0.533495  -0.533399  -0.459474  -0.893854  -0.45911  -0.893891

[:, :, 2] =
 -5.70736e-5  1.0075  -1.00753  1.33405  -1.33387  1.41258  2.27671  -1.41193  -2.2767

[:, :, 3] =
 -7.8124e-5  0.286771  -0.286851  -0.438866  0.439189  -1.52465  -0.0173874  1.52498  0.0182269
```

**Comment by berquist** [comment]
Oh, there is also https://github.com/JuliaMolSim/MolSim, maybe we should talk to them?

**Comment by ghutchis** [comment]
I know that @rkurchin has been doing a lot with DFT in Julia - she might also be a good person to talk to - she's at Carnegie Mellon right now and helped with GSoC for Julia last year: https://summerofcode.withgoogle.com/archive/2021/projects/4891585065517056

**Comment by rkurchin** [comment]
Thanks for the tag! Definitely check out our [AtomsBase](https://github.com/JuliaMolSim/AtomsBase.jl) package! Connecting that up with this CClib stuff would be 🔥

**Comment by berquist** [comment]
> Great. One thing I was wondering: maybe we should expose each cclib public module as a separate entity? Earlier I decided on the simplest solution (a single `cclib` object exported), but we could export `ccopen`, `io`, etc. separately. Maybe things should be as close as possible as in Python, but still, stick to most Julia conventions? @berquist what do you think?

I think all the conventions should match exactly what you'd expect as a Julia user. To me, that would mean `using Cclib;` would bring in `ccread` automatically, without the need for prefixing, but you could still choose to selectively import `io`, `methods`, etc.

**Comment by schneiderfelipe** [comment]
Great, let me change that bit and transfer the repo so that we can publish it.

**Comment by schneiderfelipe** [comment]
It's done. Very simple documentation is [available here](https://schneiderfelipe.github.io/Cclib.jl/).

**Comment by berquist** [comment]
Let's consider this done now that https://github.com/cclib/Cclib.jl exists thanks to Felipe.  We have interest in developing it further for GSoC 2023, and most issues can just go directly on that repo.

An initial version was sent for registration (https://github.com/JuliaRegistries/General/pull/80040) somehow during repo ownership transfer?  Aside from that PR now referencing the wrong location, we should discuss whether or not 0.1.0 should be registered as-is (https://github.com/cclib/Cclib.jl/issues/4), even though there will be a switch from PyCall to PythonCall, etc.  It also depends on if we get a student for GSoC.

**Comment by schneiderfelipe** [comment]
> An initial version was sent for registration ([JuliaRegistries/General#80040](https://github.com/JuliaRegistries/General/pull/80040)) somehow during repo ownership transfer? Aside from that PR now referencing the wrong location, we should discuss whether or not 0.1.0 should be registered as-is ([cclib/Cclib.jl#4](https://github.com/cclib/Cclib.jl/issues/4)), even though there will be a switch from PyCall to PythonCall, etc. It also depends on if we get a student for GSoC.

Sorry, that was my mistake, I ran the [tag workflow manually](https://github.com/cclib/Cclib.jl/actions/runs/4482596143/jobs/7880832952) prior to transferring and it seems to have triggered the registration one.
