### ISSUE TITLE
natural charges for radicals from gaussian

### ISSUE THREAD

**Issue by bobbypaton** [cclib/cclib#1055]
Gaussian/NBO calculations for radicals print out natural charges for alpha electrons, then beta electrons, then for the molecule as a whole - cclib parses the first set, whereas the last set is required.

**Comment by shivupa** [comment]
Hi Thanks for reporting this. Do you have a log file that reproduces this issue

**Comment by bobbypaton** [comment]
Here's an example for an open-shell neutral molecule (H3). I put the log file here: https://github.com/bobbypaton/bobbypaton/blob/main/H3.log

import cclib as cc
parser = cc.io.ccopen('H3.log')
data = parser.parse()
data.atomcharges
{'mulliken': array([ 0.04863, -0.09726,  0.04863]), 'natural': array([ 0.30931, -0.11863,  0.30931])}
 
The mulliken charges correctly sum to 0. The natural charges sum to 0.5 which is not correct.

The origin of this error is that the Gaussian log file prints out three sets of natural charges - to correct my message above, the first set are summed for alpha and beta spins, whereas these are followed by alpha and beta spins separately. The correct values of the natural charges from the log file are: 0.07210, -0.14420, 0.07210 (sums to zero).
