### ISSUE TITLE
Orca 5.0 support

### ISSUE THREAD

**Issue by ATenderholt** [cclib/cclib#1063]
Orca 5.0 was released a few weeks ago. It seems like there are formatting changes that breaks existing parsers.

**Comment by shivupa** [comment]
I can contribute the unit tests. I told @ghutchis I would do these a couple weeks back but I forgot.. They are running now

**Comment by ATenderholt** [comment]
Oh, that'd be great. I've been trying to run on my laptop but only have made it through gopt and ir.

I've also been pushing to my forked repo. Guess I could push to a branch here instead.

**Comment by ATenderholt** [comment]
Just pushed what I have to https://github.com/cclib/cclib/tree/orca5.

**Comment by shivupa** [comment]
perfect ill make a PR into that once this finishes!

**Comment by berquist** [comment]
Done in #1064 and #1065.
