### ISSUE TITLE
Error parsing orca output

### ISSUE THREAD

**Issue by bobbypaton** [cclib/cclib#1091]
Parsing error (below) for a regular opt+freq job ran with Orca 5.0. Is this due to any changes in formatting with the updated orca version?
---

Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.8/site-packages/cclib/parser/logfileparser.py", line 315, in parse
    self.extract(inputfile, line)
  File "/opt/anaconda3/lib/python3.8/site-packages/cclib/parser/orcaparser.py", line 1279, in extract
    num = int(line[0:4])
ValueError: invalid literal for int() with base 10: '----'

---
Here's the output file
[acetaldehyde.log](https://github.com/cclib/cclib/files/7857162/acetaldehyde.log)

**Comment by shivupa** [comment]
This should work with the current master branch, but support for ORCA 5 will be in the next release. v1.7.2

**Comment by shivupa** [comment]
Closing for now feel free to reopen if there are additional issues.
Running `ccget --list acetaldehyde.log ` current main branch:
```
cclib can parse the following attributes from acetaldehyde.log:
  atomcharges
  atomcoords
  atommasses
  atomnos
  charge
  coreelectrons
  dispersionenergies
  enthalpy
  entropy
  freeenergy
  geotargets
  geovalues
  grads
  homos
  metadata
  moenergies
  moments
  mult
  natom
  nbasis
  nmo
  optdone
  pressure
  scfenergies
  scftargets
  scfvalues
  temperature
  vibdisps
  vibfreqs
  vibirs
  zpve
  ```
