### ISSUE TITLE
Error parsing DLPNO single-point calculation

### ISSUE THREAD

**Issue by jvalegre** [cclib/cclib#1092]
Dear cclib developers,

I get an error when parsing DLPNO single-point calculations in ORCA v4.0 and v4.2:

"
[ORCA a_DLPNO.out ERROR] Encountered error when parsing.
[ORCA a_DLPNO.out ERROR] Last line read:              **** THE GBW FILE WAS UPDATED (/PATH/FILENAME.gbw) ****
"

where PATH is just the folder used in the HPC server where I run the calculation. Have you encountered this error before?

Best,
Juan

**Comment by shivupa** [comment]
Hi Juan,
Are you able to share the offending output file?

**Comment by jvalegre** [comment]
Absolutely, thanks! This file is for ORCA 4.0 but the same happens in version 4.2
[a_DLPNO.txt](https://github.com/cclib/cclib/files/7909540/a_DLPNO.txt)
