### ISSUE TITLE
ccopen does not support Path objects

### ISSUE THREAD

**Issue by arosen93** [cclib/cclib#1096]
Due to the `if` check below, `Path` objects (from `pathlib`) are not properly read because their type is neither string nor list of strings. To support `Path` objects, it might be nice to either: 1) Just naively convert `Path` objects or lists of `Path` objects to `str` or list of `str`; 2) Modify the `if` check to support `Path`, assuming that doesn't ruin anything downstream.
https://github.com/cclib/cclib/blob/bc1fd722e74109b49b3c1fd31a519a378d93be29/cclib/io/ccio.py#L195-L198

**Comment by shivupa** [comment]
Sorry didn't mean to remove the tags!
