### ISSUE TITLE
Feature suggestion: support .gz files in volume.read_from_cube()

### ISSUE THREAD

**Issue by Andrew-S-Rosen** [cclib/cclib#1098]
Currently, `ccopen` can open `.gz` log files. However, `volume.read_from_cube()` throws a `UnicodeDecodeError` when trying to parse a `cube.gz` file. Since `.cube` files can get kind of large, these are likely to be gzip'd in many cases, so it'd be great if the `read_from_cube()` function could natively parse the gzip'd file.

I think this could likely be done fairly easily by importing and then using `openlogfile` from `cclib.parser.logfile`.
https://github.com/cclib/cclib/blob/bc1fd722e74109b49b3c1fd31a519a378d93be29/cclib/parser/logfileparser.py#L126-L135

Also, apologies for not submitting PRs with each of these recent suggestions. I'm a bit over my head in code at the moment. If nobody gets to this, I'll get to it one day, but I can't guarantee it'll be soon.

**Comment by shivupa** [comment]
No worries! Good feature requests are just as valuable contributions as PRs.

**Comment by oliver-s-lee** [comment]
This should be fairly achievable I think, although I've not played with the cube parsing code. I'll have a look when I get a chance :)

**Comment by berquist** [comment]
No obligations, I just figured that you have the most recent experience with the different file wrappers.

**Comment by oliver-s-lee** [comment]
Implementation in https://github.com/cclib/cclib/pull/1371
