### ISSUE TITLE
Theory Level

### ISSUE THREAD

**Issue by andre-cloud** [cclib/cclib#1120]
Is there a way to get the theory level used in a calculation? 

For example B3LYP, HF/6-31g or something like that? So that when you parse the file with this library, you don't need to reopen the file and scrape it again? 

Thanks

**Comment by berquist** [comment]
Unfortunately our support for this right now is spotty. If it's available, check the `metadata` attribute, which is a dictionary, and the keys `methods`, `functional`, and `basis_set` (https://cclib.readthedocs.io/en/latest/data_notes.html#metadata). If you have needs for a specific program, let us know.

**Comment by andre-cloud** [comment]
Cool, thanks. I didn't notice that earlier.
