### ISSUE TITLE
MOLDEN: output frequency information

### ISSUE THREAD

**Issue by andre-cloud** [cclib/cclib#1127]
Hi there, 

I need a molden file to generate a wigner sampling esamble. I was wondering if cclib could generate it. It has to contain geometry, frequency modes and displacement vector in it. 

Orca v. 5.0.3

**Comment by shivupa** [comment]
We don't currently write out frequency and displacement vectors. Specifically from the tags here which ones would you need from `FREQ FR-COORD FR-NORM-COORD INT` https://www3.cmbi.umcn.nl/molden/molden_format.html

**Comment by andre-cloud** [comment]
FREQ FR-COORD FR-NORM-COORD. I know for sure that ccib outputs FREQ in normal situations, but in this case, ORCA 5.0.3 is not parsed correctly and throws an error.

**Comment by danielhollas** [comment]
@andre-cloud which cclib version are you using? Support for ORCA 5.0 has been merged to the master branch, but not officially released yet. Using master branch I can parse frequency outputs without issue.

**Comment by andre-cloud** [comment]
@danielhollas I'm using 1.7.1

**Comment by berquist** [comment]
> FREQ, FR-COORD, and FR-NORM-COORD. I know for sure that ccib outputs FREQ in normal situations, but in this case, ORCA 5.0.3 is not parsed correctly and throws an error.

>  which cclib version are you using? Support for ORCA 5.0 has been merged to the master branch, but not officially released yet. Using master branch I can parse frequency outputs without issue.

> I'm using 1.7.1 from pip

This is good incentive for us to cut 1.7.2 then. @langner 

I will try and implement the frequency bits for the MOLDEN writer.
