### ISSUE TITLE
Check progress information update for Gaussian

### ISSUE THREAD

**Issue by ATenderholt** [cclib/cclib#115]
This issue came up from a QMForge user (Andy S.) who noted that parsing some of his files only showed "Unsupported Information" in the progress dialog. To address it, just examine parser progress logic to see if any fixes are necessary, and check with the example file (unfortunately not Public Domain) provided to me.

**Comment by langner** [comment]
@ATenderholt do you think you'll get around to this. If not, do you think it's important enough to keep around?

**Comment by ATenderholt** [comment]
I'll close this issue for now. I think once we get around to refactoring the various parsers, we can make sure the progress information is correct.
