### ISSUE TITLE
Problem with how Gaussian parser checks for data.

### ISSUE THREAD

**Issue by oliver-s-lee** [cclib/cclib#1163]
Many parts of the Gaussian parser look for data by checking for the existence of certain sub-strings at given positions in the current line, for example this check for MP5 energies:
`if line[29:32] == "MP5":`
This works fine, but many parts of the Gaussian output file are essentially free-form, and can contain unpredictable data. For example:
The initial section (dependant on environment):
```
 Entering Gaussian System, Link 0=g16
 Input=/tmp/pytest-of-osl/pytest-5/test_gaussian_methods_MP5_0/Ethane/Gaussian 16 Single Point Singlet MP5 Gas Phase 6-31G*/Input/Ethane.com
 Output=/tmp/pytest-of-osl/pytest-5/test_gaussian_methods_MP5_0/Ethane/Gaussian 16 Single Point Singlet MP5 Gas Phase 6-31G*/Output/Ethane.log
 Initial command:
 /gpfs1/apps/software/Gaussian16/AVX/g16/l1.exe "/scratch/tmp/osl/12650775b68e44f59aa110865383be32/Gau-12302.inp" -scrdir="/scratch/tmp/osl/12650775b68e44f59aa110865383be32/"
 Entering Link 1 = /gpfs1/apps/software/Gaussian16/AVX/g16/l1.exe PID=     12303.
```
and the comment section (which is entirely set by the user):
```
 Leave Link    1 at Mon Nov  7 20:28:08 2022, MaxMem=  4294967296 cpu:               0.9 elap:               0.1
 (Enter /gpfs1/apps/software/Gaussian16/AVX/g16/l101.exe)
 ------------------------------------------------
 Ethane_Single_Point_Singlet_MP5_Gas_Phase_6_31G_
 ------------------------------------------------
```
These free-form sections can accidentally trigger these checks if they just so happen to contain the crucial sub-string at the right place. For example, the above comment section contains the trigger string 'MP5' at positions 29:32, and so the file fails to parse:
```
Attempting to read Ethane.mp5.log
[Gaussian Ethane.mp5.log ERROR] Encountered error when parsing.
[Gaussian Ethane.mp5.log ERROR] Last line read:  Ethane_Single_Point_Singlet_MP5_Gas_Phase_6_31G_

Traceback (most recent call last):
  File "/home/oliver/.local/bin/ccget", line 8, in <module>
    sys.exit(ccget())
  File "/home/oliver/dev/cclib/cclib Src/cclib/scripts/ccget.py", line 178, in ccget
    data = ccread(filename, **kwargs)
  File "/home/oliver/dev/cclib/cclib Src/cclib/io/ccio.py", line 170, in ccread
    return log.parse()
  File "/home/oliver/dev/cclib/cclib Src/cclib/parser/logfileparser.py", line 321, in parse
    self.extract(inputfile, line)
  File "/home/oliver/dev/cclib/cclib Src/cclib/parser/gaussianparser.py", line 922, in extract
    mp5energy = utils.float(line.split("=")[2])
IndexError: list index out of range
```
[Ethane.mp5.log](https://github.com/cclib/cclib/files/9955412/Ethane.mp5.log)

A simple workaround is to increase the specificity of the checks (ie, look for `MP5 =` instead of just `MP5`). This is probably fine as the chance of hitting the phrase in the wrong place is pretty low, but as that doesn't actually address the root of the problem I'm not sure if that's the best way to tackle it?

**Comment by berquist** [comment]
> that doesn't actually address the root of the problem I'm not sure if that's the best way to tackle it?

This is the core way of how we do it. Some parsers have some extra guardrails like knowing what section you're in (Psi4, DALTON at least) but you will always need to perform some sort of string match. Unless we have a radical redesign and determine that all outputs have text that follows a regular grammar (in the CS sense) then this is fine.

Can you make a PR to cclib-data with the ethane output?

**Comment by oliver-s-lee** [comment]
Sure that's fair, I just wanted to make a note of it really. I've added the PR.

**Comment by berquist** [comment]
This confused me because the issue was closed before the PR. Normally we have the PR automatically close the (linked) issue when the PR gets merged.
