### ISSUE TITLE
Error in parsing SCF energies in ORCA 5.0.4

### ISSUE THREAD

**Issue by andre-cloud** [cclib/cclib#1193]
Hello, 

I was messing around with the SCF energies of a file and I noted that the value parsed from CCLIB  does not match any of the values present in the output file. I was wondering what I'm missing: 

FROM THE OUTPUT
```
LAST CYCLE OF SCF: -2603.37063340
FINAL SINGLE POINT ENERGY: -2603.370633399245
No dispersion included in the calculation
```

VALUE FROM CCLIB PARSING
```
-70841.32073331 eV -> -2603.369298774752 Eh
```

**Comment by andre-cloud** [comment]
Unfortunately, I can't find that exact file. But I've checked another output file and the same error appears:

```
SCF ENERGY: -802.17406188 Eh
FINAL SINGLE POINT ENERGY:      -802.174061883973 Eh
```

Value obtained with cclib

```
-21828.26727502 eV -> -802.173650646187 Eh
```

Here below the output file

[z_dtbad_s0_dtbad.out.zip](https://github.com/cclib/cclib/files/11370937/z_dtbad_s0_dtbad.out.zip)

**Comment by oliver-s-lee** [comment]
Hi @andre-cloud, thanks for sharing this!

On my version I get the final SCF energy as:
`-21828.26727502` eV
Equivalent to `-802.174061883` Eh using a conversion factor of `27.21138505`

So the value in eV looks like it matches that in the log file. What are you using to convert between eV and Eh?

**Comment by andre-cloud** [comment]
I'm using `27.211399`

**Comment by oliver-s-lee** [comment]
Ok, this looks like just a unit conversion problem then.

Cclib uses `27.21138505` throughout for conversion from hartree to eV. For Orca SCF, most (if not all) energies are read in hartree, converted to eV and then stored in eV internally. If you want to get back to the hartree representation, just use the cclib conversion factor and the conversion should match the value in the log file exactly (save for rounding errors).

Do you have a source for the `27.211399` value you are using? If we're using the wrong factor then that's a problem that we can address.

**Comment by andre-cloud** [comment]
Not really, I was using an online converter, so it's more likely wrong that one. Or the difference of the factor can be rooted to some approximation of the constants used. 

Thank you anyway for the clarifications

**Comment by oliver-s-lee** [comment]
No problem!
