### ISSUE TITLE
ORCA Hirshfeld charges -  missing  an extra digit

### ISSUE THREAD

**Issue by alvarovm** [cclib/cclib#1209]
In the line:
https://github.com/cclib/cclib/blob/1aedede314a594442c4248453f864725c225c298/cclib/parser/orcaparser.py#L2211
There is:
`            start, stop = 9, 17`
this could be:
`            start, stop = 9, 18`

This change help to get total number of electrons closer to an integer number.

**Comment by berquist** [comment]
I looked at the actual sums from ORCA 5.0 and there is decent cancellation of error:
```python
In [10]: new = [-0.003419, -0.003419, -0.0382  , -0.0382  , -0.036945, -0.036945,  0.039063,  0.039063,  0.039379,  0.039379,
    ...:        -0.038248, -0.038248,  0.037052,  0.037052, -0.074799, -0.074799,  0.037256,  0.037256,  0.038946,  0.038946]

In [11]: old = [-0.00341, -0.00341, -0.0382 , -0.0382 , -0.03694, -0.03694,  0.03906,  0.03906,  0.03937,  0.03937, -0.03824,-0.03824,  0.03705,  0.03705, -0.07479, -0.07479,  0.03725,  0.03725,  0.03894,  0.03894
    ...: ]

In [12]: sum(old)
Out[12]: 0.00018000000000001348

In [13]: sum(new)
Out[13]: 0.00017000000000001736
```
but this was clearly a bug.
