### ISSUE TITLE
Add Optional Index Parameter to self.extend_attribute()

### ISSUE THREAD

**Issue by weronikazak** [cclib/cclib#1224]
Currently there is no provision for specifying an index when using the `self.extend_attribute` [function](https://github.com/cclib/cclib/blob/2b947c1d0d931d11d1b6fcf5b08eea5999a418a2/cclib/parser/logfileparser.py#L479C9-L479C15). It would be helpful to improve this method by adding an extra optional parameter for the index. This parameter would allow users to extend attributes at a specific position, eliminating the need for manual indexing operations like `self.mocoeffs[-1].extend(mocoeff)`.

Alternatively, it could be considered to add a new function specifically designed for this purpose. 

I think this improvement would add to the flexibility and usability of the codebase.

**Comment by berquist** [comment]
Which implementation do you think is preferable?

**Comment by weronikazak** [comment]
I was thinking of adding the optional parameter to the current function instead of creating a new one. This way, we can avoid having too many functions in the file and prevent any potential confusion. It doesn't seem worth it to create a new function for every small detail in this situation.

**Comment by berquist** [comment]
Done in #1228.
