### ISSUE TITLE
ORCA parser reads wrong energy for DLPNO-CCSD(T) calculation

### ISSUE THREAD

**Issue by flrnslbch** [cclib/cclib#1235]
cclib 1.7.2
python 3.9.16

To reproduce run this with the attached file [orca.log](https://github.com/cclib/cclib/files/12143806/orca.log):
```python
import cclib
from cclib.parser.utils import convertor

parser = cclib.parser.ORCA('orca.log')
result = parser.parse()

print(convertor(result.ccenergies[0], 'eV', 'hartree'))
```

Expected behavior according to the documentaiton: "Only the highest theory level is parsed into this attribute (for example, CCSD energies as opposed to CCD energies, or CCSD(T) as opposed to CCSD energies)."

Actual behavior: `ccenergies` contains the CCSD energy instead of the CCSD(T) energy: -188.2982948 Hartree vs -188.324984162213 Hartree

**Comment by oliver-s-lee** [comment]
Hi @flrnslbch, thanks for the bug report! It looks like this has been fixed at some point, in HEAD:
```
ccenergies
array([-5124.58365857])       # (-188.324991627727 Hartree)
```
Please feel free to open again if this is still a problem for you.

**Comment by berquist** [comment]
Yes, #1194, which appears in version 1.8.
