### ISSUE TITLE
v1.8 release: what else is needed?

### ISSUE THREAD

**Issue by arosen93** [cclib/cclib#1248]
Hi cclib friends. I noticed that all the assigned issues for the v1.8 milestone have been met. Congratulations!

I wanted to ask --- what are the remaining next steps to get a v1.8 release? If it's some small things, perhaps I can help.

**Comment by shivupa** [comment]
We plan to cut the release ASAP!

**Comment by arosen93** [comment]
CHRISTMAS COMES EARLY THIS YEAR!!!!!

**Comment by berquist** [comment]
https://github.com/cclib/cclib/issues/1249
