### ISSUE TITLE
Build, check, and push distributions in CI

### ISSUE THREAD

**Issue by shivupa** [cclib/cclib#1266]
- Create and check installation of distributions (source, wheel) on each commit
- Automatically upload distributions to PyPI when a tag is pushed

_Originally posted by @berquist in https://github.com/cclib/cclib/issues/1249#issuecomment-1672406702_

**Comment by berquist** [comment]
See #1327

**Comment by berquist** [comment]
Done in #1363, #1376, and #1382.
