### ISSUE TITLE
Request: Free Energies for nwchem

### ISSUE THREAD

**Issue by eduardob999** [cclib/cclib#1288]
Hello, I would like to have that function implemented soon. I would work on it myself and apply for a pull request only if I'm authorized to tru it first.

Greetings.

**Comment by berquist** [comment]
Hi Eduardo, you are more than welcome to submit a PR yourself and one of us will review it.  No one is working on this part of the NWChem parser right now.

**Comment by berquist** [comment]
Done in #1412 and #1422.
