### ISSUE TITLE
 Issue with G16 files ccget --list

### ISSUE THREAD

**Issue by NastaMauger** [cclib/cclib#1290]
Hello,

I have two different files, both of them produced by Gaussian 16 using the same keywords. For some reason, the command _ccget --list test.log_ works perfectly fine. However, when I try the same command on mp2_avdz_freq_tight.log, it returns an error:

> Attempting to read ../mp2_avdz_freq_tight.out
> [Gaussian ../mp2_avdz_freq_tight.out ERROR] Encountered error when parsing.
> [Gaussian ../mp2_avdz_freq_tight.out ERROR] Last line read:  Leave Link    1 at Mon Oct 16 00:52:40 2023, MaxMem=174483046400 cpu:               0.5 elap:               0.0
> 
> Traceback (most recent call last):
>   File "/usr/local/bin/ccget", line 8, in <module>
>     sys.exit(ccget())
>   File "/usr/local/lib/python3.10/dist-packages/cclib/scripts/ccget.py", line 188, in ccget
>     data = ccread(filename, **kwargs)
>   File "/usr/local/lib/python3.10/dist-packages/cclib/io/ccio.py", line 190, in ccread
>     return log.parse()
>   File "/usr/local/lib/python3.10/dist-packages/cclib/parser/logfileparser.py", line 171, in parse
>     self.extract(self.inputfile, line)
>   File "/usr/local/lib/python3.10/dist-packages/cclib/parser/gaussianparser.py", line 231, in extract
>     memory_per_cpu = int(line[line.index("MaxMem="):].split()[1])
> ValueError: invalid literal for int() with base 10: 'cpu:'

For some reason the code is trying to convert a subscript which includes the text _cpu_ to an integer
I am a bit confused about why this issue is happening in one file and the not the other one and how to solve it. Any help will be appreciated.

Best regards.

[mp2_avdz_freq_tight.log](https://github.com/cclib/cclib/files/13032028/mp2_avdz_freq_tight.log)
[test.log](https://github.com/cclib/cclib/files/13032029/test.log)

**Comment by berquist** [comment]
Thanks for the report!  Yes, this fails with 91c8d60a.  `test.log` is a Hartree-Fock opt+freq calculation and the other is an MP2 frequency only calculation.  It is probably something to do with the MP2 part then.

@oliver-s-lee Since this is in the memory parsing section, can you take a look at it?

**Comment by oliver-s-lee** [comment]
Hi @NastaMauger, thanks for the report and files.

Should now be fixed in #1368
