### ISSUE TITLE
Is `mooccnos` a supported `ccData` attribute?

### ISSUE THREAD

**Issue by Andrew-S-Rosen** [cclib/cclib#1297]
I looked in the supported list of [data attributes](https://cclib.github.io/data.html) and saw `nooccnos` for natural bonding orbital occupancies but not `mooccnos` even though some parsers (e.g. ORCA) seem to support it.

Is `mooccnos` formally supported? If so, it should be added to the list.

**Comment by shivupa** [comment]
Currently it is not. We store `homos` and assume aufbau filling. I'd be open to changing that if there was a use case (excited state scf?).

Also I think attributes that are set in parsers `self.whatever = something` that aren't official attributes get destroyed after parsing. So I think in the orca parser these are not accessible.

**Comment by Andrew-S-Rosen** [comment]
@shivupa, ah okay thanks! I didn't have a particular need but was a bit confused why I saw it in some other parsers. Feel free to close.
