### ISSUE TITLE
Minimal example for NBO parsing

### ISSUE THREAD

**Issue by Andrew-S-Rosen** [cclib/cclib#1365]
Hi friends. I am using cclib 1.8 and trying to test out the basic NBO parsing. I'm using the data files [here](https://github.com/cclib/cclib/tree/master/data/NBO/basicNBO7.0/basicORCA5.0).

```python
from cclib.io import ccread
c = ccread("dvb_sp_nbo.out")
```

results in

```
Unable to determine the type of logfile ['dvb_sp_nbo.out'], try the fallback mechanism
```

Additionally, doing

```python
from cclib.io import ccread
c = ccread("dvb_sp.out")
print(c.getattributes())
```

doesn't seem to yield any NBO data, but perhaps it's stored elsewhere?

**Comment by Andrew-S-Rosen** [comment]
Ah, fantastic. Thanks for the update! I'll go ahead and close this. I should have tried `master` :)

**Comment by Andrew-S-Rosen** [comment]
@amandadumi --- in the second instance, which does successfully parse, would you be able to point me to where the NBO properties are stored?

**Comment by amandadumi** [comment]
Of course! The parsing from the isolated NBO output is currently supported.  We are working at to allow this information to be parsed from the nested output from , but this likely won't be for the next release in all honesty. How much of  a hindrance is this for your workflow?

From the example you posted:


```
import cclib
print(cclib.__file__)
from cclib.io import ccread
c = ccread("dvb_sp.nbo.out")
print(c.atomcharges['nbo'])
```
will return
```
[ 0.00535  0.00535 -0.05385 -0.05385 -0.05386 -0.05386  0.05145  0.05145
  0.05256  0.05256 -0.04897 -0.04897  0.04977  0.04977 -0.10592 -0.10592
  0.05006  0.05006  0.05341  0.05341]
```

**Comment by Andrew-S-Rosen** [comment]
Thanks again for the reply, @amandadumi!

That's good to know. I wasn't sure if the presence of the test file indicated that the properties were properly being parsed and wanted to make sure I wasn't simply missing it. I'll stick to parsing the dedicated NBO log file for now.
