### ISSUE TITLE
Flag 'success' not working with gaussian .fchk

### ISSUE THREAD

**Issue by TimoSommer** [cclib/cclib#1401]
The `success` flag in `metadata` seems to be not working for .fchk files generated with Gaussian, it is always set to `False`. I tried it for both singlepoint calculations and geometry relaxations. The issue seems to be that it is set to `False` in `self.metadata` at the very beginning and then there is no further mention of `success` in the fchk parser.
I'm not sure if the fchk contains this information, but if it doesn't, it's a little confusing to have the success flag be `False`. Especially for singlepoint calculations in Gaussian, the .chk is written only if the job was successful as far as I know. Hence, I would expect the flag to be always `True` at least for singlepoints. For relaxations, I don't have enough experience in Gaussian to tell how it works.

Versions: 
cclib version 1.8

**Comment by berquist** [comment]
I just ran a geometry optimization that was forced to not converge, and I see `Job Status` changed from 1 to 3.  In the case of Gaussian, it should be possible to do look for this and set `self.metadata["success"] = job_status == 1`.  For the fchk output from other programs, or other output in general, where the success status isn't known or is impossible to know, success shouldn't be set at all, otherwise it's misleading.

**Comment by berquist** [comment]
I ran a single-point energy that was forced to not converge and can't even do the fchk conversion:
```console
$ formchk dvb_sp_unconverged.chk
 Read checkpoint file dvb_sp_unconverged.chk
 Write formatted file dvb_sp_unconverged.fchk
 Missing data for FChkPn.
 Error termination via Lnk1e at Sun Apr  7 14:55:04 2024.
```
so you may very well be right about single points.

**Comment by berquist** [comment]
Basically the same results in Gaussian 03 and 09 as 16.  I can try including job type (first field of second line) as a condition for setting the success flag, meaning `SP` would always be successful and `FOpt` would depend on `Job Status`. For geometry optimizations where `Job Status` isn't printed (pre-g16), success wouldn't be set: it's impossible to determine unless there are fields you can compute convergence criteria and current values from (maybe?).

I still need to check the other two fchk-generating programs I'm aware of (Psi4 and Q-Chem) but I suspect they do not generate the file at all when the calculation terminates abnormally.

**Comment by TimoSommer** [comment]
Thank you for doublechecking. I also believe that for singlepoints, the existence of an fchk means it was sucessful. I also agree the `success` flag shouldn't be set if there is simply no info about it.
