### ISSUE TITLE
Parse natural orbital populations

### ISSUE THREAD

**Issue by langner** [cclib/cclib#143]
Axel Schild has asked to parse the natural orbital occupoations numbers (populations) along with nocoeffs. These are the eigenvalues of the diagonalized density matrix (the natural orbitals are the eigenvectors), and are labelled as such in Gaussian.

Other than Gaussian, only our GAMESS-US unit tests print them, so this will require some updating of the tests if we want other programs supported.

**Comment by langner** [comment]
Would we call them `nopops`?

**Comment by berquist** [comment]
We already have `nooccnos`, and it looks like there is some test support for Gaussian and GAMESS. Molpro should be able to parse them (https://github.com/cclib/cclib/pull/286) but I'm not sure if it's tested.

**Comment by langner** [comment]
Seems you're right! Closing this in that case.
