### ISSUE TITLE
The outputs of CCread are not in line with the inputs of original Gaussian .log file

### ISSUE THREAD

**Issue by 1azyking** [cclib/cclib#1464]
Sorry to bother you. When I run the following code to get atomic forces and energy from a Gaussian .log file,

```python
data = cclib.io.ccread(log_file)
print(data.atomnos)
print(data.grads.shape)
print(data.grads)
print(data.scfenergies[0])
```

I get returns as:

```
[6 6 6 6 1 1 1 1 1 1 1 1 1 1 6 7 7 8 1 1 1 1]
(1, 22, 3)
[[[ 1.67362949e-02 -4.68006364e-03 -2.23205079e-03]
  [-5.72078294e-03  3.48601690e-05 -1.31880832e-04]
  [-5.04989255e-03  2.95022292e-03 -3.16230766e-03]
  [-4.47195111e-03 -2.16350982e-03 -5.11342903e-06]
  [-2.26548678e-03  3.69514956e-03  3.65167739e-03]
  [-3.39757816e-03 -2.26512771e-03  1.91646716e-03]
  [ 4.27689329e-04 -2.14465071e-03 -6.87611313e-04]
  [-6.73072324e-04 -1.19501817e-03  2.58258118e-03]
  [ 1.00151006e-03 -5.40283402e-04  3.54542619e-04]
  [-3.82000264e-03  9.20595104e-04  2.06035829e-03]
  [-4.71888072e-04  7.37938438e-04  2.72439899e-03]
  [-3.17633526e-04  3.51360977e-03 -1.23788334e-03]
  [ 4.95373146e-04 -1.26294889e-03 -5.07592119e-04]
  [-3.47142297e-03  7.99544326e-04 -2.62069046e-03]
  [-2.53524517e-03  1.63636828e-03 -9.52111770e-03]
  [ 8.53959518e-03  1.99806373e-02  2.44506481e-02]
  [-4.54061808e-03 -1.16277974e-02 -3.21359502e-02]
  [ 7.51630662e-03 -1.16237159e-02  2.30067246e-02]
  [-2.59954748e-03 -7.67740976e-04  2.79205935e-03]
  [ 4.48894073e-03 -9.68861012e-04 -5.25892740e-03]
  [-3.48850327e-03  3.90296553e-03  8.48199293e-04]
  [ 3.61791740e-03  1.06782808e-03 -6.88653253e-03]]]
-10441.6768285
```

In the original .log file, the SCF energy is -383.724562690 A.U., equal to -10441.6772874 eV.  Obviously, the CCread result of -10441.6768285 is not identical to the result in original file. The same confusion meanwhile occurs to the grads (atomic forces).  Different from the above code block, the reference forces in the original file are:

```
 -------------------------------------------------------------------
 Center     Atomic                   Forces (Hartrees/Bohr)
 Number     Number              X              Y              Z
 -------------------------------------------------------------------
      1        6          -0.016294739    0.003565370   -0.005362670
      2        6           0.005654948    0.000277364    0.000831022
      3        6           0.005640135   -0.002875610   -0.002031050
      4        6           0.004308420    0.002405603    0.000574229
      5        1           0.001765559   -0.003297985    0.004257629
      6        1           0.002917600    0.002580688    0.002274829
      7        1          -0.000396560    0.002063972   -0.000915431
      8        1           0.000168452    0.001408395    0.002557121
      9        1          -0.001069956    0.000506625    0.000138399
     10        1           0.003447332   -0.000558439    0.002736611
     11        1           0.000030238   -0.000518176    0.002814278
     12        1           0.000677368   -0.003568092   -0.000888027
     13        1          -0.000455640    0.001194591   -0.000680756
     14        1           0.003900216   -0.000784408   -0.001931602
     15        6           0.004196294   -0.002152414   -0.008804265
     16        7          -0.011721404   -0.018672038    0.024165025
     17        7           0.009464116    0.009591428   -0.031732904
     18        8          -0.011841819    0.012761741    0.020440751
     19        1           0.002047375    0.001105665    0.003119043
     20        1          -0.003560359    0.000345532   -0.005995836
     21        1           0.003458259   -0.003632090    0.001723544
     22        1          -0.002335837   -0.001747724   -0.007289941
 -------------------------------------------------------------------
```

It is quite confused that the values and even the signs do not match. The version of cclib package is 0.19.2. I wonder if I made any mistake, or there is any conversion relationship I overlooked. Sincerely hope to recieve replys. Thanks!

Attached is the confused Gaussian .log file. 
[PG.log](https://github.com/user-attachments/files/16414901/PG.log)

**Comment by 1azyking** [comment]
When I run the following code to get atomic forces and energy from a Gaussian .log file,

```python
data = cclib.io.ccread(log_file)
print(data.atomnos)
print(data.grads.shape)
print(data.grads)
print(data.scfenergies[0])
```

I get returns as:

```
[6 6 6 6 1 1 1 1 1 1 1 1 1 1 6 7 7 8 1 1 1 1]
(1, 22, 3)
[[[ 1.67362949e-02 -4.68006364e-03 -2.23205079e-03]
  [-5.72078294e-03  3.48601690e-05 -1.31880832e-04]
  [-5.04989255e-03  2.95022292e-03 -3.16230766e-03]
  [-4.47195111e-03 -2.16350982e-03 -5.11342903e-06]
  [-2.26548678e-03  3.69514956e-03  3.65167739e-03]
  [-3.39757816e-03 -2.26512771e-03  1.91646716e-03]
  [ 4.27689329e-04 -2.14465071e-03 -6.87611313e-04]
  [-6.73072324e-04 -1.19501817e-03  2.58258118e-03]
  [ 1.00151006e-03 -5.40283402e-04  3.54542619e-04]
  [-3.82000264e-03  9.20595104e-04  2.06035829e-03]
  [-4.71888072e-04  7.37938438e-04  2.72439899e-03]
  [-3.17633526e-04  3.51360977e-03 -1.23788334e-03]
  [ 4.95373146e-04 -1.26294889e-03 -5.07592119e-04]
  [-3.47142297e-03  7.99544326e-04 -2.62069046e-03]
  [-2.53524517e-03  1.63636828e-03 -9.52111770e-03]
  [ 8.53959518e-03  1.99806373e-02  2.44506481e-02]
  [-4.54061808e-03 -1.16277974e-02 -3.21359502e-02]
  [ 7.51630662e-03 -1.16237159e-02  2.30067246e-02]
  [-2.59954748e-03 -7.67740976e-04  2.79205935e-03]
  [ 4.48894073e-03 -9.68861012e-04 -5.25892740e-03]
  [-3.48850327e-03  3.90296553e-03  8.48199293e-04]
  [ 3.61791740e-03  1.06782808e-03 -6.88653253e-03]]]
-10441.6768285
```

In the original .log file, the SCF energy is -383.724562690 A.U., equal to -10441.6772874 eV.  Obviously, the CCread result of -10441.6768285 is not identical to the result in original file. The same confusion meanwhile occurs to the grads (atomic forces).  Different from the above code block, the reference forces in the original file are:

```
 -------------------------------------------------------------------
 Center     Atomic                   Forces (Hartrees/Bohr)
 Number     Number              X              Y              Z
 -------------------------------------------------------------------
      1        6          -0.016294739    0.003565370   -0.005362670
      2        6           0.005654948    0.000277364    0.000831022
      3        6           0.005640135   -0.002875610   -0.002031050
      4        6           0.004308420    0.002405603    0.000574229
      5        1           0.001765559   -0.003297985    0.004257629
      6        1           0.002917600    0.002580688    0.002274829
      7        1          -0.000396560    0.002063972   -0.000915431
      8        1           0.000168452    0.001408395    0.002557121
      9        1          -0.001069956    0.000506625    0.000138399
     10        1           0.003447332   -0.000558439    0.002736611
     11        1           0.000030238   -0.000518176    0.002814278
     12        1           0.000677368   -0.003568092   -0.000888027
     13        1          -0.000455640    0.001194591   -0.000680756
     14        1           0.003900216   -0.000784408   -0.001931602
     15        6           0.004196294   -0.002152414   -0.008804265
     16        7          -0.011721404   -0.018672038    0.024165025
     17        7           0.009464116    0.009591428   -0.031732904
     18        8          -0.011841819    0.012761741    0.020440751
     19        1           0.002047375    0.001105665    0.003119043
     20        1          -0.003560359    0.000345532   -0.005995836
     21        1           0.003458259   -0.003632090    0.001723544
     22        1          -0.002335837   -0.001747724   -0.007289941
 -------------------------------------------------------------------
```

It is quite confused that the values and even the signs do not match. The version of cclib package is 0.19.2. I wonder if I made any mistake, or there is any conversion relationship I overlooked. Sincerely hope to recieve replys. Thanks!

Attached is the confused Gaussian .log file. 
[PG.log](https://github.com/user-attachments/files/16414901/PG.log)

**Comment by shivupa** [comment]
Thanks for providing the output file. We will check this out. In the meantime, I am curious about this statement 

> The version of cclib package is 0.19.2

Could you detail how you installed cclib?

**Comment by 1azyking** [comment]
> Thanks for providing the output file. We will check this out. In the meantime, I am curious about this statement
> 
> > The version of cclib package is 0.19.2
> 
> Could you detail how you installed cclib?

Sincerely thanks for your reply. I apologize for my carelessness. The exact version of the cclib package I used is `1.18.1`. In my above paragraphs, I mistakenly pasted another version of the package.

**Comment by shivupa** [comment]
Sorry for the delay. Here is my analysis:
SCF energies is because our conversion factor is NIST CODATA 2010 (I know... this is going to be updated to the latest version for 2.0, but we didn't want to break backwards compatibility previously) 
https://github.com/cclib/cclib/blob/5059792776bab396ba70e71925e5607719d1ce23/cclib/parser/utils.py#L99C40-L99C51

and Grads are opposite signs to the forces because they are gradients not forces. `F=-V`

The values are different than just a sign change because they are in the standard orientation and not the input orientation, which is consistent with other codes (and consistent with the atomic coordinates we store)  see discussion here https://github.com/cclib/cclib/issues/924 and https://github.com/cclib/cclib/pull/944

**Comment by 1azyking** [comment]
> Sorry for the delay. Here is my analysis: SCF energies is because our conversion factor is NIST CODATA 2010 (I know... this is going to be updated to the latest version for 2.0, but we didn't want to break backwards compatibility previously) https://github.com/cclib/cclib/blob/5059792776bab396ba70e71925e5607719d1ce23/cclib/parser/utils.py#L99C40-L99C51
> 
> and Grads are opposite signs to the forces because they are gradients not forces. `F=-V`
> 
> The values are different than just a sign change because they are in the standard orientation and not the input orientation, which is consistent with other codes (and consistent with the atomic coordinates we store) see discussion here #924 and #944

Thanks for your reply. I got it.
