### ISSUE TITLE
D12.1 build Issue.

### ISSUE THREAD

**Issue by ijbranch** [cclib/cclib#1469]
I just downloaded the latest ccLib from GitHub.
When I try to build ccLib in D12.1 I get this error message:
[dcc64 Error] uConfigIniPersist.pas(460): E2010 Incompatible types: 'TGetCfgValueFunction' and 'Procedure'

Regards,
Ian

**Comment by berquist** [comment]
Hi Ian, I'm not sure what's going on here.  Is this Debian Bookworm?  Can you say more about how you're trying to build the package?  This error comes from Pascal code, not the Python build system, and the only code that would ever be compiled from source in the cclib dependency tree is C, so without knowing more of your process I can't say where this comes from.

**Comment by ijbranch** [comment]
Hi Eric,
              I am just trying to build it using cclib_delphi12.groupproj.
I don't know what 'Debian Bookworm' is.
I don't have any Python stuff installed.

Regards,
Ian
The Programmer's Credo:  We do these things not because they are easy, but because we thought they were going to be easy... ***@***.*** - 05/08/2016)

**Comment by berquist** [comment]
I think you have the wrong project and are likely looking for https://github.com/corneliusdavid/ccLib.  This repo is for an unrelated Python project.
