### ISSUE TITLE
Changes needed for the latest release..

### ISSUE THREAD

**Issue by ijbranch** [cclib/cclib#1472]
In CloseApplicationReg::
{ TCloseAppComponent }

procedure TCloseAppComponent.ExecuteVerb(Index: Integer);
  {$IFDEF VER130}     <<<<<
const                        <<<<<<
  sLineBreak = #13#10;
  {$ENDIF}
begin
  case Index of

In AppIdleWarn:
{$I cc.inc}

uses
  {$IFDEF XE2orHIGHER}
  Winapi.Windows, Winapi.Messages, System.SysUtils, System.Variants, System.Classes, Vcl.Graphics, System.IOUtils,
  Vcl.Controls, Vcl.Forms, Vcl.Dialogs, Vcl.Buttons, Vcl.StdCtrls, VCL.ExtCtrls          <<<<<<<<<
  {$ELSE}
  Windows, Messages, SysUtils, Classes, Graphics, Controls, Forms, Dialogs, {$IFNDEF VER130} IOUtils, {$ENDIF}
  StdCtrls, Buttons, ExtCtrls
  {$ENDIF}
   ;                                       <<<<<<<<<<
type

**Comment by shivupa** [comment]
I think this is for the other cclib? (like #1469 ?) 

Feel free to reopen if I am wrong

**Comment by ijbranch** [comment]
You are correct.  Apologies.  Too many ccLibs..  ;-)
