### ISSUE TITLE
Formaldehyde with symmetry and something else crashes Molpro parser

### ISSUE THREAD

**Issue by langner** [cclib/cclib#150]
Natural orbital occuptaion numbers are coming with #148, and Axel Schild sent in some excellent test files. In fact one of them crashes the parser in a non-trivial way so I'm creating an issue for it until I figure out the best way to fix.

File is now in cclib-data:
https://github.com/cclib/cclib-data/blob/master/Molpro/Molpro2008/ch2o_molpro_casscf.out

**Comment by langner** [comment]
This regression doesn't crash the parse anymore and gbasis seems fine in this case, but natural orbital are still not parsed. Pushing this past 1.4 so we can take another look at whether parsing for NO should in fact work here.

**Comment by berquist** [comment]
I think they should be parsed, as eventually I would like to differentiate between MP2, CI, and MCSCF natural orbitals, as well as proper symmetry handling.

**Comment by langner** [comment]
Yeah, that would be great. I've set July 17 as the publish date for 1.4.1 - so you think you could get it in by then?

**Comment by berquist** [comment]
Yes.

**Comment by berquist** [comment]
The parsing code I've added is almost identical to the MO code (`ELECTRON ORBITALS`). Are you ok with me lifting this out into a separate private method?

**Comment by langner** [comment]
Of course. That's something we should do more of.

**Comment by berquist** [comment]
The cclib PR is https://github.com/cclib/cclib/pull/286, and the cclib-data PR is https://github.com/cclib/cclib-data/pull/37.

**Comment by langner** [comment]
Fixed.
