### ISSUE TITLE
Parsing XYZ Files

### ISSUE THREAD

**Issue by exit-1** [cclib/cclib#163]
Would an xyz file (or other common chemical file formats) parser be appropriate for cclib? I imagine the supported data types for xyz file parsing would be atomcoords and atomnos.

**Comment by ATenderholt** [comment]
I don't think we've ever really thought about supporting other data types like XYZ since there are other options (e.g. OpenBabel).

I'm not completely opposed to the idea, although I think it's a bit out of the scope of cclib. Also, for me, it's below other priorities such as better PES support, CML and other export, etc.. @langner , @berquist , and @baoilleach : what do you think?

**Comment by langner** [comment]
I think we can easily support this via the openbabel bridge. Currently it does cclib->openbabel, but I see no reason to go the other way, too.

**Comment by berquist** [comment]
I think that this goes hand-in-hand with support for the writers. Other than CML, I think most other common formats don't contain quantum data.

This leads to the problem where we couldn't rely entirely on OpenBabel for reading in *quantum chemical* data from a CML-type file, but I don't think other programs can either, except for [JUMBO](http://quixote.wikispot.org/JUMBO-Converters). I haven't checked what the status of AvogadroIO is other than for CJSON, which I spoke to Marcus about; it's not standardized yet for quantum data.

My opinion is that the bridge can be extended, but we shouldn't worry (for now) about extra information that OpenBabel can't handle and throws away during the parsing.

**Comment by langner** [comment]
> My opinion is that the bridge can be extended, but we shouldn't worry (for now) about extra information that OpenBabel can't handle and throws away during the parsing.

I agree. It will solve the issue at hand, though.

> This leads to the problem where we couldn't rely entirely on OpenBabel for reading in quantum chemical data from a CML-type file, but I don't think other programs can either, except for JUMBO.

I've played around with Peter's converters a lot, with the intent of fusing them with cclib somehow. But the philosophy is really very different. So, while I think if there ever is quantum chemical data processing database online it should be running both Jumbo an cclib, I don't see a way to connect them naturally.

> I haven't checked what the status of AvogadroIO is other than for CJSON, which I spoke to Marcus about; it's not standardized yet for quantum data.

There has been talk again recently about using cclin within Avogadro, to expand the number of programs supported. The idea was to do this as a Googel Summer of Code project. @berquist maybe you are interested? Maybe you know someone interested? Here is the thread from avogadro-devel:
https://www.mail-archive.com/avogadro-devel@lists.sourceforge.net/msg00928.html

**Comment by berquist** [comment]
@langner, I have a basic CML writer implemented, just not committed yet. I haven't written anything to my `writers` branch in about a month, which I have some time for now.

**Comment by langner** [comment]
To wrap this up a bit, @berquist contributed some excellent code that I think will be the basis for a general writer capability in cclib. Here, however, I think @exit-1 wants a way to simply do this:
```
$ccget -l uracyl.xyz
cclib can parse the following attributes from uracyl.xyz
  atomcoords
  atommasses
  atomnos
  natom
$ccget atomnos uracyl.xyz
Attempting to parse uracyl.xyz
atomnos:
[7 6 1 8 7 6 8 6 6 1 1 1]
atomcoords:
[[ 5.435  3.248 -0.916]
 [ 4.091  3.266 -0.635]
 [ 6.109  3.347 -0.144]
 [ 3.647  3.394  0.495
...
```

This is excatly what #172 achieves for XYZ files and should allow other format to be loaded using openbabel, too (so, need to install python-openbabel).

**Comment by langner** [comment]
The new release 1.3.1 now contains this feature. It will probably be expanded somewhat in the future (to more formats).
