### ISSUE TITLE
Do we need an XYZ writer?

### ISSUE THREAD

**Issue by langner** [cclib/cclib#174]
Do we need to maintain our own XYZ writer since OpenBabel already does that? Depending on OpenBabel for that will also give us a multitude of other formats not specific to computational chemistry.

**Comment by berquist** [comment]
No, we do not need an XYZ writer, if we have a general interface for using Open Babel for writing files. However, I think it is good to have, since Open Babel is an external dependency. While it is more code to maintain, the format of XYZ files is so simple and unlikely to change that it should be really simple to fix if necessary.

Right now, it looks like more code to maintain than it is, because it contains functionality for choosing the geometry that should exist at a more abstract level.

**Comment by ATenderholt** [comment]
I also support having the XYZ writer, along with a few other formats like CML, CJSON, etc. as part of cclib since it removes the external OpenBabel dependency. Of course, I also like having the capability of using OpenBabel alongside cclib...

**Comment by langner** [comment]
OK, you guys have convinced me! It is worthwhile. Are there other formats you want to consider making writers for? (SDF?)

However, CML and CJSON are different, since we can put QC-specific data into those, which OpenBabel will not do for us.

**Comment by berquist** [comment]
I think that we should implicitly handle all the formats Open Babel can handle through a very generic interface, something like an `OpenBabelWriter`. This would avoid creating extra code for other formats, since Open Babel can't handle QC data anyway.

**Comment by langner** [comment]
> I think that we should implicitly handle all the formats Open Babel can handle through a very generic interface, something like an OpenBabelWriter. This would avoid creating extra code for other formats, since Open Babel can't handle QC data anyway.

Yes, of course. I meant, are there any other formats that can be handled entirely by OpenBabel (no QC data) which we would want to implement in cclib.

**Comment by joanwa** [comment]
I think to have some writers inbuilt is a good idea. I created my own simple .xyz writer to be able to create new qm input files from cclib parsed output.
However, .xyz is I think not a well defined format, programs like pymol or vmd have different specifications for a file to read, especially if one likes to put several frames in one .xyz file, say optimization steps or scans. For example there can be a header line (or not) that states the number of lines(atoms) to follow (vmd requirement), another header line with extra information (e.g. energy, that pymol would read but not vmd), empty line between two succeeding frames, and so on.
Another format I like that incorporate all the connection information as cjson does is mol2, but this one OpenBablel knows

**Comment by berquist** [comment]
What I currently have implemented is a format that VMD will read for multiple geometries; frames one after the other, with no blank lines between frames. The comment line has the filename and geometry index if available.

**Comment by langner** [comment]
Well, we could try to read both variants, best backed by some tests (example files anyone?).

For now I am closing this, since I the XYZ parser is staying. We can continue the discussion in a dedicated issue.
