### ISSUE TITLE
Molcas parser

### ISSUE THREAD

**Issue by berquist** [cclib/cclib#191]
I've been using Molcas a lot lately, and it would be nice to have a parser for it.

**Comment by langner** [comment]
That would be great. There actually is a Molcas branch, but I last touched it about a year ago. You can take a look, but it might be more productive to start from scratch.

**Comment by langner** [comment]
I updated the molcas branch from master: https://github.com/cclib/cclib/tree/molcas

**Comment by langner** [comment]
I just discovered there's no actual code for Molcas :) so basically that branch *is* master at this point.

**Comment by berquist** [comment]
Yes, I definitely haven't pushed anything, and the branch I have is empty, so the code must be in a stash somewhere...

**Comment by langner** [comment]
I meant - I don't think there ever was any code.

**Comment by berquist** [comment]
Pushing this back because

1. I don't remember what work has been done, and
2. the university Molcas license expired.

There may be missing tests, etc. At least part of the program will be open-sourced by the end of the calendar year, so I'll revisit this then.

**Comment by langner** [comment]
+1

**Comment by berquist** [comment]
@kunalsharma05 did a considerable amount of work in https://github.com/cclib/cclib/pull/514, so this is effectively done.
