### ISSUE TITLE
Towards v1.4

### ISSUE THREAD

**Issue by langner** [cclib/cclib#196]
I've reset the due date for the v1.4 milestone for the end of April... perhaps that is realistic. Here are some things we would or might include in that release:
* DALTON parser (see #167)
* upgrade of test system (see #190 and issues #45, #54, #69 and related)
* MOLCAS parser?
* various smaller additions and bugfixes

**Comment by berquist** [comment]
Since the DALTON parser is already present in the codebase, I think the focus should be there, rather than on the Molcas parser.

I also think that Cfour should probably be moved from 1.4 to 2.0.

**Comment by langner** [comment]
Yes, the focus is on the new parser. I would also like to push the tests as far as possible. This has been a real time saver in the past, and I need more tests for some cclib-based work I am doing currently.

As to Cfour, it probably won't make it of course, but I guess it depends what Adam has up his sleeve!

**Comment by ATenderholt** [comment]
Cfour will have to wait until v2.0 as there is no way I can even *start* working on it before v1.4.

**Comment by langner** [comment]
Moved the milestone to the end of May for now.

**Comment by langner** [comment]
Moved the milestone to the end of July (I will be unavailable most of the time between mid June - mid July).

**Comment by langner** [comment]
This release is long overdue. I've set the release date for April 24th (two weeks from now) and I'd like that to be final. I've created v1.5 for coordinating further backwards compatible work, and I'm going to move a lot the bugs set for v1.4 to that milestone.

**Comment by langner** [comment]
I also created a `release-1.4` branch and based it on master before @ghutchis added the fchk files since it'll be a while before we get those parsed.

**Comment by langner** [comment]
Cherry picked recent commits and created the v1.4 release. I was not able to create windows installers, however. If someone would be able to do that, that would be great. I'll keep this issue open for a few more days in case something goes wrong.

I'll send a message do cclib-devel.

@ATenderholt: do you think you could do the CCL message like in the past? Unless we don't care about that anymore.

**Comment by langner** [comment]
Before sending announcements we need to at least bump the version in the docs. Here are the necessary changes: cclib/cclib.github.io#18 - could someone look over them? I need to figure out a better way to compile those docs, because there's a lot of cruft in the pull requests.

**Comment by langner** [comment]
Would also be good to update PyPI - but I can't unless @ATenderholt or @baoilleach add me to the owners for cclib there.

**Comment by langner** [comment]
Here's the new Zenodo DOI: http://dx.doi.org/10.5281/zenodo.44552

**Comment by ATenderholt** [comment]
Yes, I can post to CCL although might have to wait until tomorrow. Also, I
can probably also do the Windows installer, but I definitely can't get to
it today.

**Comment by langner** [comment]
That would be great... it can wait.

**Comment by langner** [comment]
Updated PyPI.
