### ISSUE TITLE
Symmetry in test jobs

### ISSUE THREAD

**Issue by berquist** [cclib/cclib#197]
I'm creating/fixing test jobs in DALTON, and a potential issue is the use of symmetry in calculations. Most QC programs don't take considerable advantage of point group symmetry, but some do. DALTON (and later Molcas) can do so at all stages of a calculation. This can have implications for the ordering and number of molecular orbital coefficients and energies, plus other properties.

Should test data jobs be run with symmetry, without symmetry, both, or whatever is the default?

**Comment by langner** [comment]
Most of the test logfilles do use symmetry - at least the SP tests for dvb. This is also one of the issues I had in mind for #45.

Having both no-symmetry and symmetry variants of one test would be nice, IMO. They should have the same results, so we don't need to write any new tests (I presume).

**Comment by cstein** [comment]
I think I added at DVB example without symmetry to the regression tests when I added the initial parser.

**Comment by langner** [comment]
> I think I added at DVB example without symmetry to the regression tests when I added the initial parser.

Yes... good point. Will keep this in mind.

**Comment by langner** [comment]
On second thought, I think it will be easier to stick with what we already have: symmetry on by default for the dvb SP tests and add regressions with no symmetry as needed. This is much less work. If there is an output file with/without symmetry that does not pass, that is a good candidate for a regression test. If we decide to parse symmetry information in the future (unlikely), we should then perhaps include explicit unit tests with various kinds of symmetry.

**Comment by langner** [comment]
Any additional thoughts about this?

**Comment by berquist** [comment]
> If we decide to parse symmetry information in the future (unlikely), we should then perhaps think about including explicit unit tests with various kinds of symmetry.

I think with all the work for `gbasis`, we're already part of the way there. The tests can be added once things are more feature-complete.

I'm in agreement; this is more important for some calculations than others (TD comes to mind), but regressions can be added.
