### ISSUE TITLE
Parse Scan Geometries

### ISSUE THREAD

**Issue by LaTruelle** [cclib/cclib#211]
I would like to know the status of the development for IRC/PES Scan geometries extraction for Gaussian jobs. Is someone taking care of it, or has someone started something?

**Comment by langner** [comment]
It would help immensely if you could provide us with an example file that you would like to parse.

**Comment by LaTruelle** [comment]
Here are two examples for PES scans: [one on CO2](https://gist.github.com/LaTruelle/21926a6eb42f7cf3279a) with all possible cases (steps not fully optimized but still moving to the next, steps optimizing properly with several geometries in it, steps already optimized (only one opt cycle)) and [an other one on H2](https://gist.github.com/LaTruelle/a2100ee3f92aa60ac0a1), which is much simpler but will not cover everything.

Let me know if you want more detail, or some help on something.

**Comment by TDI-tenderholt** [comment]
There should be (initial?) support for PES calculations. Try the following:

```parser = ccopen(filename, optdone_as_list=True)```

This should store all of the geometries, including the unoptimized ones, in ```atomcoords```. The indices that correspond to the optimized point for each step should be in ```optdone```. I believe that ```scfenergies``` also contains the energies for each geometry.

So you should be able to get the optimized structures in a PES via ```atomcoords[optdone]``` and their energies with ```scfenergies[optdone]```.

**Comment by langner** [comment]
@LaTruelle - does this work for you? Eventually I think we want to make optone_as_list True by default, but the timeline is uncertain.

**Comment by LaTruelle** [comment]
So far it seems to work. I will let you know if I have questions. The only problem for IRC jobs, is that when an optimization does not work on an IRC step, then you cannot retrieve the last geometry easily, You either have to leave that step out or take everything into account. It would be nice if one could get the indexes of the last optimization step (for every IRC step) as well, so you are not left with data with holes in it...

**Comment by langner** [comment]
I would imagine this could be covered by one of the scan* attributes... would have to take a longer look to figure it out, though. Any thoughts @TDI-tenderholt @ATenderholt @berquist ?

**Comment by TDI-tenderholt** [comment]
I think the ```scan*``` attributes are only for constrained scans (e.g. Gaussian's ```Scan```) and not unconstrained scans (```IRC``` or ```Opt=ModRedundant```). 

To handle the cases where the optimizations haven't finished on an IRC step would probably require a new attribute (```opt_last_step```?) since I don't think we want to add it to ```optdone```. We should probably create new ```irc*``` attributes.

**Comment by langner** [comment]
What about and `optstart` attribute to index the starting geometries? Would that provide sufficient room to cover unconstrained scans?

**Comment by TDI-tenderholt** [comment]
I think ```optstart``` is a great idea.

**Comment by joanwa** [comment]
Hello all,
same topic but should have probably posted this earlier since it bothered me for a while. For me the "optdone_as_list=True” has one big issue: in some cases scan steps don’t converge, then the iteration limit will be hit and the scan will proceed to the next step which probably will converge. In this case one has an optdone list with one element less. In some cases the not converged step can be just a tiny vibration that is immediately solved by numerical force constants calculation and its energy will be almost the same as the no converged case.
When I parse my output with cclib I don’t even know which scan step is missing, unless there is a jump. Only indication is then the difference in indexes, i.e. optimization step n_i - n_(i-1) ~ iteration limit. Then I need to go back to the normal QM program output and manually check.
A possible solution would be to include instead of the optimization step index either some dummy variable that indicates a non converged scan step in the series, or use the last optimization index of that scan step and produce a warning that it is not converged. 
What’s your thoughts?

Best, 

Johannes

**Comment by TDI-tenderholt** [comment]
I'm hesitant to use the last optimization index if it's not converged, even if it produced a warning, since then the attribute name (i.e. ```optdone```) isn't really accurate. A dummy variable is reasonable, but then shortcuts like ```atomcoords[optdone]``` would no longer work, and would require iterating over ```optdone``` instead.

**Comment by joanwa** [comment]
Well situation right now is if one has an external list of reaction coordinates and maps them onto the scfenergies[optdone], they will have different dimensions. 
Of course one can also parse the reaction coordinate back from atomcoords[optdone] and sees the gap then. However with 2 reactions coordinates, i.e. 2 scan indices this becomes quite messy if one item is missing. Basically what I do is fold a list of say 16 scan steps back to a “correct" 4x4 step matrix along both reaction coordinates. Depending on in which order the scan is actually performed by the QM program, the energy along the list of 16 can have many gaps because of the nature of 2 reaction coordinates scanning. But now the folding back to 4x4 doesn’t work anymore unless I know where the blank "not converged” spot is and fill in something, or what I actually do is run an another constraint optimization with force calculations on this point from last optimization step and find out that it mostly converges quickly.

For the reason of not loosing the very handy atomcoords[optdone], I actually prefer the last optimization index with warning and have that not converged atomcoords[optdone] ready at hand. But maybe I’m the only one who runs into this a lot. Or perhaps someone has a better workaround for this problem?

**Comment by TDI-tenderholt** [comment]
What about another keyword like ```unconverged_in_optdone``` that turns on your desired behavior?

Or create a new attribute ```lastopt``` which does what you want, and make ```optdone``` a list of bools of the same size? This would then allow ```atomcoords[lastopt]``` to work as expected. For example

```
lastopt = [5, 8, 12, 25, 35]
optdone = [True, True, True, False, True]
```

**Comment by joanwa** [comment]
I think the combination of lastopt and optdone would be great! Both have original scan step dimensions, optdone stays as currently is and lastopt is what the name says. And also very easy to obtain current non-default optdone_as_list=True functionality by combining both.

Another “unconverged_in_optdone" switch has probably less impact for users not wanting this. I also don’t know how many already use the “optdone_as_list=True” and would like to see this as default, as already several times mentioned that it eventually (probably) will be. But I would like the change a lot, and it should ease life much for everyone parsing scans using more than 1 reaction coordinate.

**Comment by LaTruelle** [comment]
Or what you can do is add another list `optNotDone` (or something of the like) which contains the unconverged steps. This way you can have the best of both worlds: you have the converged steps, you can test if there are some steps that did not converge, and you can combine the two lists and sort them to retrieve all converged and unconverged steps.

**Comment by TDI-tenderholt** [comment]
```optNotDone``` also makes sense to me. Any comments from @langner, @berquist, or @baoilleach?

**Comment by joanwa** [comment]
that would work well also!

**Comment by langner** [comment]
I'm now thinking we effectively want information about each step, so multiplying attributes is not the way to go. How about `optstatus` or a similar name that would contain enums, for example from `[NEW, OPT, OPT_DONE, NEW, OPT, OPT, NEW, OPT, OPT_DONE]` it is obvious there was no convergence between the OPT and NEW.

This has the additional benefit of being orthogonal to the planned evolution of  `optdone`. Still, a list of indices with convergence can be had easily with `numpy.where(optstatus==OPT_DONE)`.

**Comment by TDI-tenderholt** [comment]
How would you get a list of indices that correspond to the last point for each optimization step, converged or not? ```numpy.where(optstatus[1:] == NEW) - 1```, where you assume ```optstatus[0] == NEW```?

**Comment by langner** [comment]
> How would you get a list of indices that correspond to the last point for each optimization step, converged or not? numpy.where(optstatus[1:] == NEW) - 1, where you assume optstatus[0] == NEW?

That would be one way to do it. Another would be to use a designated enum. Anyway, it is just anther idea, somewhat more general.

**Comment by LaTruelle** [comment]
@langner @TDI-tenderholt Do you have any idea of a possible schedule for implementing this? If you do not have time for this at all, I can have a go but I would need pointers as to where to include the necessary code.

**Comment by langner** [comment]
Well, is the `optstatus` generalization I outlined above satisfactory?

**Comment by LaTruelle** [comment]
`optstatus` has the benefit of being quite general so this seems fine to me. `optNotDone` was probably easier, but less flexible so has less benefits in the long run I suppose.

**Comment by joanwa** [comment]
I also like the optstatus. A logical OPT or OPT_DONE also does the job
for getting last step indices, converged or not.

**Comment by langner** [comment]
Implemented for Guassian in #224

**Comment by langner** [comment]
Please let us know what you think of the new attribute.

**Comment by joanwa** [comment]
testing it right now. Would you also like to have a gaussian .log file that has converged and not converged scan steps for testing purposes?

**Comment by langner** [comment]
That would be quite useful.

**Comment by joanwa** [comment]
ok, my testfiles would be quite large. the very reason is they didn't converge in the cycle limit, means the limit got hit couple of times. I could upload a case where every step converges, and another one where 3 out of 16 do not converge. A question regarding data type:
optdone is a boolean list, optstatus is a integer numpy array. Is it perhaps good to have either both as numpy array, or both as normal list?
Otherwise works as advertised and very happy with it :) Thank you!

**Comment by langner** [comment]
How large compressed? If not more than a few MB it is still fine as a
regression test - best would be to send it directly in pull request to
cclib/cclib-data.

So optdone started out as a Boolean, but in 2.x it will be a list of
integers (or perhaps a list of Booleans if we want it to be extra
consistent. The reason we are waiting until the next major release is to be
backwards compatible.

**Comment by joanwa** [comment]
4.2mb as .tar.bz2.

**Comment by langner** [comment]
As long as it's useful that should be fine.

**Comment by joanwa** [comment]
I don't know if it's useful. There's just no 2D-PES in /data/Gaussian/basicGaussian09 yet ...  Shall I make a pull request?

**Comment by langner** [comment]
I had a regression test in mind - so please put it in cclib/cclib-data

**Comment by LaTruelle** [comment]
Was there a change on this ? I can't seem to be able to have an optdone table when parsing an IRC calculation with the `optdone_as_list=True` option.

**Comment by LaTruelle** [comment]
Here is an example of an IRC computation that does not get its optdone table filled.
[CO2-HBH2-IRC-fw.zip](https://github.com/cclib/cclib/files/1245268/CO2-HBH2-IRC-fw.zip)

**Comment by langner** [comment]
> Here is an example of an IRC computation that does not get its optdone table filled.
> CO2-HBH2-IRC-fw.zip

This true:
```bash
$ ccget --future -l ~/CO2-HBH2-IRC-fw.zip 
Attempting to read /home/kml/CO2-HBH2-IRC-fw.zip
cclib can parse the following attributes from /home/kml/CO2-HBH2-IRC-fw.zip:
  atomcharges
  atomcoords
  atomnos
  charge
  coreelectrons
  grads
  homos
  metadata
  moenergies
  moments
  mult
  natom
  nbasis
  nmo
  optstatus
  polarizabilities
  scfenergies
  scftargets
```

But `optstatus` is parsed with OPT_UNCONVERGED everywhere:
```bash
$ ccget optstatus ~/CO2-HBH2-IRC-fw.zip 
Attempting to read /home/kml/CO2-HBH2-IRC-fw.zip
optstatus
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1]
```

Is this what you expect in `optstatus` for this file? Would you expect `None` for `optdone` or an empty list in the newer format?

**Comment by LaTruelle** [comment]
Ha, the absence of optstatus seems to be that I use the latest pip version, not the latest from git repo. I updated and get the same output as you have.

It is however not correct, since it gives a table of 49 OPT_UNCONVERGED values, when this IRC path calculation contains 105 steps, with converged and unconverged steps, most of them having actually converged.

**Comment by LaTruelle** [comment]
See #428 for a possible resolution of this issue. Let me know what you think of the result.

**Comment by LaTruelle** [comment]
I am having questions about the OPT_XXX arguments. Their usage is not perfectly clear in my opinion, especially for OPT_UNKNOWN. For instance, if you converge on the first steps every time, you will not have any OPT_NEW, they will be replaced by OPT_CONVERGED. This can happen on a lot of scans for small molecules actually. Moreover, an OPT_NEW step is also (unless convergence reached on first step) technically an OPT_UNCONVERGED step.

Is the OPT_UNCONVERGED value reserved for the final step ? In which case, it would be easy to retrieve all last steps, mixing OPT_UNCONVERGED and OPT_CONVERGED flags. However, some OPT_NEW can be missing so they should not be trusted. How necessary are they ? Shouldn't they be switched to use OPT_UNKNOWN or a somewhat different name?

**Comment by langner** [comment]
> I am having questions about the OPT_XXX arguments. Their usage is not perfectly clear in my opinion, especially for OPT_UNKNOWN. For instance, if you converge on the first steps every time, you will not have any OPT_NEW, they will be replaced by OPT_CONVERGED. This can happen on a lot of scans for small molecules actually. Moreover, an OPT_NEW step is also (unless convergence reached on first step) technically an OPT_UNCONVERGED step.
> 
> Is the OPT_UNCONVERGED value reserved for the final step ? In which case, it would be easy to retrieve all last steps, mixing OPT_UNCONVERGED and OPT_CONVERGED flags. However, some OPT_NEW can be missing so they should not be trusted. How necessary are they ? Shouldn't they be switched to use OPT_UNKNOWN or a somewhat different name?

This is a good point. Let me think about this a little bit and what would be the best course of action. @berquist @ATenderholt any comments?

**Comment by ATenderholt** [comment]
Yes, good points.

What about using bit values for ```optstatus```? Then we could encode multiple states at the same time (e.g. OPT_NEW and OPT_CONVERGED) or (e.g. OPT_NEW and OPT_UNCONVERGED). Something like:

```
OPT_NEW = 0b0001
OPT_UNCONVERGED = 0b0010
OPT_CONVERGED = 0b0100
OPT_UNKNOWN = 0b1000
```

**Comment by LaTruelle** [comment]
I agree we could thus have multi-state, but how easy will it be to use, and is OPT_NEW actually necessary ? If OPT_{UN}CONVERGED is properly set, and the rest is OPT_UNKNOWN, you can get all your values quite easily, and the OPT_NEW states can be found as those following the OPT_{UN}CONVERGED (with care taken for the beginning and end states)

**Comment by ATenderholt** [comment]
Do calculations always terminate if one of the steps doesn't converge? OPT_NEW would be useful there because you would see something like ```[ ... , OPT_UNCONVERGED, OPT_NEW, OPT_UNCONVERGED, ... ]``` instead of ```[ ... , OPT_UNCONVERGED, OPT_UNCONVERGED, OPT_UNCONVERGED, ... ]```.

**Comment by LaTruelle** [comment]
It will not terminate in scans or modredundant calculations. (I think it does in IRCs) My point was to make sure that for every scan step, only the last optimisation step will bear an `OPT_{UN}CONVERGED` value, the rest being kept at `OPT_UNKNOWN`

In that case, you would see something like `[ OPT_UNKNOWN, OPT_UNKNOWN, OPT_UNCONVERGED, OPT_CONVERGED, OPT_UNKNOWN, OPT_UNKNOWN, OPT_CONVERGED, OPT_UNCONVERGED, ]`, where steps 2 and 3 converged, steps 1 and 4 did not, but steps 2 and 4 took only one optimization cycle when steps 1 and 3 took 3 cycles to reach this convergence state.

It is also a problem of implementation and usability to me, I have no experience in using such bit values. If there is a simple (i.e. one-line) way to retrieve all `OPT_CONVERGED` and `OPT_UNCONVERGED` steps easily, or all `OPT_NEW`, then I am perfectly happy with this solution.

**Comment by berquist** [comment]
> What about using bit values for optstatus?

Will this work cleanly in both Python 2 and 3?

I'd rather use a list or dictionary of 0/1 unless there's a significant speed penalty.

**Comment by ATenderholt** [comment]
Working with bit values should be pretty easy. Here are some examples:

```
>>> OPT_NEW = 0b001
>>> OPT_UNCONVERGED = 0b010
>>> OPT_CONVERGED = 0b100
>>> optstatus = [ OPT_NEW | OPT_UNCONVERGED, OPT_UNCONVERGED, OPT_CONVERGED ]
>>> optstatus 
[3, 2, 4]
>>> converged_indices = [ x for x, y in enumerate(optstatus) if y & OPT_CONVERGED > 0 ]
>>> converged_indices
[2]
>>> new_indices = [ x for x, y in enumerate(optstatus) if y & OPT_NEW > 0 ]
>>> new_indices
[0]
>>> unconverged_indices = [ x for x, y in enumerate(optstatus) if y & OPT_UNCONVERGED > 0 ]
>>> unconverged_indices
[0, 1]
```

**Comment by ATenderholt** [comment]
And just confirmed the above works in Python 2.7.

**Comment by LaTruelle** [comment]
Then that's good for me. I have a PR already opened for the IRC support, I can work on implementing it over then next few days.

Btw, are there tests for all this? If so, can you point me to the place where they should be modified?

**Comment by LaTruelle** [comment]
Implemented in #428

**Comment by langner** [comment]
I'm OK with the bit values, but if we go in that direction it'd be good to expose commonly used operations as functions. We can't expect people to deal with the internal bit operations all the time.

**Comment by LaTruelle** [comment]
OK with making a few functions. I guessed that it should go in [data.py](https://github.com/cclib/cclib/blob/master/src/cclib/parser/data.py), as methods of the `ccData` class?

**Comment by LaTruelle** [comment]
I added functions (See a5ae7d17f0cd36c04d230ec305a07ced30e37fc6). 
`converged_geometries()` works, but `starting_geometries()` bumped into an issue due to the trimming of atomcoords performed in [gaussianparser.py](https://github.com/cclib/cclib/blob/master/src/cclib/parser/gaussianparser.py#L113-L118). Because of that, when the last step does not end up in an `OPT_DONE`, the final `OPT_NEW` is also removed, and with it the last IRC/Scan cycle... from `atomcoords`.
How necessary is that trimming, and do you know of an easy switch that would prevent this to happen? All coordinates, regardless of their status, should be appended to `atomcoords` IMHO.

**Comment by langner** [comment]
@berquist Are you OK with the bit values as implemented in #432 ?

**Comment by LaTruelle** [comment]
@langner @berquist @ATenderholt Any idea on the trimming described above?

**Comment by ATenderholt** [comment]
Perhaps the trimming in [gaussianparser.py](https://github.com/cclib/cclib/blob/master/src/cclib/parser/gaussianparser.py#L113-L118) needs to use `optstatus` instead of `optdone`?

**Comment by langner** [comment]
> All coordinates, regardless of their status, should be appended to atomcoords IMHO.

I agree, but if something is printed twice, we don't want to parse it twice.

**Comment by LaTruelle** [comment]
Indeed, I understood what is the point of this trimming and fixed it in #432.

**Comment by LaTruelle** [comment]
Since #432 was merged, I suppose we can close this.

**Comment by langner** [comment]
Thanks again for the work!

**Comment by bertadenes** [comment]
I am working with Gaussian scans (also along multiple coordinates). This helps doing so, but I am wondering if anyone is working on the scan* attributes, or shall I implement them myself?

**Comment by ATenderholt** [comment]
I don't think anyone is working on the scan* attributes right now. We'd love anything you can contribute. Note that some appear to be at least partially implemented in Gaussian: https://github.com/cclib/cclib/blob/master/cclib/parser/gaussianparser.py#L934.

**Comment by langner** [comment]
Hi Dénes. Like Adam said, all contributions are welcome. Let us know if you need help or guidance.

**Comment by kdavis2** [comment]
Hi, I was wondering if there was any update on whether or not cclib could be implemented in extracting only the optimized geometries from a Gaussian IRC scan?

**Comment by berquist** [comment]
@kdavis2 Can you give us an example to test this?

**Comment by langner** [comment]
Currently we parse all geometries, but also allow indexing by optimization status as described by `optdone` above. There are also convenience functions on the data object, I think the one you need is [converged_geometries](https://github.com/cclib/cclib/blob/master/cclib/parser/data.py#L339).
