### ISSUE TITLE
cclib and csx

### ISSUE THREAD

**Issue by bwang2453** [cclib/cclib#212]
My name is Bing Wang, a programmer at Chemical Semantics, Inc. (www.chemicalsemantics.com). Our company is trying to apply the semantic web into computational chemistry data. We have developed our XML format, which is called CSX, for containing the computational chemistry data. The cclib fits our needs very well. I am wondering if we could contribute our code into cclib so that cclib users could generate the CSX file and upload into our portal.

**Comment by berquist** [comment]
I became really interested in adding this myself after hearing Neil Ostlund's talk at the last ACS meeting, and it would fit nicely into the "writer" utilities we've been slowly developing, so I think it would be a great addition.

**Comment by langner** [comment]
Yes, this would be a much welcomed addition to cclib!

**Comment by berquist** [comment]
New issue: https://github.com/cclib/cclib/issues/240

**Comment by langner** [comment]
Closing this since it's a no-op and work has moved forward elsewhere.
