### ISSUE TITLE
python 3.5 support for tests - cclib-1.3.1

### ISSUE THREAD

**Issue by nonamedotc** [cclib/cclib#213]
Are tests included in the v1.3.1 tarball supposed to work with python 3.5?

When trying to build a rpm, tests seem to fail.

```bash
+ python3 testall.py
Could not import openbabel, fallback mechanism might not work.
**** ADF2007.01/dvb_sp_b.adfout: Customized restricted single point unittest ****
Traceback (most recent call last):
  File "testall.py", line 268, in <module>
    tests = testall(parsers, modules, status, terse)
  File "testall.py", line 204, in testall
    test.data, test.logfile = getfile(eval(parser), *location, stream=stream)
  File "testall.py", line 52, in getfile
    location = os.path.join(("..", "data", get_program_dir(parser.__name__)) + location)
  File "/usr/lib64/python3.5/posixpath.py", line 89, in join
    genericpath._check_arg_types('join', a, *p)
  File "/usr/lib64/python3.5/genericpath.py", line 143, in _check_arg_types
    (funcname, s.__class__.__name__)) from None
TypeError: join() argument must be str or bytes, not 'tuple'
```

Building with tests disabled, rpm building completely as expected and provides correct requires as well.

```bash
$ rpm -qRp python3-cclib-1.3.1-3.fc24.noarch.rpm
/usr/bin/python3
python(abi) = 3.5
python3-numpy
rpmlib(CompressedFileNames) <= 3.0.4-1
rpmlib(FileDigests) <= 4.6.0-1
rpmlib(PayloadFilesHavePrefix) <= 4.0-1
rpmlib(PayloadIsXz) <= 5.2-1
```

Failed build - https://koji.fedoraproject.org/koji/taskinfo?taskID=11793722
Successful build - https://koji.fedoraproject.org/koji/taskinfo?taskID=11838273

**Comment by TDI-tenderholt** [comment]
Thanks for reporting the issue. I've confirmed that it doesn't work with Python 3.5 (installed on Mac with Homebrew). It appears the behavior of ```os.path.join``` changed between versions 3.4 and 3.5, although I didn't see any mention in Python release notes or change log:

```
Python 3.4.1 (default, Jul  3 2014, 19:48:56) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-4)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import os.path
>>> os.path.join(("a", "b"))
('a', 'b')
```

```
Python 3.5.0 (default, Sep 14 2015, 11:35:12) 
[GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.49)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import os.path
>>> os.path.join(("a", "b"))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/posixpath.py", line 89, in join
    genericpath._check_arg_types('join', a, *p)
  File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/genericpath.py", line 143, in _check_arg_types
    (funcname, s.__class__.__name__)) from None
TypeError: join() argument must be str or bytes, not 'tuple'
```

**Comment by baoilleach** [comment]
But either way, shouldn't it be os.path.join("a", "b") ?

**Comment by langner** [comment]
It most definitely should! However, that code is old and we don't do that anymore as far as I can see. The testall.py script has also moved, here is the relevant new code I think:
https://github.com/cclib/cclib/blob/92d5d6a4cc32aeb8b79131ab98da1c074605a1ef/test/test_data.py#L96

@nonamedotc what version are you using?

**Comment by nonamedotc** [comment]
@langner I am on Python 3.5.

**Comment by langner** [comment]
I meant what version of cclib.

**Comment by abadger** [comment]
Looks like 1.3.1 coming from this github link for the source code: https://github.com/cclib/cclib/archive/v1.3.1.tar.gz

**Comment by abadger** [comment]
It's being built from this source repository: http://pkgs.fedoraproject.org/cgit/python-cclib.git/tree/  I checked that the md5sum in the sources file there matched with what's available at the github archive link.

**Comment by langner** [comment]
I see. So would a 1.3.2 release with this fixed be OK? I could do that this week.

**Comment by nonamedotc** [comment]
@langner  Sounds perfect.

**Comment by langner** [comment]
@nonamedotc could you confirm that branch v1.3.2 fixes this?
https://github.com/cclib/cclib/tree/v1.3.2

If that is the case, I will create a new release based on that.

**Comment by nonamedotc** [comment]
Thanks! Will report back tomorrow after testing!

**Comment by nonamedotc** [comment]
@langner This works perfectly. Thanks for quick fix!

https://koji.fedoraproject.org/koji/taskinfo?taskID=12088893

Here is the build log - https://kojipkgs.fedoraproject.org//work/tasks/8893/12088893/build.log

**Comment by langner** [comment]
That's great. I created the release now (https://github.com/cclib/cclib/releases/tag/v.1.3.2) and will update it with the bdists soon.

**Comment by nonamedotc** [comment]
Checked in and built on Fedora. All is well now. Thanks for the release.

**Comment by langner** [comment]
Release is updated with final files and newly minted DOI.
