### ISSUE TITLE
loading multiple Gaussian log files

### ISSUE THREAD

**Issue by ChayaSt** [cclib/cclib#222]
There seems to be something off with how the files are being parsed when multiple files are parsed with the Gaussian parser. Here are some tests I did

```
from cclib.parser import Gaussian
from numpy.testing import assert_almost_equal
import numpy as np

log1 = Gaussian('testing/reference/PRL.scan2.neg.log')
log2 = Gaussian('testing/reference/PRL.scan2.pos.log')
log = Gaussian(['testing/reference/PRL.scan2.neg.log', 'testing/reference/PRL.scan2.pos.log'])

data1 = log1.parse()
data2 = log2.parse()
data = log.parse()

positions_all = np.append(data1.atomcoords, data2.atomcoords, axis=0)
```

```
assert_almost_equal(data1.atomcoords, data.atomcoords[:40])
```

This passes

```
assert_almost_equal(data1.atomcoords, positions_all[:40])
```

passes

```
assert_almost_equal(data2.atomcoords, data.atomcoords[40:])
```

fails. I get the following error:

```
AssertionError: 
Arrays are not almost equal to 7 decimals

(mismatch 99.96212121212122%)
 x: array([[[ 2.471965,  0.316529,  0.287968],
        [ 1.075144,  0.834374, -0.061614],
        [ 0.288424, -0.294688, -0.323138],...
 y: array([[[-2.283659,  0.536695, -0.374085],
        [-0.876468,  0.859499,  0.133808],
        [-0.239545, -0.372688,  0.344585],...

```

```
assert_almost_equal(data2.atomcoords, positions_all[40:])
```

passes

```
assert_almost_equal(data.atomcoords, positions_all)
```

fails with the following error

```
AssertionError: 
Arrays are not almost equal to 7 decimals

(mismatch 49.98106060606061%)
 x: array([[[ 2.471965,  0.316529,  0.287968],
        [ 1.075144,  0.834374, -0.061614],
        [ 0.288424, -0.294688, -0.323138],...
 y: array([[[ 2.471965,  0.316529,  0.287968],
        [ 1.075144,  0.834374, -0.061614],
        [ 0.288424, -0.294688, -0.323138],...
```

Here is a link to the log files I used:
https://github.com/ChayaSt/Torsions/tree/fragments/torsionfit/testing/reference

I'm using the current master branch (with PR #218)

**Comment by langner** [comment]
Confirmed with current master.

**Comment by langner** [comment]
What is happening here is that cclib tries to trim the last repeated standard orientation Gaussian prints after a converged optimization. When we wrote that we assumed there is one output file at hand, and furthermore do the trimming based on `optdone`. In your case there are 41 standard orientations in each file and the parser blindly trims the full 82 in the concatenated stream to 80. So, this should work:
`assert_almost_equal(data.atomcoords[41:], data2.atomcoords[:-1])`

We didn't anticipate people glueing Gaussian outputs together and I don't think that is a good thing to do in general. However, it will not be too much work to fix this particular case with better checking.

**Comment by ChayaSt** [comment]
Thanks.
I'm glueing the Gaussian output of the torsion scan together because I'm trying to fit torsion parameters for Molecular Mechanics force fields. I need all coordinates in a numpy array and I calculate the MM energy of this array for every proposal of parameter set. Can you explain why you think that is not a good idea? 
Location of files changed. They are now living here:
https://github.com/ChayaSt/torsionfit/tree/fragments/torsionfit/tests/reference

**Comment by langner** [comment]
So `positions_all = np.append(data1.atomcoords, data2.atomcoords, axis=0)` seems sufficient to this end and gets you what you need. I see no reason to concatenate two output files that are distinct jobs (from Gaussian's point of view). That having been said, I still think we can do better and have this as a regression since the current behavior is not the expected one and the way coordinates are trimmed now is not optimal.

**Comment by langner** [comment]
Reviewed this again I think cclib is doing the right thing. Logfiles from two separate jobs should be parsed separately, and then can be processed as needed.
