### ISSUE TITLE
PC GAMESS/Firefly parser failes to parse MOs from geometry optimizations?

### ISSUE THREAD

**Issue by mkrompiec** [cclib/cclib#228]
Test case: geometry optimization or single-point calculation on naphthalene (see attached input and output files). The parser reads correctly the single-point calculation, but fails on the geometry optimization. Basis set and all Firefly options are the same in both cases.

[naphtalene.zip](https://github.com/cclib/cclib/files/88720/naphtalene.zip)

Python 2.7.10 (default, Jul 20 2015, 12:26:59)
[GCC 4.3.4 [gcc-4_3-branch revision 152973]] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from cclib.parser import ccopen
>>> ff_in=ccopen("t_0.out")
>>> data=ff_in.parse()
[GAMESS t_0.out WARNING] MO section found but could not be parsed!
[GAMESS t_0.out WARNING] Overwriting previous multipole moments with new values
[GAMESS t_0.out WARNING] This could be from post-HF properties or geometry optimization
>>> ff_in=ccopen("t_0_SP.out")
>>> data=ff_in.parse()
>>>

**Comment by mkrompiec** [comment]
Actually, it is more complicated, dependent on the Firefly binaries.
For most recent binaries (8.1.1), the parser displays the warning message (which is misleading), but actually parses the MOs correctly (there is only one set of MOs in the test file, for the optimised geometry). 
Older binaries (verified for 8.1.0) add the following message in many places of the output file:
 WARNING! THIS VERSION OF FIREFLY IS PROBABLY OUTDATED!
 PLEASE CHECK FIREFLY HOMEPAGE FOR INFORMATION ON UPDATES!
And this message causes the parser to fail as in the following example, whilst displaying the same warning:
>>> ff_in=ccopen("eu3_combo_uks_1_s0.out")
>>> data=ff_in.parse()
[GAMESS eu3_combo_uks_1_s0.out WARNING] MO section found but could not be parsed!
[GAMESS eu3_combo_uks_1_s0.out WARNING] Overwriting previous multipole moments with new values
[GAMESS eu3_combo_uks_1_s0.out WARNING] This could be from post-HF properties or geometry optimization
>>> data.moenergies[0][0]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
IndexError: index 0 is out of bounds for axis 0 with size 0

**Comment by langner** [comment]
Thanks for reporting this. Can we use your files as regression tests?

**Comment by mkrompiec** [comment]
Yes, sure.

**Comment by langner** [comment]
Couldn't get to this for 1.4 - pushing back.

**Comment by berquist** [comment]
> WARNING! THIS VERSION OF FIREFLY IS PROBABLY OUTDATED! PLEASE CHECK FIREFLY HOMEPAGE FOR INFORMATION ON UPDATES!

@mkrompiec, could you post an example of one of these outputs as well?

**Comment by langner** [comment]
Will close before launching 1.4.1 if we get no response.

**Comment by mkrompiec** [comment]
I'll try to dig out some examples before Monday, I should still have the
old binaries somewhere.

**Comment by langner** [comment]
Thanks!

**Comment by mkrompiec** [comment]
This is an example file with the warning about outdated version of Firefly, which causes cclib to crash:

[benzene_am1_log.zip](https://github.com/cclib/cclib/files/359376/benzene_am1_log.zip)

**Comment by baoilleach** [comment]
Just to note that I think that those warnings are inserted into the output
after a specific date compared to when it was released or downloaded. So it
will happen to all releases eventually.

**Comment by mkrompiec** [comment]
That's correct. And even though Firefly is freely available (and therefore
can be updated as required), we cannot assume that it will be maintained
forever...

**Comment by berquist** [comment]
Please test the latest git version of cclib if you can; `ccget --list --verbose` seems to work fine for both Python 2 and 3 on this file for me.

**Comment by langner** [comment]
Adding files in cclib/cclib-data#40.

**Comment by langner** [comment]
I think we've covered everything here. Thanks again!
