### ISSUE TITLE
bugs in gamess/firefly parser

### ISSUE THREAD

**Issue by mkrompiec** [cclib/cclib#238]
I don't have the "offending" logfiles at hand (they would be confidential, anyway, and were deleted by my workflow), but the exceptions are as follows:

local variable 'maximum' referenced before assignment  
Looks like line 412: self.geovalues.append([maximum, rms]) assuming that maximum has already been assigned. The logfile is a single-point energy run, so this should not happen, should it?

could not convert string to float: ********** (non-numbers created by Firefly if the number of digits is "too large")

**Comment by langner** [comment]
We can fix this if you provide us with an example output that reproduces the issue.

**Comment by berquist** [comment]
@mkrompiec, can you create an example output for us?

**Comment by langner** [comment]
Not the same as #228 but it's been some time, so closing.
