### ISSUE TITLE
CSX generation

### ISSUE THREAD

**Issue by bwang2453** [cclib/cclib#240]
Hi, cclibers,

As I promised, I enabled cclib to generate CSX file. The code is here: https://github.com/chemsem/cclib

If you think everything is fine, I could check my codes into the main repository of cclib. 

Once the csx file generated, you could publish it on our portal demo386.chemsem.com (registration first). The uploading instruction is the following:

1. click "Add publication" button, and a basic information page pops up.
2. fill out those basic information (title, abstract, category, etc.)
3. click "save changes" button, and a "Data sets" tab appears.
4. click "Browse" button, select the csx file you want to upload in your local machine.
5. select "Add CSX/CML file" option in the dropdown box.
6. click "Upload file".

Even better, at step 4, you could directly select the output file from quantum chemistry, and at step 5, select "Add Output file". You could do this because our portal uses my version of cclib to parse the output file.

If you have any questions and comments, please let me know!

Bing

**Comment by langner** [comment]
I don't think there's anything actionable here.
