### ISSUE TITLE
Absence of testall.py

### ISSUE THREAD

**Issue by Schamnad** [cclib/cclib#251]
Hello,

I am an aspirant for GSOC-2016, I am working on a proposal for the project:integration of cclib with Avogadro2. 
With regards to this, I built cclib from source and according to the Install instructions, there should be testall.py file in the test/ directory. In the master branch this python file is absent but when I checked older forks (like ATenderholt / cclib) this file is present. The directory structure in the ATenderholt / cclib fork and the master branch is also different.

Either we should update the readme file or has the testall.py file been deprecated?

**Comment by berquist** [comment]
Yes, it looks like that part of the documentation is out-of-date; the contents of `testall.py` have been broken up into several files. Take a look at the file that runs for our continuous integration testing to see how tests run. [Here](https://gist.github.com/b0c2c5004f1ac25748ce) is a copy of it as a shell script.

**Comment by berquist** [comment]
Hi @Schamnad, I'm in the process of updating the documentation, including the tutorial. Please post an issue [here](https://github.com/cclib/cclib.github.io/issues) if you find any other problems so I can fix them.

**Comment by Schamnad** [comment]
Hello @berquist, I shall update any issues that I find with it's own issue thread. I am looking at ways to contribute to cclib, if you require any help in updating the documentation I would be glad to help.
Currently I have started working on providing some usage examples for cclib ([issue 6 ](https://github.com/cclib/cclib.github.io/issues/6)

Do I close this thread as the initial issue has been resolved, albeit in an ad hoc manner

**Comment by langner** [comment]
@berquist I don't know what you've updated so far, but I added a fix to the Makefile in the docs and bumped the version - see cclib/cclib.github.io#12

**Comment by langner** [comment]
Unfortunately the production code has evolved a lot sine the docs were last updated. I want to release v1.4 in two weeks. Let's try to get the docs up to date for that.

**Comment by langner** [comment]
Closing this. Further work/discussion at cclib/cclib.github.io#16
