### ISSUE TITLE
Parse GAMESS *.dat files

### ISSUE THREAD

**Issue by berquist** [cclib/cclib#254]
This has been requested by a coworker. They contain the `$HESS` block with the molecular Hessian (if doing a frequency calculation) and one or more `$VEC` blocks for canonical and natural MO coefficients, among other things.

**Comment by langner** [comment]
Would anyone be up to adding the *.out files for all unit tests?

**Comment by berquist** [comment]
Yes, I can run them.

**Comment by berquist** [comment]
Actually, it looks like I don't have access to 2012, just 2013 and 2014. What should I do?

**Comment by langner** [comment]
Let's update the unit tests and move 2012 to cclib-data for v1.5.

**Comment by berquist** [comment]
Done in #1208, #1214, and #1229.
