### ISSUE TITLE
Support for molecular polarizability

### ISSUE THREAD

**Issue by ghutchis** [cclib/cclib#255]
I'd like to add support for polarizability (and perhaps hyperpolarizability tensors). The format would be similar to multipole moments.

Thoughts or issues?

I can contribute to Gaussian, and MOPAC format, with examples.

**Comment by bwang2453** [comment]
Absolutely! It's on my to-do lists. I can provide some example files from NWChem, GAMESS and QChem.

**Comment by ghutchis** [comment]
I think a key question would be units, e.g. a.u. or Å^3. Personally, I'd be in favor of Å^3.

**Comment by bwang2453** [comment]
I think a.u. is used consistently in most packages, and it is also applied for hyperpolarizabilities and second hyperpolarizabilities. 

Another thing we need to consider is that those values are static or dynamic (field-dependent), although we are talking about static values in most cases.

**Comment by ghutchis** [comment]
Let's start with the static values. Most people don't do dynamic calculations unless they're really into NLO. (I'm not - at the moment.) I think adding at least polarizability would greatly help electrostatics, etc.

I'm OK with a.u. for units. I think the main thing would be to offer conversions into util.py.

**Comment by langner** [comment]
Atomic units would probably be the natural choice since moments are parsed in those. We do have conversion utilities available in util.py, we should add the appropriate things there.

**Comment by berquist** [comment]
> Another thing we need to consider is that those values are static or dynamic (field-dependent), although we are talking about static values in most cases.

I don't think there's a distinction as far as the parsers are concerned, though one would want to keep track of the input wavelength/energy in the dynamic case.

**Comment by bwang2453** [comment]
Yes, we just need to keep track of the input wavelength in the dynamic case for polarizability. for hyperpolzaribility, we need to know the frequency mixing process, such as SHG, OR, etc.

**Comment by berquist** [comment]
PR is https://github.com/cclib/cclib/pull/290.

**Comment by langner** [comment]
Done.
