### ISSUE TITLE
Support for rotational constants

### ISSUE THREAD

**Issue by ghutchis** [cclib/cclib#256]
I think there should be support for rotational constants - either in cm-1 or GHz.

These would be stored as an array of rank 1 (i.e., 3 of them). I can contribute a bunch of examples.

**Comment by ghutchis** [comment]
I mention this because I'd really like to plot rotational spectra in Avogadro and PQR.pitt.edu.

**Comment by berquist** [comment]
I'm not against this, but not every program calculates this even though it is easy enough to calculate separately: https://gist.github.com/c730ca8a2af4df112933dc4d310ac554

**Comment by langner** [comment]
We already both parse and calculate some things (populations come to mind), so this is a matter of taste. Can we add a method for rotational constants based on your gist?

**Comment by berquist** [comment]
> Can we add a method for rotational constants based on your gist?

Yes, I was thinking of this. I'll clean it up and add it.

**Comment by ghutchis** [comment]
One nitpick - these should be be exact isotopic masses..

**Comment by berquist** [comment]
That would explain why my numbers are slightly off. Now I think it's a good idea for this to be added to the parser.

**Comment by ghutchis** [comment]
Have we defined an attribute name? I can add a few of these (e.g., Gaussian, MOPAC). I'll see if I have time to add the list of default isotopic masses too.

**Comment by berquist** [comment]
It looks like I was going to call it `rotcons`.

Having a list of default isotopic masses would be a great help.

**Comment by langner** [comment]
Why not `rotconst`?

If we ever get to version 2.0 I would advocate more verbose attribute names.

**Comment by berquist** [comment]
No particular reason. I agree.

**Comment by langner** [comment]
Pushing back.

**Comment by berquist** [comment]
I have an implementation as part of the Nuclear method. Physical constants come from [`scipy.constants`](https://docs.scipy.org/doc/scipy/reference/constants.html) and isotopic masses come from [`periodictable`](https://pypi.org/project/periodictable/). For isotopic masses, the most abundant isotope is used.

Are there better choices?

**Comment by berquist** [comment]
No, this is done, taken care of by https://github.com/cclib/cclib/pull/568.
