### ISSUE TITLE
Support for molecular point group symmetry

### ISSUE THREAD

**Issue by ghutchis** [cclib/cclib#258]
While mosyms and vibsyms exist, the molecular point group symmetry "sym" is not parsed. This is extremely useful to know if a calculation was performed in a reduced symmetry.

**Comment by bwang2453** [comment]
Maybe we could put the molecular symmetry in the metadata.

**Comment by langner** [comment]
Sure, I can see that as being useful.

**Comment by berquist** [comment]
I have started parsing the full and Abelian/reduced point group from every program. I like the idea of putting both in the metadata, once it's available in all the parsers.

**Comment by langner** [comment]
Cool, will you finish before the 1.5 release (mid August)?

**Comment by berquist** [comment]
Thinking about v2.0, I would really like it if this was extended to more than just a string `d2h`, `c2v`, `cs`, and so on. In addition to determining the point group, there should be the ability to parse the number of doubly-occupied/singly-occupied/empty/total irreps, or calculate them if enough information is available.

This would enable, for the future, proper handling of symmetry-adapted orbitals for `mocoeffs` and MCSCF calculations.

**Comment by ghutchis** [comment]
I'd recommend optional integration with https://github.com/mcodev31/libmsym

libmsym has a small Python wrapper and can produce much of this, including symmetry-projected orbitals.

**Comment by ghutchis** [comment]
Not sure how much of your suggestion would need to be in cclib vs. already in libmsym, but certainly handling the irreps, etc. is already implemented.

**Comment by berquist** [comment]
Yes, I'd definitely like that. I think it would be a good candidate as a bridge, rather than a hard dependency. I don't think any point group math needs to be added to cclib directly, since programs are usually nice enough to print the irrep ordering for you, but if we offer any symmetry-based methods in the future, libmsym would probably be needed.

**Comment by berquist** [comment]
The first part is done in https://github.com/cclib/cclib/pull/839.
