### ISSUE TITLE
ccwrite fails to write cjson format

### ISSUE THREAD

**Issue by Schamnad** [cclib/cclib#261]
While I was working on creating the examples page ([Pull request](https://github.com/cclib/cclib.github.io/pull/17)), I was testing out the capabilities of the ccwrite script.  All the testing was done using a Gaussian09 opt-freq job done at the b3lyp/6-311++g(3df,3pd) for a Benzeneselenol molecule.

The ccwrite script provides an output format of cjson/json but whenever I try to use it to write my .out file into the cjson format, it throws the following error : 

> Traceback (most recent call last):
>   File "/usr/local/bin/ccwrite", line 84, in <module>
>     main()
>   File "/usr/local/bin/ccwrite", line 80, in main
>     ccwrite(data, outputtype, outputdest, *_ccwrite_kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/cclib/writer/ccwrite.py", line 70, in ccwrite
>     outputobj = outputclass(ccdata, jobfilename=jobfilename, *args, *_kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/cclib/writer/cjsonwriter.py", line 38, in **init**
>     self.generate_repr()
>   File "/usr/local/lib/python2.7/dist-packages/cclib/writer/cjsonwriter.py", line 104, in generate_repr
>     cjson_dict['totalDipoleMoment'] = self._calculate_total_dipole_moment()
>   File "/usr/local/lib/python2.7/dist-packages/cclib/writer/filewriter.py", line 78, in _calculate_total_dipole_moment
>     return sqrt(sum(self.ccdata.moments[1] *\* 2))
> AttributeError: 'ccData_optdone_bool' object has no attribute 'moments'

When I use the cml or xyz format with ccwrite, this error is absent and I get a valid output file. From what I could figure out is that my output file doesn't have any moments information. It crashes at this point. I commented this line (no. 78) out, and ccwrite json worked perfectly and provided the cjson output.

**Comment by berquist** [comment]
> From what I could figure out is that my output file doesn't have any moments information.

Yes, this is a classic `AttributeError`. The CML and CJSON writers should do a better job of error handling. Can you post the output file?

**Comment by Schamnad** [comment]
Github, unfortunately, doesn't allow me to upload *.out files here. I have shared the Gaussian09 ouput file on google drive ([Link](https://drive.google.com/open?id=0B07sfcCrfAN5aWtsZzU1QndvME0)).

I am looking at fixing the bug, hopefully will submit a fix within the week.

**Comment by langner** [comment]
It would be great if you could get the fix in for version 1.4 (which I will release on April 24th). Let me know if you need any help with that.

Also, could you contribute the output file you have to the cclib-data repository? We could then create a regression test to make sure this doesn't happen again.

**Comment by berquist** [comment]
I've added some basic checks for attributes before writing in https://github.com/cclib/cclib/pull/265. Your output file doesn't crash anymore, though it seems odd that `moments` aren't detected.

**Comment by langner** [comment]
Thanks @berquist.

I'll wait for @Schamnad to add the file to cclib-data - let me know if you need help with that. Keeping this open until that gets settled.

I created #266 for the moments issue which we can deal with later.

**Comment by Schamnad** [comment]
Have added the Gaussian input and output file to cclib-data - have created a Pull request [here](https://github.com/cclib/cclib-data/pull/30) 
Thanks @berquist for the fix. Since the original issue has been fixed, I am closing this issue.

**Comment by langner** [comment]
Reopening as I'd like to add a regression test for ccwrite with this file to cclib-data.
