### ISSUE TITLE
Moments not parsed for Benzeneselenol

### ISSUE THREAD

**Issue by langner** [cclib/cclib#266]
This is a follow-up to #261 concerning the fact that moments don't seem to get parsed for that regression.

**Comment by berquist** [comment]
Just putting the cclib-data link here: https://github.com/cclib/cclib-data/pull/30

**Comment by langner** [comment]
Note: add regression test for moments for that output file once the fix is in.

**Comment by berquist** [comment]
Maybe this was already obvious, but I didn't realize `moments` isn't implemented for Gaussian at all.

**Comment by langner** [comment]
Wasn't to me. Pushing back to 1.5.

**Comment by berquist** [comment]
https://github.com/cclib/cclib-data/pull/48 is a regression to check for this, now that `moments` are implemented.

**Comment by langner** [comment]
This looks all done.
