### ISSUE TITLE
Support URLs in ccget 

### ISSUE THREAD

**Issue by langner** [cclib/cclib#267]

**Comment by gaursagar** [comment]
I would like to help. Can you provide more information about what needs to be done?

**Comment by langner** [comment]
The idea is to add the ability to pass URLs for ccget on the command line, so you could load things from the the web. cclib already support this internally, so it's just a question of updating that script.

**Comment by gaursagar** [comment]
I suggest using constructor overloading or some sort of implicit URL validation for the input filename.
The second approach can be easily implemented in the `openlogfile` module of [parser/logfileparser.py](https://github.com/cclib/cclib/blob/master/src/cclib/parser/logfileparser.py#L128).

After URL validation, the file can be downloaded either to the working directory or a temporary directory using `urllib.request` module as follows,
1. Saving to a temporary location
`tempfile_path, http_messege = urllib.request.urlretrieve(url)`
2. or, Saving to some other path
`urllib.request.urlretrieve(url, file_path)`

The saved file can be opened and used as any other local file would be used. 
I can implement this code and create a PR if this approach sounds fine.

**Comment by langner** [comment]
@gaursagar I don't think we need to validate anything. cclib already support loading the URLs, we just need to make sure the `ccget` script support it as well.

**Comment by gaursagar** [comment]
I believe ccget has support for file handling after PR #351 ([change](https://github.com/cclib/cclib/commit/9c15985c85a2b198a2b8a7411a20628220a990ad#diff-77f83a1127aa56589d06e360cca19da9)). Please verify.

The following is working for me,
``` 
ccget -l https://raw.githubusercontent.com/cclib/cclib/master/data/Molpro/basicMolpro2012/dvb_gopt.log https://raw.githubusercontent.com/cclib/cclib/master/data/Molpro/basicMolpro2012/h2o_mp2.out
```
and giving output:
```
Attempting to read https://raw.githubusercontent.com/cclib/cclib/master/data/Molpro/basicMolpro2012/dvb_gopt.log
cclib can parse the following attributes from https://raw.githubusercontent.com/cclib/cclib/master/data/Molpro/basicMolpro2012/dvb_gopt.log:
  aonames
  atombasis
  atomcoords
  atomnos
  charge
  coreelectrons
  gbasis
  geotargets
  homos
  metadata
  moments
  mult
  natom
  nbasis
  nmo
  scfenergies
  scftargets
  scfvalues
Attempting to read https://raw.githubusercontent.com/cclib/cclib/master/data/Molpro/basicMolpro2012/h2o_mp2.out
cclib can parse the following attributes from https://raw.githubusercontent.com/cclib/cclib/master/data/Molpro/basicMolpro2012/h2o_mp2.out:
  atomcoords
  atomnos
  charge
  coreelectrons
  geotargets
  homos
  metadata
  moments
  mpenergies
  mult
  natom
  nbasis
  nmo
  scfenergies
  scftargets
  scfvalues
``` 
If this is the expected behavior, this issue can be closed.

**Comment by langner** [comment]
@gaursagar Could you make sure we have appropriate unit tests for this? Related to #54

**Comment by gaursagar** [comment]
Yes, I will look into making the tests.

**Comment by gaursagar** [comment]
`ccget` [calls](https://github.com/cclib/cclib/blob/master/src/scripts/ccget#L156) `ccopen` via `ccread`  for all sorts of file handling including URL IO. Tests for these already cover [URL handling](https://github.com/cclib/cclib/blob/master/test/io/testccio.py#L88).

If there is any interest in testing `ccget` as a  script, can we consider using bash scripts?

```bash
#!/bin/bash
function assertEquals()
{
    MESSEGE=$1; shift
    EXPECTED=$1; shift
    ACTUAL=$1; shift
    echo -n "$MESSEGE: "
    if [ "$EXPECTED" != "$ACTUAL" ]; then
        echo "FAILED: EXPECTED=$EXPECTED ACTUAL=$ACTUAL"
    else
        echo PASSED
    fi
}

ACTUAL=$(ccget -l https://raw.githubusercontent.com/cclib/cclib/master/data/QChem/basicQChem4.2/C_bigbasis.out | xargs | md5)
EXPECTED=$(echo "Attempting to read https://raw.githubusercontent.com/cclib/cclib/master/data/QChem/basicQChem4.2/C_bigbasis.out
cclib can parse the following attributes from https://raw.githubusercontent.com/cclib/cclib/master/data/QChem/basicQChem4.2/C_bigbasis.out: aonames atombasis atomcharges atomcoords atomnos charge coreelectrons enthalpy entropy freeenergy gbasis homos metadata mocoeffs moenergies moments mult natom nbasis nmo pressure scfenergies scftargets scfvalues temperature" | xargs | md5)
assertEquals "checking ccget url IO" $EXPECTED $ACTUAL
```

**Comment by berquist** [comment]
> If there is any interest in testing ccget as a script, can we consider using bash scripts?

I am definitely interested in this.

**Comment by berquist** [comment]
I don't know much about testing shell scripts (since I've never done it), so this looks like a good start to me. There are probably "best practices" that I'm unaware of.

I think the exit codes (stored in `$?` after each command) should also be checked, though I don't know if Python automatically sets the right code upon success or failure (such as when we'd have an `AttributeError`).

One other thing is that we'd need to generalize the above to take any path (not just a URL) and the attributes, but that shouldn't be too bad.

**Comment by langner** [comment]
As much as I love to write bash scripts, I would avoid writing tests in bash. And, why would we write tests in bash if we have Python at our disposal? And, `ccget` is a Python function, it seems much more straightforward to test that function in Python - perhaps breaking it up into smaller pieces where convenient.

**Comment by gaursagar** [comment]
Breaking ccget into functions​ would be a better idea. Currently it is a
single large function, making writing python unittests not so
straightforward.

**Comment by berquist** [comment]
I suppose that since there would be no problems with the Python -> Bash interface, just breakage Python-side, that shell script tests are unnecessary.

**Comment by langner** [comment]
Moving any logic that we can to a module would be great, since we could unit test that. Taking a second look at `ccget`, however, a substantial amount of code would stay there (dealing with arguments and inputs).

Given that we currently have failures with the scripts, I suggest adding a regression test that runs against all logfiles (at least the unit test ones for now) - and including that in Travis CI. Sagar says it runs in 2 minutes, which is on the same scale as the existing regressions.

**Comment by TDI-tenderholt** [comment]
@berquist If you're interested in testing bash scripts, check out BATS: https://github.com/sstephenson/bats. I've used it a little bit.

**Comment by berquist** [comment]
@oliver-s-lee Would you consider helping write a test for this? The feature works fine I think, except for #1268.

**Comment by oliver-s-lee** [comment]
Sure can do, although I think we already have a test for this (for the backend machinery anyway) in the IO tests.

**Comment by oliver-s-lee** [comment]
Added in #1370
