### ISSUE TITLE
Backwards compatibility with python2.6

### ISSUE THREAD

**Issue by felixplasser** [cclib/cclib#274]
Hi, as discussed on the mailing list, I am posting an "Issue" for the backwards compatibility with python2.6. I guess this is not so critical since users can update their python version. But I am posting it for completeness.

Here I am using Version 1.3.1 but it also happens with the current branch from github

What I am doing is

~~~~
python2.6 setup.py build
export PYTHONPATH=/user/plasserf/programs/cclib/cclib-1.3.1/build/lib
./build/scripts-2.6/ccget
~~~~

and the output is

~~~~
  File "/user/plasserf/programs/cclib/cclib-1.3.1/build/lib/cclib/parser/__init__.py", line 27, in <module>
    from .molproparser import Molpro
  File "/user/plasserf/programs/cclib/cclib-1.3.1/build/lib/cclib/parser/molproparser.py", line 417
    while line.strip() and (not "ORBITALS" in line) and (not set(line.strip()) == {'*'}):
~~~~

This happens because python2.6 does not know the notation {...} for a set.

There is one more command in molproparser that python2.6 does not understand: itertools.combinations_with_replacement

And some things in qchemparser are also not compatible with python2.6

**Comment by langner** [comment]
I didn't realize it was several things. It's not worth adding a custom implementation of combinations_with_replacement and whatever else is needed in orderto support an old Python version.

Closing - will not fix. Suggestion in this case is to upgrade Python.

**Comment by berquist** [comment]
@felixplasser, can you mention what the problems with the Q-Chem parser are? If they're something trivial, like `{}` instead of `set()`, then those can definitely be fixed.

**Comment by felixplasser** [comment]
In qchemparser the error is also something about sets, in line 1312: 
~~~~
element_counters = {element: itertools.count(start=1) for element in set(self.atomelements)}
~~~~

with the error message

~~~~
  File "/user/plasserf/programs/cclib/GIT-standalone/build/lib/cclib/parser/__init__.py", line 32, in <module>
    from .qchemparser import QChem
  File "/user/plasserf/programs/cclib/GIT-standalone/build/lib/cclib/parser/qchemparser.py", line 1312
    for element in set(self.atomelements)}
~~~~

**Comment by berquist** [comment]
I installed 2.6.9 to check this, and I can't even begin to run the test suite, so it probably isn't worthwhile to change even a few lines.
