### ISSUE TITLE
Help writing a regression test

### ISSUE THREAD

**Issue by rcrehuet** [cclib/cclib#278]
I've written a parser for BOMD in Gaussian. I've checked the code works with my test file, but before doing a pull request I'l like to write a regression test and I would need some advice on how to do that. 
Thanks in advance,
Ramon

**Comment by langner** [comment]
The regression tests, due to typically larger size, are in
cclib/cclib-data. Start by uploading your file there and the rest is
boilerplate.

**Comment by langner** [comment]
@rcrehuet: Do you still need help?

**Comment by rcrehuet** [comment]
I've written a regression test. But  `from cclib.parser import DALTON` fails because there is not a DALTON module.
This is my pull request for the parser in cclib:
https://github.com/cclib/cclib/pull/283
And this for the cclib-data regression test:
https://github.com/cclib/cclib-data/pull/36

**Comment by langner** [comment]
You probably need to update your local repos (both cclib and cclib-data). I think they've gone out of sync.

**Comment by langner** [comment]
@rcrehuet any luck?

**Comment by rcrehuet** [comment]
Yes. Everything is done and I did the pull request. I though the out of sync was not a problem. Should I update my repos and do another pull request?

**Comment by langner** [comment]
You don't need to create a new pull request. Just update your branch with a new commit, or change the commit that is there, and the pull request will update in GitHub automatically. It doesn't look like a sync problem, it's just that in cclib/cclib-data#36 you're deleting a test by accident.

**Comment by langner** [comment]
A question: in cclib/cclib#283 do you think it is useful to parse the rejected steps as well?

**Comment by langner** [comment]
Pushing back to 1.5

**Comment by langner** [comment]
I think everything here has been dealt with. Thanks again @rcrehuet !
