### ISSUE TITLE
Investigate behavior with streams

### ISSUE THREAD

**Issue by langner** [cclib/cclib#293]
@Schamnad has reported FileWrapper might be gobbling up the beginnings of files.

**Comment by langner** [comment]
I don't think I've personally tried using stdin with our FileWrapper, but it is something we should cover. This is a good chance to add some tests to https://github.com/cclib/cclib/blob/master/test/parser/testlogfileparser.py

**Comment by Schamnad** [comment]
exact issue I am having is:
[Here](https://github.com/Schamnad/avogadrolibs/blob/2c3811aaf07d2d70e0ce697893dd9277b60f2309/avogadro/qtplugins/scriptfileformats/formatScripts/cclib/cclibScript.py#L32) I pass sys.stdin to ccopen. When the log.parse() function is called, in different parsers (for example the gaussianparser/gamessparser) the first line passed to the extract() [method](https://github.com/cclib/cclib/blob/master/src/cclib/parser/logfileparser.py#L301) varies, but it seems to miss the data pertaining to the input file.

For example, for the gamess output file [C_bigbasis.out](https://github.com/cclib/cclib/blob/master/data/GAMESS/basicFirefly8.0/C_bigbasis.out), the first line passed to the extract method is line [#188](https://github.com/cclib/cclib/blob/master/data/GAMESS/basicFirefly8.0/C_bigbasis.out#L188) onwards whereas information required about the basis sets is on line [#146](https://github.com/cclib/cclib/blob/master/data/GAMESS/basicFirefly8.0/C_bigbasis.out#L146). This later on causes an attribute error as it tries to access the self.nbasis attribute .
The same error is reproducible with the gaussian output file albeit parsing starting at a different start point.

I have been investigating it in two directions:

1. The Filewrapper might be gobbling up the beginnings of files
2.  Avogadro passes the sys.stdin after skipping the beginning of files

Investigation into Point 1. has resulted in the following:
In my computer Python2 is being used, so the Filewrapper initialization always goes into the '[except](https://github.com/cclib/cclib/blob/master/src/cclib/parser/logfileparser.py#L91)' block but it is unable to set the [size](https://github.com/cclib/cclib/blob/master/src/cclib/parser/logfileparser.py#L93) attribute

Investigation into Point 2:
I printed the first line (basically print(sys.stdin.readline)) before passing it to ccopen, and it printed out the first line of the output file.

This can be taken as confirmation that the Filewrapper is the one that is gobbling up the initial parts.

**Comment by langner** [comment]
Looks like your on the right track!

**Comment by Schamnad** [comment]
The problem arises on this [line](https://github.com/cclib/cclib/blob/master/src/cclib/parser/logfileparser.py#L86). After some googling, I found out [that](http://www.gossamer-threads.com/lists/python/python/37709)

> sys.stdin  is more like a pipe, and not a regular file. You can't ask a pipe 
> how many bytes it contains before you read from it. Instead, you can 
> yourself count how many bytes you read from the pipe before there are no 
> more to read

The thread though is very old and I was unale to find any suitable thread/documentation dealing with the same issue. To test this theory I made the following [changes](https://github.com/Schamnad/cclib/commit/72055ad434561f725e6c0541e1c6307a36f814f4) and ran the code. The error was not thrown and everything proceeded as intended.

**Comment by langner** [comment]
Great. Could you incorporate that into master and add some tests for FileWrapper for that case? I don't think we need to specifically check for stdin, just read in everything if seek doesn't work. Maybe think about a stop condition if the size gets too big.

**Comment by langner** [comment]
I'm going to try to figure this out today/tomorrow.

**Comment by langner** [comment]
I've created a unit test that reproduces this in #306. No fix yet - will add one this evening. It's not clear what the best way to fix this is, because we have several places where we override seek and other behaviors. I think some broader work is needed to clean up this code, but in #306 I'd just like to get a quick fix in so we can proceed with Avogadro integration.

**Comment by langner** [comment]
The fix seemed to work. Further work on io in #309.
