### ISSUE TITLE
Error in parsing GAMESS file

### ISSUE THREAD

**Issue by felixplasser** [cclib/cclib#303]
Hi, I had an error in parsing the attached GAMESS output file [FaFa.txt](https://github.com/cclib/cclib/files/406725/FaFa.txt), see also [this thread](https://sourceforge.net/p/theodore-qc/discussion/bugs_questions/thread/d9df5550/).

Even though there are 64 MOs, cclib only parses 52 "moenergies".

The problem is the line 887 in gamessparser.py

~~~~
for base in range(0, self.nmo, 5):
~~~~

This has to be changed to

~~~~
for base in range(0, self.nmo, 4):
~~~~

Since there are only 4 columns with MOs. With this fix it works for me.

**Comment by langner** [comment]
Thanks Felix for the report. Will you be sending a patch or should I run with this?

**Comment by felixplasser** [comment]
Thanks for your reply!

Sorry, I just learned that this output was produced with a locally modified version of GAMESS.
https://sourceforge.net/p/theodore-qc/discussion/bugs_questions/thread/d9df5550/#968b/fbb0/7c00/2207
There is no problem with the official GAMESS release and this ticket can be closed.

**Comment by langner** [comment]
Thanks for following up on this.
