### ISSUE TITLE
Towards v1.5

### ISSUE THREAD

**Issue by langner** [cclib/cclib#314]
I created a branch for v1.5:
https://github.com/cclib/cclib/tree/release-1.5

I'll do maintenance changes on that branch and then merge them into master after release. After #294 that seems safer than just using tags, to make sure we don't modify the release state down the road.

I'm going to make the release on Sunday as planned, so I'll go through the remaining issues and push back anything that won't get done _now_ to v1.5.1.

Feel free to comment here about the process or anything urgent we need to do before the Sunday release.

**Comment by langner** [comment]
There are now a handful of issues and PRs left in the v1.5 milestone, and those are the only ones I want to consider for the release.

**Comment by berquist** [comment]
Is there anything left that I should focus on?

**Comment by langner** [comment]
I don't think so. I'll come back to the remaining issues this evening and hopefully get the release out. I can't upload files to Zenodo for some reason, but assume that's transient.

I think we can start working towards 1.5.1 now... feel free to merge with master, I'm keeping the 1.5 stuff on a separate branch.

**Comment by langner** [comment]
Will go over things one more time today and then I'll create the release.

**Comment by langner** [comment]
I created the release on GitHub - will merge the release branch into master in a moment.

**Comment by langner** [comment]
Create new Zenodo DOI: http://dx.doi.org/10.5281/zenodo.60670

**Comment by langner** [comment]
Here's the mailing list announcement: https://sourceforge.net/p/cclib/mailman/message/35297189/

I think that concludes the release tasks. Thanks everyone!

**Comment by langner** [comment]
FTR, I updated pypi as well: https://pypi.python.org/pypi/cclib?
