### ISSUE TITLE
Add tests for CJSON reader/writer

### ISSUE THREAD

**Issue by langner** [cclib/cclib#316]

**Comment by Schamnad** [comment]
Created the PR for CJSON writer tests here : https://github.com/cclib/cclib/pull/326

**Comment by Schamnad** [comment]
CJSON reader test Suite : https://github.com/cclib/cclib/pull/329

**Comment by Schamnad** [comment]
Both Pull requests have been merged. Should there be any more testing required?

**Comment by langner** [comment]
I think more tests are definitely possible, but these have been good contributions. Thanks!
