### ISSUE TITLE
Get more test logfiles for Psi3

### ISSUE THREAD

**Issue by langner** [cclib/cclib#319]

**Comment by berquist** [comment]
Is this important? I (and definitely the Psi developers) would argue that Psi 3 is obsolete.

**Comment by langner** [comment]
Yes, if it is truly obsolete now we should move Psi3 files over to the regressions. We never did have good coverage for Psi3. I think when we added Psi, Psi4 was just in its infancy.

**Comment by langner** [comment]
Hmm, I will close this for v1.5.3 since we're not going to be extending the Psi3 part of the Psi parser. Should we be thinking about deprecating Psi3 entirely, or maybe moving it to a "mini" psi3 parser so as not to complicate the core psi parser?

@berquist you may have more context here

**Comment by berquist** [comment]
I am not sure anyone would use Psi3, but then again I wonder about how many people are using GAMESS-UK, Jaguar, etc. Since that is the case, and it doesn't cost much to those around, I think we can split the Psi parser into 3 and 4 and trim a lot from each.

**Comment by langner** [comment]
Sounds good, created #494 for that.
