### ISSUE TITLE
can't import ccopen

### ISSUE THREAD

**Issue by ahmadubuntu** [cclib/cclib#337]
Dear developer

When I want to import ccopen from parser I get error:

$ python3
>>> from cclib.parser import ccopen
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'ccopen'

while I can import other module from parser.

my system:
Ubuntu 16.04.1
Linux 4.4.0-36-generic
cclib 1.3.1-1

**Comment by berquist** [comment]
Try this:

```
from cclib.io import ccopen
```

**Comment by ahmadubuntu** [comment]
Thanks berquist

**Comment by langner** [comment]
Something we should add in cclib/cclib.github.io#6
