### ISSUE TITLE
Bugs in documentation

### ISSUE THREAD

**Issue by sandeepkrjha** [cclib/cclib#348]
There is no `regression.py` in `test` directory. `run_regressions.py` should be written in place of that in the [tutorial page](http://cclib.github.io/tutorial.html#what-next)

Also `regression.py` on [development docs](http://cclib.github.io/development.html#regression-tests) is redirecting to an [error](https://github.com/cclib/cclib/blob/master/test/regression.py) page. This link needs to be fixed.

I will try to fix this in a PR very soon.

**Comment by langner** [comment]
Thanks!
