### ISSUE TITLE
Psi4 parser in python 3.5 not parsing mpenergies 

### ISSUE THREAD

**Issue by ChayaSt** [cclib/cclib#357]
I was trying to parse a Psi4 log file of an MP2 geometry optimization. I had no problem in python 2.7 and 3.4. However, when I use Psi4 in python 3.5, the mpenergies attributes (and optdone, optstatus) don't exist. 

[Here's](https://github.com/ChayaSt/torsionfit/blob/qm/torsionfit/tests/reference/MP2_torsion_scan/0/butane_0.out2) the log file I was using.

**Comment by berquist** [comment]
I will investigate the version dependence. Does this look correct?

```
[eric@copper]$ ccget --list butane_0.out
Attempting to read butane_0.out
cclib can parse the following attributes from butane_0.out:
  atomcoords
  atommasses
  atomnos
  charge
  coreelectrons
  geotargets
  geovalues
  homos
  metadata
  moenergies
  mosyms
  mpenergies
  mult
  natom
  nbasis
  nmo
  optdone
  optstatus
  scfenergies
  scftargets
  scfvalues
/home/eric/development/cclib_berquist on master! (env: cclib_berquist 3.6.0)
[eric@copper]$ ccget mpenergies butane_0.out
Attempting to read butane_0.out
mpenergies:
[[-4294.45876623]
 [-4294.73533664]
 [-4294.84729512]
 [-4294.88832055]
 [-4294.90272988]
 [-4294.90383422]
 [-4294.90389647]]
```

**Comment by berquist** [comment]
I get the same result with Python 3.5.3 as I do with 2.7.13 and 3.6.0, so the problem might be the cclib version. Can you try running this from a Python interpreter?

```python
>>> import cclib
>>> cclib.__version__
'1.5'
```

Looking at the commit history tells me that there were quite a few fixes for Psi4 after the cclib 1.4 release, so if you aren't up-to-date, that might be the problem.

**Comment by ChayaSt** [comment]
Thanks @berquist! This was the issue. It's working now.

**Comment by berquist** [comment]
Great; if you have any further problems, just make more issues. The flexibility of Psi4 makes it hard to cover all possible use cases but the more people who are vocal about things breaking, the better.

@langner, what labels should this have now that we know there isn't a bug?

**Comment by langner** [comment]
dunno, question?

but yea, the more reports the better!
