### ISSUE TITLE
NameError in volume.py

### ISSUE THREAD

**Issue by gaursagar** [cclib/cclib#364]
Function `makepyquante` is defined under `bridge.cclib2pyquante`.
Running the program was throwing a NameError. 

Its a small fix, and I have requested a PR  https://github.com/cclib/cclib/pull/363.

**Comment by langner** [comment]
Will review for v1.5.3.

**Comment by berquist** [comment]
This might be fixed by https://github.com/cclib/cclib/pull/485.

**Comment by langner** [comment]
Confirmed the moved volume test works in `master`.
