### ISSUE TITLE
Documentation is missing API examples

### ISSUE THREAD

**Issue by baoilleach** [cclib/cclib#368]
What is documented at http://cclib.github.io/ is well documented. However...
1. It is missing any examples of use, e.g. opening a file and printing an attribute value. As far as I can remember, this was in the original wiki and so might just have been misplaced.
2. What is titled as the "Tutorial" is actually "Installation instructions".

**Comment by jeiros** [comment]
Yes, I came to the repo to find something about this. I am completely new to the package and I don't even know where or how to begin parsing files from Psi4.

**Comment by gaursagar** [comment]
@jeiros, a brief tutorial on getting started.

- Using `ccget` from command line to get a list of parseable attributes from a Psi4 output file `C_bigbasis.out`:

    ```$ ccget -l C_bigbasis.out```
- Parsing `scfvalues` and `nmo` attributes:

    ```$ ccget scfvalues nmo C_bigbasis.out```
- Using python interpreter to do the same
```python
>>> import cclib
>>> output = cclib.parser.Psi('C_bigbasis.out').parse()
# All the parsed data is now availabe in the output object
>>> output.nmo
80
>>> output.scfvalues
[array([[ -3.26250000e+01,   1.34669000e-01],
       [ -2.03968000e+00,   3.34052000e-02],
       [ -2.66475000e+00,   2.11570000e-02],
       [ -2.34458000e-01,   6.95570000e-03],
       [ -3.98417000e-02,   8.77964000e-04],
       [ -7.86602000e-04,   2.51547000e-04],
       [ -6.18476000e-05,   2.68647000e-05],
       [ -6.97285000e-07,   9.13684000e-07]])]
```

**Comment by jeiros** [comment]
@gaursagar thanks! that's enough to get going. It's simple, but a small example in the website would help :)

Also, I'm getting the following warning:
```python
output = cclib.parser.Psi('./opt.out').parse()
```
```
[Psi ./opt.out WARNING] In logfileparser.py, line 471, line not all dashes as expected: --------------------------------------------------------------------------------------------- ~
```

But I guess it's fine since I can access the attributes fine. Thanks again!

**Comment by berquist** [comment]
Historically, I used to do

```python
>>> from cclib.parsers import ccopen
>>> job = ccopen('./opt.out')
>>> data = job.parse()
>>> data.nmo
...
```

but the preference is now

```python
In [1]: from cclib.io import ccread

In [2]: data = ccread('Ala16.out')

In [3]: data.nmo
Out[3]: 1544
```

@jeiros Yes, that warning is fine. It may be something I introduced...

I think that if you run into any trouble, post about it here, because it's worthwhile to put problems into a tutorial as potential pitfalls. More specifically, some features might not be implemented for Psi4 since the program is so flexible.

**Comment by langner** [comment]
Thanks Juan, please keep the complaints coming :) we need to do a better job with the docs. I'll try to put some time into that. Perhaps moving the text of the docs to the main repo would help to remember to keep them up to date.

**Comment by baoilleach** [comment]
Or scehdule a documentation sprint for a week. Helps to focus.

**Comment by langner** [comment]
Will review what still needs to be done before v1.5.3 is out. I'll break up the tasks into smaller issues so it's easier to make progress.

**Comment by langner** [comment]
A little bit was added, further work can continue in cclib/cclib.github.io#6.
