### ISSUE TITLE
"from cclib.parser import ccopen" no longer works

### ISSUE THREAD

**Issue by baoilleach** [cclib/cclib#369]
The ccopen function has been moved to the "io" module. This function is used by GaussSum, for example. I'm guessing that it's also the go-to function for most users. I think this is a key API function, and that this change should be accompanied by an API bump.

I can perhaps use "try except" to support the old and new APIs.

**Comment by langner** [comment]
On the other hand, we never explicitly stated which names are part of the public API, did we? I propose we start to do so now, and create aliases in the parent namespace (just "cclib") so that we retain the flexibility of moving code around in the future.

Since the move of `ccopen` already happened with a minor release, we can't really go back in time to mend that.

#366 creates the alias for `cclib.ccopen`.

**Comment by baoilleach** [comment]
Sorry - I didn't realise this was already in the release.

There were already aliases in cclib.parser.__init__.py for ccopen for a similar reason. They should be removed if it is not intended that users access them in that way. It's going to break a lot of user's code though.

**Comment by langner** [comment]
Well.. we can still restore the alias cclib.parser.ccopen - did that in #366. Please take a look. I ultimately do agree that it's better to remain backwards compatible.

@baoilleach Could you make sure that's sufficient to work again with Gausssum?

**Comment by baoilleach** [comment]
Will do today.

**Comment by baoilleach** [comment]
That part works, but the absolute import fails, "from cclib.method import Electrons".

<pre>
Traceback (most recent call last):
  File "src\GaussSum.py", line 18, in <module>

  File "C:\Tools\GaussSum\src\gausssum\gausssumgui.py", line 26, in <module>
    from gausssum.cclib.parser import ADF, GAMESS, Gaussian, ccopen
  File "C:\Tools\GaussSum\src\gausssum\cclib\parser\__init__.py", line 17, in <m
odule>
    from .adfparser import ADF
  File "C:\Tools\GaussSum\src\gausssum\cclib\parser\adfparser.py", line 17, in <
module>
    from . import logfileparser
  File "C:\Tools\GaussSum\src\gausssum\cclib\parser\logfileparser.py", line 24,
in <module>
    from .data import ccData
  File "C:\Tools\GaussSum\src\gausssum\cclib\parser\data.py", line 14, in <modul
e>
    from cclib.method import Electrons
ImportError: No module named 'cclib'
</pre>

Hmmm...maybe I should change the code at my end, so that it works anyway (I just need to move the cclib folder up a directory in my source, I think). At the same time, I do feel that within the library, cclib should only use relative imports - I filed a bug separately on this. Presumably this is a common issue and someone already has a clear guidance on this.

More to the point is that the Electrons method is not required to parse the file, and is only necessary to implement the nelectrons() method. In my mind, the parsed data should be considered an immutable container class that doesn't provide any methods (beyond those absolutely necessary). This is to ensure a clean separation of the different modules of the toolkit, i.e. the parsers fill in the data object, the various calculation methods take the data object, and the two should have no dependencies between them.

You could have a facade class, for example, Calculator, that takes a data object at initalisation and provides the methods. Or just have the methods to accept the data object.

Obviously I don't do any development these days, and so it's easy for me to suggest all sorts of changes from the back seat. :-)

**Comment by baoilleach** [comment]
Yes - moving the code up a directory now works, so immediate problem solved. Thanks!

**Comment by langner** [comment]
Thanks Noel for raising these issues. I'll deal with the relative imports in the separate issue (and you are write about it).
