### ISSUE TITLE
ORCA: no etsyms from TDDFT calculation

### ISSUE THREAD

**Issue by berquist** [cclib/cclib#373]
```
  File "/usr/lib/python3.6/site-packages/cclib/parser/orcaparser.py", line 602, in extract
    for x in self.etsyms:
AttributeError: 'ORCA' object has no attribute 'etsyms'
```

Input:

```
! rks pbe def2-svp

%tddft
 nroots 24
 tda false
 end

* xyzfile 0 1 1-ttt_opt.xyz *
```

**Comment by berquist** [comment]
It appears there are several printing differences, both in headers and content, when doing RPA (full TDDFT) compared to TDA.

**Comment by berquist** [comment]
This was 2 separate issues:

1. headers are different for RPA and TDA
2. v4.0.0 doesn't print excitation coefficients, but v3.0.3 does.

Going to reopen this so I can change the empty string to nan in another PR.

**Comment by langner** [comment]
So not are we all done with this?

**Comment by berquist** [comment]
Yes, all done. Let me know if there's anything else that needs to be done this weekend.
