### ISSUE TITLE
Version in 1.5.1 still says 1.5

### ISSUE THREAD

**Issue by richardjgowers** [cclib/cclib#413]
From the 1.5.1 release on Pypi:
```python
import cclib

cclib.__version__
'1.5'
```

**Comment by langner** [comment]
Thanks for pointing his ou! I fixed the release on github (https://github.com/cclib/cclib/releases/tag/v1.5.1) with 10ab1da. But I'm not going to update PyPI since I would actually need to make a new version for that which doesn't make much sense IMO.
