### ISSUE TITLE
Parsing multiple files after each other for polarizability could be ambiguous

### ISSUE THREAD

**Issue by xymaxim** [cclib/cclib#420]
Parsing a DALTON output file which doesn't contain all polarizability components (`**RESPONSE .DIPLNX/Y/Z` keyword) just before another one with `.DIPLEN` keyword results in the output containing ambiguous numbers.

**How to reproduce this?**

See a [Gist](https://gist.github.com/xymaxim/b0a78e9fa2e545b8163f07ef6f60a21f) I've prepared to illustrate the issue. The first output file contains `.DIPLNX` keyword in the input—in this case *A* and *B* operators are set only to the *x* dipole operator. 

```python
    from cclib.parser import DALTON

    print(DALTON('Trp_polar_response_diplnx.out').parse().polarizabilities)
    print(DALTON('Trp_polar_response.out').parse().polarizabilities)
    print(DALTON('Trp_polar_response_diplnx.out').parse().polarizabilities)
```

And what went wrong? Notice that the last parsing output contains meaningful numbers from the previous file. Surprisingly. The source of that is the line below:

https://github.com/cclib/cclib/blob/73aeee78ad2a45963928747eb7b3723b17366d34/src/cclib/parser/daltonparser.py#L1102

NumPy's reference [warns](https://docs.scipy.org/doc/numpy/reference/generated/numpy.empty.html) users about using `empty()` with caution. Look at the example:

```python
    >>> a = np.empty(2); a[0] = 3.14
    >>> print(a)
    array([  3.14000000e+000,   9.65124433e-317])
    >>> print(np.empty(2))
    array([  3.14000000e+000,   9.65124433e-317])
```

**Real-life example**
Imagine that someone (inattentive or not) wants to find the trace of a tensor and calculate isotropic polarizability value for a bunch of output files. With the mentioned cuckoo-like behavior from `cclib` it could be potentially a ticking time bomb. 

**Nested issue and solution**
Actually this issue is not about how we parse the output nor shamelessly modifying the user data (it's not so). While parsing a single file with `.DIPLNX/Y/Z` run, the diagonal components of polarizability mixed up with meaningless off-diagonal numbers and that's fine (for attentive users).

Probably the better idea is to fill an empty array with `NaN` values: `a = np.empty(shape) * np.nan`. Should I create a pull request that can be used as a patch? However, some of other parsers can also be affected by this issue.

**Comment by berquist** [comment]
The junk in the 1st array isn't surprising. I do find it surprising that the memory is being reused for the 3rd array. It might be a side effect of Python namespacing, but it isn't worth investigating because the fix is simple, as you say.

Our solution is to always use `np.nan` for missing values, and that would be the solution here for the time being. I would welcome a patch and I'll scan the code for `empty` usage.

The real long-term solution is to also parse and store linear/quadratic/cubic/etc. terms properly, by name.

**Comment by langner** [comment]
@xymaxim Thanks for bringing this to our attention. Are you planning to send a fix for this as well?

**Comment by xymaxim** [comment]
I've created a pull request #421 with a small change that fixes the original DALTON issue with the inclusion of polarizabilities values from another previously parsed output file. According to the manual, ADF also has ability to limit the tensor components and tomorrow I can inspect the output files for this type of issue.
