### ISSUE TITLE
Problem with ADF TDDFT output

### ISSUE THREAD

**Issue by berquist** [cclib/cclib#430]
Before it gets lost, Felix sent us an email on 2017-03-13:

> Dear cclib team,

> I wanted to forward you an ADF output file from a TheoDORE user. It
seems that this file is not properly parsed by cclib. Using the newest
cclib version from github and python3:

> `ccget etoscs 166-tddft-0.31-new.out`

```
Attempting to read 166-tddft-0.31-new.out
Traceback (most recent call last):
   File
"/user/plasserf/programs/cclib/GIT-standalone/src/scripts/ccget", line
180, in <module>
     ccget()
   File
"/user/plasserf/programs/cclib/GIT-standalone/src/scripts/ccget", line
153, in ccget
     data = ccread(filename, **kwargs)
   File
"/user/plasserf/programs/cclib/GIT-standalone/build/lib/cclib/parser/ccio.py",
line 107, in ccread
     return log.parse()
   File
"/user/plasserf/programs/cclib/GIT-standalone/build/lib/cclib/parser/logfileparser.py",
line 309, in parse
     self.extract(inputfile, line)
   File
"/user/plasserf/programs/cclib/GIT-standalone/build/lib/cclib/parser/adfparser.py",
line 141, in extract
     line = inputfile.next()
   File
"/user/plasserf/programs/cclib/GIT-standalone/build/lib/cclib/parser/logfileparser.py",
line 101, in next
     line = next(self.src)
StopIteration
```

> I looked at the code. The problematic part seems to be in adfparser.py

```python
         # In ADF 2014.01, there are (INPUT FILE) messages, so we need to use just
         # the lines that start with 'Create' and run until the title or something
         # else we are sure is is the calculation proper. It would be good to combine
         # this with the previous block, if possible.
         if line[:6] == "Create":
             while line[:5] != "title":
                 line = inputfile.next()
```

> This loop runs until the end of the file.

I have the file, but it's too large to attach here directly (28 MB).

**Comment by langner** [comment]
Can you upload the file to cclib-data?

**Comment by mmattaNU** [comment]
Dear all,
I seem to have the same problem with my ADF output (a geometry optimization) even after the last update. 


<img width="895" alt="adf_err" src="https://user-images.githubusercontent.com/31009265/35937587-44b6cd12-0c0c-11e8-81ae-d0c9fd8e498c.png">

**Comment by berquist** [comment]
Would you be able to upload an output file that causes this?

**Comment by mmattaNU** [comment]
[ADF2017_test.out.zip](https://github.com/cclib/cclib/files/1704607/ADF2017_test.out.zip)

**Comment by berquist** [comment]
How did you install cclib? I am getting the same error from a copy I used `pip install cclib`, but it seems to work fine from the git version (`python setup.py install`):

```
[eric@copper]$ ccget --verbose --list ADF2017_test.out 
Attempting to read ADF2017_test.out
Identified logfile to be in ADF format
[ADF ADF2017_test.out WARNING] MO info up to #276 is missing
cclib can parse the following attributes from ADF2017_test.out:
  atombasis
  atomcharges
  atomcoords
  atommasses
  atomnos
  charge
  coreelectrons
  fonames
  fragnames
  frags
  geotargets
  geovalues
  homos
  metadata
  moenergies
  moments
  mosyms
  mult
  natom
  nbasis
  nmo
  optdone
  scfenergies
  scftargets
```

**Comment by mmattaNU** [comment]
@berquist indeed I had installed it with `pip` originally. Now it works.
Thanks a lot!
