### ISSUE TITLE
Successfully completed boolean

### ISSUE THREAD

**Issue by jevandezande** [cclib/cclib#435]
It would be nice to have a boolean indicating that a logfile contains a successfully completed job(s). Many programs indicate a successful job in some manner: ORCA prints out the timings `TOTAL RUN TIME: 0 days 0 hours 10 minutes 49 seconds 808 msec`, PSI4 asks for a beer `*** Psi4 exiting successfully. Buy a developer a beer!`. I presume other programs print something similar. I'm not sure what we would want to call such a variable, and I don't have much experience with other programs.

**Comment by langner** [comment]
This is a good idea. I suggest we put it in `metadata` for now. For example, `metadata['success']`.

**Comment by jevandezande** [comment]
Should this be set to `False` by default or should it not be available at all if the file terminated abnormally or is incomplete? The former is easier for the user, as they don't have to do a separate check for `success` in `metada`, but then it requires the value to be set at the beginning of `extract()`. However, no other variable seems to be set this way.

**Comment by langner** [comment]
Sounds good. I think we'd like it to be `False` when a file is abruptly cut, for example.

**Comment by langner** [comment]
This was finished.
