### ISSUE TITLE
QChem: charge being set to number of ECP-replaced electrons

### ISSUE THREAD

**Issue by theochemtheo** [cclib/cclib#438]
Hi,

Qchem provides a built in version of [libwfa](https://github.com/libwfa/libwfa), a tool for analyzing calculations, primarily excited states. When libwfa is activated (`state_analysis true` in the `$rem` block), an addition segment can be found in the output file containing the analysis. I think this extra section is causing parsing issues, since it contains some lines that are similar to those used to find excited state energies.

I have attached two example files, one without libwfa activated and one with libwfa.

[water_qchem500.txt](https://github.com/cclib/cclib/files/1317220/water_qchem500.txt)
[water_qchem500+libwfa.txt](https://github.com/cclib/cclib/files/1317221/water_qchem500.libwfa.txt)

The first one parses fine and the relevant excited state properties can be obtained. The second one does not, although ground state properties are unaffected.

Thanks,

Theo

**Comment by berquist** [comment]
Hi Theo, thanks for the bug report and especially the examples. I'm not having any trouble parsing these, and I bet it has to do with the version of cclib you're using. Can you check it? If you're using a version from a package manager like apt-get and not PyPI (`pip`) or the Git repo, it can be really out-of-date.

```
[eric@copper]$ python
Python 3.6.2 (default, Jul 20 2017, 03:52:27) 
[GCC 7.1.1 20170630] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cclib
>>> cclib.__version__
'1.5.2'
```

---

Here is the output I get from the command line script:

```
[eric@copper]$ ccget --verbose --list ~/Dropbox/research/cclib/438/*out
Attempting to read /home/eric/Dropbox/research/cclib/438/water_qchem500.libwfa.out
Identified logfile to be in QChem format
cclib can parse the following attributes from /home/eric/Dropbox/research/cclib/438/water_qchem500.libwfa.out:
  atomcoords
  atomnos
  charge
  coreelectrons
  etenergies
  etoscs
  etsecs
  etsyms
  homos
  metadata
  moenergies
  moments
  mult
  natom
  nbasis
  nmo
  scfenergies
  scftargets
  scfvalues
Attempting to read /home/eric/Dropbox/research/cclib/438/water_qchem500.out
Identified logfile to be in QChem format
cclib can parse the following attributes from /home/eric/Dropbox/research/cclib/438/water_qchem500.out:
  atomcharges
  atomcoords
  atomnos
  charge
  coreelectrons
  etenergies
  etoscs
  etsecs
  etsyms
  homos
  metadata
  moenergies
  moments
  mult
  natom
  nbasis
  nmo
  scfenergies
  scftargets
  scfvalues
```

The actual output for excited-state properties:

```
[eric@copper]$ ccget etenergies etoscs etsyms etsecs ~/Dropbox/research/cclib/438/*out
Attempting to read /home/eric/Dropbox/research/cclib/438/water_qchem500.libwfa.out
etenergies
[  84803.72333755   97029.47358174  115727.54031323]
etoscs
[ 0.00186462  0.          0.08315413]
etsyms
['Singlet', 'Singlet', 'Singlet']
etsecs
[[[(4, 0), (5, 0), 1.0]], [[(4, 0), (6, 0), 1.0]], [[(2, 0), (6, 0), -0.3168], [(3, 0), (5, 0), 0.947]]]
Attempting to read /home/eric/Dropbox/research/cclib/438/water_qchem500.out
etenergies
[  84803.72333755   97029.47358174  115727.540313  ]
etoscs
[ 0.00186462  0.          0.08315413]
etsyms
['Singlet', 'Singlet', 'Singlet']
etsecs
[[[(4, 0), (5, 0), 1.0]], [[(4, 0), (6, 0), 1.0]], [[(2, 0), (6, 0), -0.3168], [(3, 0), (5, 0), 0.947]]]
```

**Comment by theochemtheo** [comment]
Hi Eric, thanks for getting back to me. I've double checked and I am using cclib 1.5.2; however, now I can't replicate the issue myself either. This is confusing because I haven't updated anything since I tried this earlier:
```
[URANUS /home/chp13tk/Documents/PhD/NACME]86) python3
Python 3.4.5 (default, Jul 03 2016, 12:57:15) [GCC] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cclib
>>> qchemfiftywfa = cclib.io.ccread('water_qchem500+wfa.out')
>>> qchemfiftywfa.etenergies
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'NoneType' object has no attribute 'etenergies'
```
but now it works fine. Not sure what has changed. I'm even in the same shell session as before.

I have another file which *I think* really doesn't work
 
[otherfile.txt](https://github.com/cclib/cclib/files/1317835/otherfile.txt)

**Comment by berquist** [comment]
What are you trying to extract from [`otherfile`](https://github.com/cclib/cclib/files/1317835/otherfile.txt)? It terminated during the excitation part, so no `etenergies` etc., but the other parts seem ok:

```
cclib can parse the following attributes from /home/eric/Dropbox/research/cclib/438/otherfile.txt:
  atomcoords
  atomnos
  charge
  coreelectrons
  metadata
  mult
  natom
  nbasis
  nmo
  scfenergies
  scftargets
  scfvalues
```

**Comment by theochemtheo** [comment]
Oh, that's embarrassing, I was reading in the wrong file... my mistake, sorry!

I did notice a separate error whilst checking this though: the charge is reported as 60, which is the size of the ECP in this calculation.

**Comment by berquist** [comment]
Ok, that's something I'll look into. I don't ever remember implementing ECP stuff into the parser, which would explain this.

**Comment by berquist** [comment]
Note for myself: I won't be able to set `coreelectrons` properly, since Q-Chem doesn't print enough information (yet), but I can read the correct total `charge` from the multipole section.

**Comment by berquist** [comment]
I was wrong, pseudopotential data can be printed if `iprint = 100` in `$rem`. I'll have a fix soon.
