### ISSUE TITLE
ORCA CD output

### ISSUE THREAD

**Issue by adpressd** [cclib/cclib#440]
It would be great if cclib supported ORCA CD spectrum output parsing.

**Comment by berquist** [comment]
Thanks for the suggestion.

Note: `etrotats` is the column `R`/`(1e40*sgs)`. The next three columns are magnetic transition dipole moments, which aren't necessarily required.

**Comment by langner** [comment]
Is there an example output file in the repo that contains this data? If not, can one be created?

**Comment by berquist** [comment]
Yes, it's in `dvb_td`, grep for `CD SPECTRUM`.

**Comment by langner** [comment]
> Yes, it's in dvb_td, grep for CD SPECTRUM.

Excellent, so this is a matter of just writing the bit of code and testing. @berquist do you think the check should be in unit tests or regressions?

**Comment by berquist** [comment]
See `testtd.py/GaussianTDDFTTest`: `testrotatsnumber` should be moved to `GenericTDTest` and then disabled for some parsers.
