### ISSUE TITLE
Add more information to metadata

### ISSUE THREAD

**Issue by ChayaSt** [cclib/cclib#451]
Currently, the metadata parsed from psi4 output files are limited to basis_set, methods, package and package version. It will be nice if it also parses parameter used for the calculation, and if a constrained calculation was run what constraints were used and which atoms it was applied to. 

I can take a stab at adding it but because of [this](https://github.com/cclib/cclib/pull/450#issuecomment-344675414) comment on https://github.com/cclib/cclib/pull/450, I was wondering if there is any specific way this should be implemented.

**Comment by langner** [comment]
Which parameters specifically do you have in mind?

**Comment by ChayaSt** [comment]
> Which parameters specifically do you have in mind?

A) The kind of calculation preformed (energy, optimization, gradient, frequencies etc.)
B) Parameters used for the calculation (optking parameters, frequency parameters etc.)
C) If any constraints were used (cartesian, distance, dihedrals, etc.), which atoms they were applied to and what the value was.

Personally what I would like to have now are the parameters for optking and constraints used. 
Can you point me to MolSSI's metadata specs? Or is that still being decided?

**Comment by berquist** [comment]
There is a workshop that I will be attending at the end of this month, http://molssi.org/2017/10/09/molssi-workshop-quantum-mechanics-schema/, and current work is organized at https://github.com/MolSSI/QC_JSON_Schema, but there is nothing defined yet. I suspect that soon afterwards there will be an initial working definition, and Psi4 will be the first to dump a lot of this information. I'm sure all of the above information will be available, but I don't know exactly when.

For the short-term, it is probably fine to add these things. For example, here is a hypothetical snippet that describes an excited-state geometry optimization and frequency calculation.

```python
metadata['job_type'] = ['opt', 'freq']
metadata['method'] = ['hf', 'hf']
metadata['state'] = [2, 2]
metadata['tda'] = [False, False]
```

It looks like right now we have the following for metadata keys

```
package
package_version
methods
basis_set
functional
unrestricted
```

that are inconsistently implemented. `job_type` is fine to add. The most basic geometry parameters might already be available in `ccdata.geotargets`, but nothing like constraints. If you can come up with a reasonable data structure for these extra parameters and the constraints, then we can at least take a look at it.

**Comment by berquist** [comment]
Now that the workshop is over, I vote that we go ahead and just start adding stuff. Can you post an input or an output file so we can start coming up with a schema?

**Comment by langner** [comment]
Pushing this back, but are there any specific action items for us here? If not, I'm going to close it due to inactivity.

**Comment by berquist** [comment]
> are there any specific action items for us here?

No, but I think they will reveal themselves once we try to align with the QCSchema. Linking https://github.com/cclib/cclib/issues/643 so it doesn't get lost.
