### ISSUE TITLE
closed_shell() results in error for Gaussian files

### ISSUE THREAD

**Issue by jaimergp** [cclib/cclib#452]
```
import cclib as cc
p = cc.parser.Gaussian("Au1_ts3.ok.qfi").parse()
p.closed_shell
```
First, line 385 in cclib.parser.data has a typo that results in AttributeError. It should be `orbitals.Orbitals`, but now it is

```
return orbitals.orbitals(self).closed_shell()
```

After fixing that, it fails because data contains no attribute named `mocoeffs`. I guess because my file does not contain information for that. Anyway, it should be fail gracefully with a nice error message, right?

```
$CONDA_ENV/lib/python3.6/site-packages/cclib/method/orbitals.py in closed_shell(self)
     43         # If there are beta orbitals, we can assume the system is closed
     44         # shell if the orbital energies are identical within numerical accuracy.
---> 45         if len(self.data.mocoeffs) == 2:
     46             precision = 10e-6
     47             return numpy.allclose(*self.data.moenergies, atol=precision)
```

**Comment by berquist** [comment]
Hi Jaime,

Sorry for the late response. Could you post an output file that triggers this behavior?

**Comment by jaimergp** [comment]
Hi! Yes, of course. This is the (zipped) file I used.


[Au1_ts3.zip](https://github.com/cclib/cclib/files/1552353/Au1_ts3.zip)

**Comment by kunalsharma05** [comment]
I would like to work on this issue. A simple try except would be able to check if data has attribute "mocoeffs" or not. 
@langner What should be the message that should be shown if there is an Attribute error?

**Comment by ATenderholt** [comment]
I don't think it should be handled via try-except. Better to validate required attributes in the `Orbitals` constructor. As far as messages, perhaps look at some other examples (e.g. WFX writer).

**Comment by langner** [comment]
@kunalsharma05 I agree with @ATenderholt, it would be much better to handle this sort of thing generically. So in this case, that would mean in the initializer of the base class (`Method.__init__`) - it's defined in `calculationmethod.py`.

The WFX writer logic Adam was referring to: https://github.com/cclib/cclib/blob/master/src/cclib/io/wfxwriter.py#L93

**Comment by kunalsharma05** [comment]
@langner @ATenderholt So basically we want to have a list of required attributes for each sub class (e.g `Orbitals(Method)`) and place a check in the initializer of the base class (`Method.__init__`) that whether the parsed data has the required attributes or not. 
If the required attributes are not satisfied then we do not create an object for that class.

**Comment by langner** [comment]
> @langner @ATenderholt So basically we want to have a list of required attributes for each sub class (e.g Orbitals(Method)) and place a check in the initializer of the base class (Method.__init__) that whether the parsed data has the required attributes or not.
> If the required attributes are not satisfied then we do not create an object for that class.

Yes, that's the idea!

**Comment by kunalsharma05** [comment]
@ATenderholt Can we close this issue? Also, should I send another PR with the required attributes functionality extended to all other child classes as well?

**Comment by ATenderholt** [comment]
I forgot to close this issue. And yes, we would appreciate another PR with required attributes used by other method subclasses.
