### ISSUE TITLE
Possible problems with ORCA files

### ISSUE THREAD

**Issue by ATenderholt** [cclib/cclib#453]
As reported by Martin Rahm on cclib-users:

> N2 with ORCA runs OK, but results in the following warnings (not seen in some other orca output):
> `[ORCA ['./X-analysis_pyt3.py', 'N2.out'] WARNING] The geotargets attribute should not exist yet. There is a problem in the parser.`
> `[ORCA ['./X-analysis_pyt3.py', 'N2.out'] WARNING] The geotargets attribute should not exist yet. There is a problem in the parser.`
> `[ORCA ['./X-analysis_pyt3.py', 'N2.out'] WARNING] Modes corresponding to rotations/translations may be non-zero.`
> 
> NCNO2 with ORCA runs OK, but results in the following warnings (not seen in some other orca output):
> `[ORCA ['./X-analysis_pyt3_v2.py', 'NCNO2-12.out'] WARNING] Attribute atomnos changed value ([7, 6, 6, 8, 8] -> [7, 6, 7, 8, 8])`
> `[ORCA ['./X-analysis_pyt3_v2.py', 'NCNO2-12.out'] WARNING] The geotargets attribute should not exist yet. There is a problem in the parser.`

Relavant files:

[N2-ORCA.out.txt](https://github.com/cclib/cclib/files/1514193/N2-ORCA.out.txt)
[NCNO2-ORCA.out.txt](https://github.com/cclib/cclib/files/1514194/NCNO2-ORCA.out.txt)
[X-analysis_pyt3_v2.py.txt](https://github.com/cclib/cclib/files/1514195/X-analysis_pyt3_v2.py.txt)

**Comment by langner** [comment]
I understand the attached files are meant to be regressions?

**Comment by ATenderholt** [comment]
Yes, regressions assuming a problem is actually identified.

**Comment by berquist** [comment]
I'm not sure there's a bug.

For `N2-ORCA.out`, there are 4 calculations,

1. fails before echoing the input,
2. opt that converges SCF but doesn't take a Cartesian step,
3. opt,
4. opt + freq.

For `NCNO2-ORCA.out`, there are 3 calculations,

1. opt + freq that fails before SCF,
2. opt + freq with different `atomnos` that causes the `Attribute atomnos changed value`,
3. opt + freq that's identical.

For both files, `The geotargets attribute should not exist yet.` is coming from the concatenation of multiple outputs. Using `N2` as an example, when you break it apart:

```
Attempting to read N2_1.out
Identified logfile to be in ORCA format
cclib can parse the following attributes from N2_1.out:
  metadata
Attempting to read N2_2.out
Identified logfile to be in ORCA format
cclib can parse the following attributes from N2_2.out:
  atomcharges
  atomcoords
  atommasses
  atomnos
  charge
  coreelectrons
  geotargets
  homos
  metadata
  moenergies
  mult
  natom
  nbasis
  nmo
  scfenergies
  scftargets
  scfvalues
Attempting to read N2_3.out
Identified logfile to be in ORCA format
cclib can parse the following attributes from N2_3.out:
  atomcharges
  atomcoords
  atommasses
  atomnos
  charge
  coreelectrons
  geotargets
  geovalues
  homos
  metadata
  moenergies
  moments
  mult
  natom
  nbasis
  nmo
  optdone
  scfenergies
  scftargets
  scfvalues
Attempting to read N2_4.out
Identified logfile to be in ORCA format
[ORCA N2_4.out WARNING] Modes corresponding to rotations/translations may be non-zero.
cclib can parse the following attributes from N2_4.out:
  atomcharges
  atomcoords
  atommasses
  atomnos
  charge
  coreelectrons
  enthalpy
  entropy
  freeenergy
  geotargets
  geovalues
  homos
  metadata
  moenergies
  moments
  mult
  natom
  nbasis
  nmo
  optdone
  pressure
  scfenergies
  scftargets
  scfvalues
  temperature
  vibdisps
  vibfreqs
  vibirs

```

and the attributes work as expected:

``` python
from cclib.io import ccread

N2_0 = ccread('N2-ORCA.out')
N2_2 = ccread('N2_2.out')
N2_3 = ccread('N2_3.out')
N2_4 = ccread('N2_4.out')

assert N2_0.atomcoords.shape == (11, 2, 3)
assert N2_2.atomcoords.shape == (1, 2, 3)
assert N2_3.atomcoords.shape == (5, 2, 3)
assert N2_4.atomcoords.shape == (5, 2, 3)

assert N2_0.scfenergies.shape == (11, )
assert N2_2.scfenergies.shape == (1, )
assert N2_3.scfenergies.shape == (5, )
assert N2_4.scfenergies.shape == (5, )

assert hasattr(N2_0, 'vibfreqs')
assert not hasattr(N2_2, 'vibfreqs')
assert not hasattr(N2_3, 'vibfreqs')
assert hasattr(N2_4, 'vibfreqs')
```

**Comment by ATenderholt** [comment]
Thanks for investigating. I'll let Martin know.
