### ISSUE TITLE
Recommended way to install for development?

### ISSUE THREAD

**Issue by berquist** [cclib/cclib#459]
Apparently I have no idea how to install cclib while I'm developing anymore, because `python setup.py install` is simply not updating changed files in my virtualenvs.

Maybe @mcocdawc can chime in, since he helped rewrite `setup.py`.

**Comment by langner** [comment]
Maybe it's a matter of existing files? Have you tried adding `-f`?

**Comment by mcocdawc** [comment]
First thing is, that I would use ``pip install .``.
Or in your case even better ``pip install -e .`` which is roughly equivalent to ``python setup.py install --develop``. (The e stands for editable).
Supporting pip was the main point of my changes.
Nevertheless it should still work with ``python setup.py``. I try to reproduce on my computer.

There are probably better sources for ``pip vs. python setup.py``, but here are some:
[SO question 1](https://stackoverflow.com/questions/45426794/setup-in-virtualenv-pip-install-e-vs-python-setup-py-install)
[SO question 2](https://www.davidfischer.name/2010/04/why-you-should-be-using-pip-and-virtualenv/)

**Comment by mcocdawc** [comment]
Apparently I cannot reproduce the problem. Note that I am using conda for managing my environments.
If I am in my root environment and use ``python setup.py install``, change stuff, and redo the installation via ``python setup.py install`` the changes are visible.

Did you perhaps install cclib somewhere else with higher precedence in your PYTHONPATH?

**Comment by langner** [comment]
I can't reproduce either. Eric, if you remove the installed files does it work? If so, then try `-f`. Otherwise it's some configuration problem.

**Comment by berquist** [comment]
When I wiped my virtualenv things started working again, but I noticed more issues if I didn't use `-f`.

> Or in your case even better pip install -e . which is roughly equivalent to python setup.py install --develop. (The e stands for editable).

Just to make sure, this means that if I change a file in the source tree, I don't need to reinstall, because whatever is in `$VIRTUAL_ENV` works like a symlink, correct? And things should still work if I switch branches?

For some reason `pip install -e .` didn't install `numpy` in a fresh non-symlinked virtualenv.

**Comment by mcocdawc** [comment]
Yes and no.
It works like a symlink. So as long as only the content of your files is different, there is no problem. I am not exactly sure what happens if you have different directory structures across your branches. 
Also compiled extensions have to be recompiled. But in 99% of your time, where you just change Python code in existing files does not require reinstallation.

The editable installation does not automatically install dependencies. This is just from my experience. I don't know if it is a bug or documented behavior. For these cases it is probably best to type:
``` 
pip install .
pip uninstall cclib
pip install -e .
```

**Comment by berquist** [comment]
All of that makes sense. I asked not only because I wasn't sure how to do it, but we need new instructions for the next time the docs get updated.

**Comment by langner** [comment]
> All of that makes sense. I asked not only because I wasn't sure how to do it, but we need new instructions for the next time the docs get updated.

Yes... we should the docs after the recent changes.
