### ISSUE TITLE
NameError in the convertor function - utils.py 

### ISSUE THREAD

**Issue by acebri** [cclib/cclib#461]
The function Convertor in 'cclib/src/cclib/parser/utils.py' presents an error in the conversion name of  "hartree_to_kcal": lambda x: x * 627.50947414. This conversion corresponds to hartree to **kcal/mol** 
Consequently in the other way around kcal_to_hartree:lambda x: x / 627.50947414. 
The rest conversions related with kcal are also wrong. The values of the conversions are related with **kcal/mol** not with **kcal** 
 http://web.utk.edu/~rcompton/constants

**Comment by langner** [comment]
Hmm, I think we were assuming these numbers were per mole, and just did not put the "mol-1" in the keys. We should probably just fix the strings in the keys. @ATenderholt @berquist any objections?

**Comment by ATenderholt** [comment]
I think the implicit assumption is clear (i.e. Hartree for particle, kcal for mols), but it's also better to be more explicit when possible.

Are you thinking changing to `hartree_to_kcal_mol-1`? Or would `hartree_to_kcal_per_mol` be better?

**Comment by berquist** [comment]
I also think we should fix it, and my vote is for `kcal_per_mol`.

**Comment by mithlesh4257** [comment]
Can I fix this issue?

**Comment by langner** [comment]
> Can I fix this issue?

Of course, go ahead. I just haven't gotten around to it.

**Comment by berquist** [comment]
I am fine with that.

Is it appropriate for me to bring up here that I'd like to have `cm-1` be changed to `wavenumber`?

**Comment by langner** [comment]
I suppose `kcal/mol` also has the advantage of being shorter, so let's stick with that.

I'm OK with `wavenumber` as well, but let's do that in a separate PR.

**Comment by langner** [comment]
Will be fixed by #645.

**Comment by berquist** [comment]
Done.
