### ISSUE TITLE
Problem with using ccwrite on Mac OS

### ISSUE THREAD

**Issue by szl0072** [cclib/cclib#468]
`Traceback (most recent call last): File "/Users/username/anaconda3/bin/ccwrite", line 4, in <module> __import__('pkg_resources').run_script('cclib==1.5.2', 'ccwrite') File "/Users/username/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 748, in run_script self.require(requires)[0].run_script(script_name, ns) File "/Users/username/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1516, in run_script code = compile(source, script_filename, 'exec') File "/Users/username/anaconda3/lib/python3.6/site-packages/cclib-1.5.2-py3.6.egg/EGG-INFO/scripts/ccwrite", line 45 type=int, ^ SyntaxError: invalid syntax`

The above information was generated when I was trying to use the ccwrite method on my Mac OS system. I know in the document, it states about usage on various Linux systems. If this problem is mainly happening on Mac OS, I will try to use the library on Linux machines. However, I feel like it is worthy to mention here. If it is my misunderstanding of using the library, I am sorry for the inconvenience beforehand.

**Comment by ATenderholt** [comment]
This looks very similar to problem raised in #466, so I'm closing this. Please reopen if it is actually a separate problem.
