### ISSUE TITLE
Add tests for the main scripts (ccwrite, ccget)

### ISSUE THREAD

**Issue by pasenor** [cclib/cclib#472]
At the moment there is no easy way to test the main scripts (`ccget`, `ccwrite`, probably `cda`) and no tests on them, which leads to bugs (#377, #466, probably more).

There are different ways to enable testing:
- move the scripts to a module and write a test that imports their main functions and invokes them. 
- write regression tests that run scripts using shell commands and look at the output

I prefer the first approach: it is faster, more granular (we are looking for errors in script files, not in the functions they invoke); it also allows us to use mocks and thus not deal with output files.

**Comment by langner** [comment]
@pasenor Was there anything else you wanted to add for this?

**Comment by langner** [comment]
Closing this, moved last two points for consideration to #54.
