### ISSUE TITLE
Add support for g16 logfiles

### ISSUE THREAD

**Issue by arosen93** [cclib/cclib#481]
Currently, cclib has support for Gaussian03 and Gaussian09. With the release of Gaussian16, it would be ideal to add g16 functionality to cclib. I have attached two sample g16 log files. From prior conversations with @jaimergp, cclib is unable to parse the log file due to changes in how the frequency analysis is formatted. So, I thought I'd open an issue here to get a conversation started about potentially adding g16 support in the future.

[sample1.log](https://github.com/cclib/cclib/files/1831568/sample1.log)
[sample2.log](https://github.com/cclib/cclib/files/1831569/sample2.log)

**Comment by langner** [comment]
Yes, this is definitely something we want to do.

**Comment by jaimergp** [comment]
Is this considered part of the GSOC proposals?

**Comment by langner** [comment]
Not specifically, but it could be. It might fall under "adding new parsers". It shouldn't take much effort anyway. What needs to happen:
1. Someone needs to rerun our unit test jobs in the new version.
2. Add the new files to our repository.
3. Add them to our unit tests suite and fix anything that breaks
4. Move the third oldest version (g03?) to the regression suite.

**Comment by jaimergp** [comment]
I would like to help with this, but I don't have access to G16 (yet, I hope). So... once 1 and 2 are tackled, I could help with 3/4.

**Comment by arosen93** [comment]
I'd be happy to run any necessary unit tests if that would help. I'd just need to be pointed in the right direction to know what to run.

**Comment by arosen93** [comment]
Great. I'll aim to have that done for tomorrow. I don't know of any major input changes with g16 (just new additions), so it should be pretty smooth sailing. Will touch base soon.

**Comment by arosen93** [comment]
I just submitted a [pull request](https://github.com/cclib/cclib/pull/488). I had to increase the memory from 100 MB to 400 MB in some of the `dvb` jobs. Otherwise, nothing else needed to be changed.

**Comment by langner** [comment]
I think everything is done here.
