### ISSUE TITLE
Get raw CJSON dict

### ISSUE THREAD

**Issue by jaimergp** [cclib/cclib#484]
Would it be posible to obtain a raw CJSON dict out of `cclib.io.CJSON`? The current implementation can only return the dumped str with `json.dumps`, but I would like to obtain the raw Python object. Currently I have to call `json.loads` on the returned string.

I'd suggest a small refactor similar to this:

```
class CJSON(filewriter.Writer):

    [...]

    def _cjson_dict(self):
         cjson_dict = dict()
         # all the code present currently in self.generate_repr, sans the return statements
         # extracted below
         return cjson_dict

    def generate_repr(self):
        cjson_dict = self._cjson_dict()
        if self.terse:
            return json.dumps(cjson_dict, cls=NumpyAwareJSONEncoder)
        else:
            return json.dumps(cjson_dict, cls=JSONIndentEncoder, sort_keys=True, indent=4)

    [...]

```
Would that be OK? I can submit a PR if you want.

**Comment by ATenderholt** [comment]
That seems reasonable to me, although `_cjson_dict` implies a non-public API according to PEP8. I suggest something like `as_dict()` or a property (`object`?) instead.

**Comment by langner** [comment]
Agreed, would be nice to have access to the dict. Would also be nice to merge the reader and writer into one class.

**Comment by jaimergp** [comment]
Finally, I have some free time! How should we proceed with this API merge? Would it make sense to first refactor the CJSON dumper for direct access to the dict and then think about the reader/writer merge?

**Comment by berquist** [comment]
@jaimergp, do you want to work on merging readers and writers, or should we do that?

**Comment by jaimergp** [comment]
@berquist I can handle that if you want! I mean, I don't want to interfere but I am happy to help :) That said, I'd need some guidelines to see how you want to abstract the interface for more general cases.

**Comment by langner** [comment]
I think that's not strictly necessary for this particular change, namely returning the dict, but it would be great as well. Also, please use `as_dict` as Adam suggested or similar.

**Comment by berquist** [comment]
Yes, I think we would appreciate the help. My strategy was going to start with making an abstract `FileFormat` class or something similar.
