### ISSUE TITLE
Make conda-forge package

### ISSUE THREAD

**Issue by richardjgowers** [cclib/cclib#493]
Hello

I'm trying to integrate cclib into MDAnalysis, sort of what you'd call a "bridge" module MDAnalysis/mdanalysis#1618 

For this it would be really handy if cclib was available on conda-forge (https://conda-forge.org/).  Is this something you've looked at previously?  We've got some experience packaging things up for conda-forge if you'd need some help.

**Comment by langner** [comment]
Hi Richard. Two things:
1. Can you do the conda-forge packaging yourself?
2. Do we need to make any code changes for this to work?

**Comment by richardjgowers** [comment]
We shouldn't need to make any changes, the recipe can be external to the package.

We could do it all ourselves, but I did think you might like to be in charge of the release schedule, once the recipe is built making a release is [fairly simple](https://github.com/conda-forge/mdanalysis-feedstock/commit/b3fc4ee0150b3e510bae354a623b6625f6838b05#diff-e178b687b10a71a3348107ae3154e44c)

**Comment by langner** [comment]
OK, I can look into after the next release for v1.5.4. If you want it soon, feel free to take the initiative (you can probably add someone from cclib as an admin or something later on).

**Comment by berquist** [comment]
I've just installed and tested the conda-forge package. Thank you @richardjgowers and @jaimergp!

**Comment by langner** [comment]
Yay! Is there something we need to subscribe to monitor that it's up to date in the future?

**Comment by richardjgowers** [comment]
@langner a bot will update the conda-forge recipe when a new pypi release is published, so releasing on pypi as normal works!

**Comment by langner** [comment]
@richardjgowers Excellent, that's great to hear. Is this the best status page for the conda package? https://anaconda.org/omnia/cclib

**Comment by richardjgowers** [comment]
https://anaconda.org/conda-forge/cclib

Is what we made. So ‘conda install -c conda-forge cclib’ does the trick.

The thing you linked is something the omnia people did, I’m not sure if
it’s automatic etc, looks like it’s on v1.5 still
