### ISSUE TITLE
Location for scripts is too generic

### ISSUE THREAD

**Issue by dleidert** [cclib/cclib#508]
I was informed, that the installation path for the scripts (console_script) is too generic. Indeed, the scripts are in <python-path>/dist-packages/scripts/:

/usr/lib/python3/dist-packages/cclib/__init__.py
/usr/lib/python3/dist-packages/scripts
/usr/lib/python3/dist-packages/scripts/__init__.py
/usr/lib/python3/dist-packages/scripts/ccget.py
/usr/lib/python3/dist-packages/scripts/ccwrite.py
/usr/lib/python3/dist-packages/scripts/cda.py

IMO they should better be in /usr/lib/python3/dist-packages/cclib/scripts/.

**Comment by langner** [comment]
Is this installing from the github repo, or some distribution?

**Comment by dleidert** [comment]
This is the result from building the source tarball from [1] to create the Debian package [2]. The source tarball and the 1.5.3 branch in Git have a different source layout than the master branch in Git. So IMO master is not affected. But the 1.5.x branches (and sources) are.

[1] https://github.com/cclib/cclib/releases/tag/v1.5.3
[2] https://packages.debian.org/sid/amd64/python3-cclib/filelist

**Comment by langner** [comment]
I see, at first glance things changed after v1.5.3 at 8d1eac291a. Would you prefer to pick up the change in the next release or for me to cherry pick that into v1.5.3?

**Comment by langner** [comment]
Daniel, I cherry-picked the script update into a post release. I'm closing this as fixed, but let us know if the organization of files is better now for v1.5.3.
