### ISSUE TITLE
Ensure metadata contains most detailed package version

### ISSUE THREAD

**Issue by berquist** [cclib/cclib#533]
As mentioned in https://github.com/cclib/cclib/pull/515#discussion_r194088771, each parser should set `self.metadata['package_version']` to be the most specific version possible.

**Comment by berquist** [comment]
The "most specific version possible" will be within reason. For example, packages that print a value that is very clearly the version control commit number or hash (DALTON) should read that separately. Some are less clear (GAMESS-UK, Jaguar) and those can be added to the primary package version.

**Comment by berquist** [comment]
There is a line in the ORCA parser that reads
```python
# Clashes with Orca 2.6 (and presumably before) TDDFT absorption spectrum printing
elif line == 'ABSORPTION SPECTRUM' and float(self.metadata['package_version']) > 2.6:
```
which gives a better definition of what `package_version` should contain: even if it cannot be cast to a number, it should be a string with a clear ordering so comparisons can easily be performed. [Dictionary order](https://en.wikipedia.org/wiki/Lexicographical_order) is probably sufficient. This clearly requires things like Git revision hashes to be separate fields, but does not exclude things like build numbers, SVN revision numbers, or counters that start from 0 or 1.

However, I believe this should be simplified so that `float(package_version)` always works, otherwise it will be inconsistent for people modifying parser code. _All_ more specific version information that isn't like 1.2.3 should go in some other metadata.

Thoughts, @dgasmith? I don't recall the current schema spec containing these details.

**Comment by dgasmith** [comment]
I would go with something where you can use `pkg_resources`:

```
>>> v1 = pkg_resources.parse_version("0.2.2+12.g41eebf2")
>>> v2 = pkg_resources.parse_version("0.2.2")
>>> v2 > v1
False
```

**Comment by berquist** [comment]
The way I would set it up is that the parser would read the version and save it right away after calling `parse_version` on it, so that it can be used for version comparisons in `extract()` without much work:
```python
self.metadata["package_version"] = pkg_resources.parse_version(package_version)
```
and `testtypes` in https://github.com/cclib/cclib/pull/599 would be changed to check for `packaging.version.Version`:
```python
In [10]: s2 = "1.2.1"

In [11]: v2 = pkg_resources.parse_version(s2)

In [12]: type(v2)
Out[12]: packaging.version.Version
```
Is this sufficient?

**Comment by langner** [comment]
I thought the version was going to be stored as a string in `metadata`, and the parsing done just in a test. My concern would be that not all programs will necessarily give us a parsable string, and in that case we'd just modify the test, instead of mangling the string(?).

**Comment by berquist** [comment]
I'm testing it right now, and `parse_version` is willing to take any string, though there are rules about version precedence. So far I've found a version for every single program.

Version precedence is weird, because this is incorrect:
```python
In [80]: va2
Out[80]: <LegacyVersion('development version')>

In [81]: va4
Out[81]: <Version('2013.1')>

In [82]: va2 < va4
Out[82]: True
```
though in this specific case, it looks like there is extra information in the first file I forgot that would solve this.

Storing as a string in `metadata` would mean every time a version comparison is required, a call to `parse_version` needs to happen. This would need to happen anyway, because a `Version` can only be compared to another `Version`, not a string, float, or int:
```python
In [88]: v1
Out[88]: <Version('1.0')>

In [89]: v1 < '1.2'
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-89-cd94e581e4f9> in <module>()
----> 1 v1 < '1.2'

TypeError: '<' not supported between instances of 'Version' and 'str'
```
Storing as a string would make the eventual writing to JSON slightly easier.

I may have convinced myself that it should be stored as a string. What should extra version tests look like then?
