### ISSUE TITLE
Fix line ending, but not in logfiles

### ISSUE THREAD

**Issue by langner** [cclib/cclib#536]
See #371 and #531 for context.

**Comment by berquist** [comment]
Do we also want to convert every file to UTF-8? Most are ASCII.

**Comment by berquist** [comment]
Done in https://github.com/cclib/cclib/pull/1307/commits/7b2e8701dcb1a1a6c437919b185be78a35c3e2a5.  If there were a change of an entire file back from LF to CRLF our setup would not catch that, but we'll cross that bridge when we come to it.
