### ISSUE TITLE
Order of parsing files for Turbomole

### ISSUE THREAD

**Issue by berquist** [cclib/cclib#562]
From https://github.com/cclib/cclib/pull/557#issuecomment-401457492,

> ... investigate here is the issue of file order. We dictate that order for the unit tests. There might be some questions, for example:

> 1. Is that the correct "canonical" order?
> 2. What order actually make sense
> 3. Should we be testing other orders as well?
> 4. How do we communicate this to users?

**Comment by berquist** [comment]
This is just in case any other issues come up.

**Comment by kunalsharma05** [comment]
@berquist Please link this to the project. I am not able to do it, github just keeps showing me error for some reason. Also the `Molcas moenergies check` card on the project needs to be converted to an issue as well and doing that gives me error as well. https://github.com/orgs/cclib/projects/1#card-11212690

**Comment by langner** [comment]
I think the right thing to do for the questions are:
1. I don't think there is such a thing, we can parse in any order we like.
2. The order that makes most sense is that one that lets us parse everything we need.
3. We should only test one order - the one we use for parsing.
4. Ideally this should be transparent to the user. I assume the files are always called the same, so we can just determine what order we want to use and stick to that.

Any other thoughts?

**Comment by berquist** [comment]
@oliver-s-lee We talked about this a bunch but I don't remember the resolution other than it's solved.  Can you find the merged PR(s) that close this?

**Comment by oliver-s-lee** [comment]
Sure. Most recently this was addressed as part of the rewrite in #1222. Each parser can define its own preferred parsing order via the `sort_input()` classmethod.
