### ISSUE TITLE
Drop Python 3.2 and bump Travis to 3.4

### ISSUE THREAD

**Issue by berquist** [cclib/cclib#577]
I've run into problems in https://github.com/cclib/cclib/issues/455 and https://github.com/cclib/cclib/pull/568 with Python 3.2 not being supported properly. Even Ubuntu 14.04.5 LTS, released in 2014 and supported until 2019, ships 3.4.3. I propose that we switch to 3.4 as the minimum version for 3.x.

**Comment by ATenderholt** [comment]
Seems like a good idea to me.

**Comment by langner** [comment]
+1 but let's please update the carious files/docs mentioning the requirements

**Comment by berquist** [comment]
Well, now it's much easier to update the docs and the config simultaneously.

**Comment by langner** [comment]
> Well, now it's much easier to update the docs and the config simultaneously.

And kudos for that!

**Comment by langner** [comment]
Done.
