### ISSUE TITLE
Produce pandas.DataFrame out of logfiles

### ISSUE THREAD

**Issue by dudektria** [cclib/cclib#580]
Hi,

I've been using cclib for some time now and I often create a [`pandas.DataFrame`](https://pandas.pydata.org/) object out of logfiles using cclib. This makes it very easy to deal with lots of results. Besides, this might fill a gap for machine learning. Would a simple function for it be a useful addition to cclib?

I have some initial code but I'm unsure if it would fit in this project. Some attributes are perfect for fitting in a table cell (e.g., `freeenergy`), while others might need some thought (e.g. `atomcoords`).

**Comment by ATenderholt** [comment]
There might be some cases where a function like that would be useful. What does your initial code do? As you mention, it might not make sense to put something like `atomcoords` in a `DataFrame`, but others make perfect sense.

**Comment by berquist** [comment]
This is a good idea. I'm assuming that each row represents a new `ccData` instance, and each column is an attribute?

When I made dataframes from ccdata instances, which was all the time, I also struggled with the representation. My conclusion was that for complex properties like `atomcoords`, it's preferable to have each cell contain the whole result, so the column name is faithful to the original attribute name. This way `df.loc[:, 'atomcoords']` or `df.atomcoords` just works. The downside is the column type would be `object`, and I'm not sure how inefficient that is. This is still better than automatically generating column names when sticking every vibrational frequency into its own column.

**Comment by dudektria** [comment]
Right now I have the following function:

```python
def ccframe(ccobjs, *args, **kwargs):
    """Write data parsed by cclib from one or more outputfiles to a
    pandas.DataFrame.

    Inputs:
        ccobjs - An iterable of either cclib jobs (from ccopen) or data (from
        job.parse()) objects

    Returns:
        a pandas.DataFrame
    """
    outputs = []
    for ccobj in ccobjs:
        # Is ccobj an job object (unparsed), or is it a ccdata object (parsed)?
        if isinstance(ccobj, logfileparser.Logfile):
            jobfilename = ccobj.filename
            ccdata = ccobj.parse()
        elif isinstance(ccobj, data.ccData):
            jobfilename = None
            ccdata = ccobj
        else:
            raise ValueError

        outputs.append(pd.Series(ccdata.getattributes()))

    return pd.DataFrame(outputs)
```

This nicely handles incomplete information (e.g. a lacking `freeenergy` becomes `NaN`) and supports cells with array data (such as `atomcoords`), which is supported by pandas by casting to lists if necessary.

On the other hand, array data gets casted to strings if written to a csv file, for instance, which makes writing and re-reading this kind of data a little more complicated. For instance,

```python
paths = ["a.out", "b.out"]

df = ccframe([ccopen(path) for path in paths])
print(df[["freeenergy", "vibfreqs"]])

print(type(df["freeenergy"][0]))
print(type(df["vibfreqs"][0]))

df_json = pd.read_json(df.to_json())
print(type(df_json["freeenergy"][0]))
print(type(df_json["vibfreqs"][0]))

df_csv = df.to_csv("/tmp/ab.csv")
print(type(df_csv["freeenergy"][0]))
print(type(df_csv["vibfreqs"][0]))
```

gives

```
   freeenergy                                           vibfreqs
0 -553.226474  [16.3588, 69.2992, 91.6743, 112.0387, 127.9224...
1 -475.103836  [34.6873, 97.0408, 134.6723, 177.8323, 182.561...
<class 'numpy.float64'>
<class 'numpy.ndarray'>
<class 'numpy.float64'>
<class 'list'>
<class 'numpy.float64'>
<class 'str'>
```

**Comment by berquist** [comment]
If you want to have a proper CSV file, then there is no way around generating new columns. My approach was to convert `vibfreqs` into `vibfreqs_0`, `vibfreqs_1`, ..., automatically generating the correct number of columns depending on `max([len(data.vibfreqs) for data in ccdatas])`. Empty spots contain `np.nan`. For higher-dimensional data, `atomcoords[4][2][0]` would map to a column `atomcoords_4_2_0`.

Now that interoperability between tools is getting better thanks to JSON, YAML, and HDF5, we should try to move away from CSV. All the column name autogeneration I did was because I kept my data in pickled dictionaries and CSV files rather than any of the above. Converting the autogenerated column names into a workable analysis was time-consuming and error-prone.

**Comment by berquist** [comment]
I wrapped `ccframe` in a script: https://gist.github.com/berquist/610f5245ec17d8da98e38f0c97fbdf3b

**Comment by dudektria** [comment]
I agree with using pickle/HDF5 and not mapping higher-dimensional data to multiple columns.

I wrote a *very* similar script that supports writing to multiple file formats: https://github.com/dudektria/ccframe/blob/master/ccframe.py

```
% ccframe --help
usage: ccframe [-h] [-O OUTPUTDEST] [--identifier IDENTIFIER]
                  compchemlogfile [compchemlogfile ...]

positional arguments:
  compchemlogfile       one or more computational chemistry output files to
                        parse and convert

optional arguments:
  -h, --help            show this help message and exit
  -O OUTPUTDEST, --outputdest OUTPUTDEST
                        the output document to write, including an extension
                        supported by pandas (csv, hdf/hdf5, json/cjson,
                        pickle/pkl, xlsx)
  --identifier IDENTIFIER
                        name of sheet which will contain DataFrame, if writing
                        to an Excel file, or identifier for the group in
                        HDFStore, if writing a HDF file
```

Do you think it to be an interesting addition to `ccget` and `ccwrite`?

**Comment by berquist** [comment]
Yes, I do. One thing we need to be careful of is that the codebase is currently structured so the only hard dependency is on NumPy. Outside of the core, there is `cclib.bridge`, which contains interfaces to Open Babel, BioPython, and PyQuante 1, with minor mechanisms to make sure that exceptions are thrown only if a function is used. Importing the files won't fail even if the packages aren't installed. `ccframe` would require pandas, which [has extra dependencies of](https://pandas.pydata.org/pandas-docs/stable/install.html#dependencies) python-dateutil and pytz. There are two options for adding `ccframe` at the same level as the other scripts:

1. Make pandas a hard dependency, which guarantees the script works on all installs.
2. Make pandas a soft dependency. If it isn't installed, trying to run the script will give a message saying it needs to be installed.

Until more of the codebase is built on top of pandas (if at all), I vote for option 2.

I wonder where the main code should live. `bridge` is supposed to contain interfaces to other packages, but `ccframe` is valuable both in scripts and standalone. The other scripts are now in `cclib.io`, and setuptools automatically generates the entry points. This makes more sense to me.

**Comment by dudektria** [comment]
Right, I'll split the code when making the PR.

**Comment by langner** [comment]
This is a good idea. If there is substantial code/logic behind this, it can
make sense to have both a new bridge module and a script with a soft
dependency.

**Comment by langner** [comment]
BTW, the link https://github.com/dudektria/ccframe/blob/master/ccframe.py does
not work. Does this live somewhere else?

**Comment by dudektria** [comment]
Sorry, this is the right link: https://gist.github.com/dudektria/a1dea3d9352215b36a28511784115fac
This is was almost copy-pasted from PR #586.

**Comment by langner** [comment]
Was there something else to add here?

**Comment by dudektria** [comment]
No, I think this issue can be closed. Thanks for accepting this idea!
