### ISSUE TITLE
Replace parser.utils.PeriodicTable with periodictable

### ISSUE THREAD

**Issue by berquist** [cclib/cclib#604]
As discussed in https://github.com/cclib/cclib/pull/568, our built-in periodic table should be replaced with [periodictable](https://pypi.org/project/periodictable/).

Rather than rewrite everywhere that our own table is used, PeriodicTable should be modified to call periodictable, so the interface doesn't need to be changed.

**Comment by langner** [comment]
Another option that looks reasonable: https://github.com/MolSSI/QCElemental

**Comment by berquist** [comment]
It does; it could also replace our unit converter. Are you ok with its dependency on Pint?

**Comment by dudektria** [comment]
Hi, [mendeleev](https://mendeleev.readthedocs.io/en/stable/) might be also an alternative.

**Comment by pandaxtc** [comment]
Hi, I'd like to take this issue! Is that alright?

**Comment by berquist** [comment]
@pandaxtc Go right ahead! My thought is that we probably want to use QCElemental rather than `periodictable`, so the issue title is maybe misleading.

**Comment by pandaxtc** [comment]
It looks like QCElemental is only Python 3 compatible, it's listed as such on PyPi and some of its dependencies are Python 3 only. Should I use `periodictable` instead, or should this be put on hold for now?

**Comment by langner** [comment]
A good opportunity to drop Python2 support? :)

**Comment by pandaxtc** [comment]
I've gone ahead and made a pull request using `periodictable` just for now!

**Comment by berquist** [comment]
I am ok with depending on `periodictable` rather than QCElemental for now. The benefit would be that we could drop SciPy as a depedency, since QCElemental comes with the physical constants we need for the nuclear methods.

**Comment by berquist** [comment]
I've made https://github.com/cclib/cclib/issues/776 so we can track a possible move to QCElemental there.
