### ISSUE TITLE
ORCA parser doesn't store gradients

### ISSUE THREAD

**Issue by ghutchis** [cclib/cclib#607]
I'm confused. If I look at the orcaparser.py in `master` it looks like it reads `grads` but using https://github.com/cclib/cclib-data/blob/master/ORCA/ORCA4.0/CO2_freqs.out

```
% ccget --list CO2_freqs.out 
Attempting to read CO2_freqs.out
cclib can parse the following attributes from CO2_freqs.out:
  atomcharges
  atomcoords
  atommasses
  atomnos
  atomspins
  charge
  coreelectrons
  enthalpy
  entropy
  freeenergy
  geotargets
  geovalues
  homos
  metadata
  moenergies
  moments
  mult
  natom
  nbasis
  nmo
  optdone
  pressure
  scfenergies
  scftargets
  scfvalues
  temperature
  vibdisps
  vibfreqs
  vibirs
```

**Comment by ghutchis** [comment]
I've tried this on a range of other ORCA files that seem to have the data, but self.grads does not make it through.

I'd be happy to debug if someone can give me pointers (e.g., to get logging messages that the code is getting called in the parser, etc.)

**Comment by berquist** [comment]
It's being parsed fine for me. I bet the reason why is the lines that set `grads` are dated 2018-04-18 under blame (f9a5f9714), but the last release was on 2018-04-08. Can you confirm which version you're using?

**Comment by ghutchis** [comment]
I tried installing from `master` but it's possibly old. I'll check by doing a pip install from Git.

**Comment by langner** [comment]
> Is there an easy way to confirm the cclib version?

```python
>>> import cclib
>>> print cclib.__version__
```

**Comment by langner** [comment]
We should have a new version (1.6) in pip tomorrow or soon after. Leaving this pinned to the v1.6 milestone to confirm it's a versioning issue...

**Comment by ghutchis** [comment]
It works with 1.6. 

I think I still need to understand setup a bit better - installing from source wasn't replacing the already-installed version until I bumped the version number.

**Comment by berquist** [comment]
I consistently had problems with installation after changing over to `setuptools` until I completely wiped and reinstalled with `pip install .` or `pip install -e .`, depending on your preference.
