### ISSUE TITLE
natoms not set when reading Turbomole aoforce.out

### ISSUE THREAD

**Issue by oh-fv** [cclib/cclib#626]
Thank you so much for adding Turbomole support in 1.6!

So far, I only tested reading results from a frequency calculation using
`data = ccread('aoforce.out')`
and I noticed that `data.natom` is not set.

My simple fix is
`data.natom = len(data.atomcoords[0])`
but I guess there is a more straightforward way in the parser routine.

**Comment by langner** [comment]
Thanks for the report. Would you be willing to share the output file so we can debug?

**Comment by oh-fv** [comment]
I attached it to this post. Thank you for looking into this!
[aoforce.out.txt](https://github.com/cclib/cclib/files/2353251/aoforce.out.txt)

**Comment by langner** [comment]
Oh, `ccread` and some other helper functions might not have been fixed for multifiles/Turbomole yet. You can get multiple file parsing for now by going through the parser directly:
```python
import cclib
data = cclib.parser.Turbomole(['aoforce.out', 'basis', 'mos', ...]).parse()
```

**Comment by langner** [comment]
#627 should add parsing for `natom` when looking only at `aoforce.out`

**Comment by oh-fv** [comment]
Thanks a lot for the quick fix. I'll test the new version tomorrow at work, although it seems to be so simple that nothing can possibly be wrong with it :-)

I'm aware that cclib can parse a lot of the other output files as well, which is great. I'm currently only interested in the displacement vectors, however.

**Comment by langner** [comment]
Fixed.
