### ISSUE TITLE
Two issues encountered in CJSON writer test

### ISSUE THREAD

**Issue by langner** [cclib/cclib#641]
Noticed some things while doing #640 that should be fixed later:
1. The attribute `atomcoords` is missing when parsing the C_bigbasis DALTON unit test logfile:
```
$ ccget -l data/DALTON/basicDALTON-2013/C_bigbasis.out 
Attempting to read data/DALTON/basicDALTON-2013/C_bigbasis.out
cclib can parse the following attributes from data/DALTON/basicDALTON-2013/C_bigbasis.out:
  atombasis
  atommasses
  atomnos
  charge
  coreelectrons
  gbasis
  homos
  metadata
  moenergies
  moments
  mosyms
  mult
  natom
  nbasis
  nmo
  scfenergies
  scftargets
  scfvalues
```
2. The CJSON writer will not work currently if `atomcoords` is not present as in the above case, but we should just ignore and export everything else possible.

**Comment by berquist** [comment]
The DALTON carbon atom inputs are missing `.RUN PROPERTIES` under `**DALTON`.  There are other locations where coordinates are available (`Cartesian Coordinates (a.u.)`), but this block isn't in all calculations.
