### ISSUE TITLE
pytest: treat each regression file as its own test

### ISSUE THREAD

**Issue by berquist** [cclib/cclib#649]
From https://github.com/cclib/cclib/issues/455#issuecomment-409720496 and https://github.com/cclib/cclib/pull/647, when using pytest,

> Changing `main` to `test_regressions` allows pytest to automatically run regressions, but the current setup treats it as one big test. It would be nice if each regression file was its own individual test.

**Comment by langner** [comment]
Yeah, or at least break down by program(+version)?
