### ISSUE TITLE
Natural Spin Orbitals parsing

### ISSUE THREAD

**Issue by shivupa** [cclib/cclib#653]
Gaussian (and probably other programs) can calculate natural spin
orbitals which are not currently parsed. Currently, `nooccnos` (array of
rank 2) and `nocoeffs` (array of rank 1) are read in for natural
orbitals. These could be modified to lists of arrays for natural spin
orbitals, which would be consistent with the way spin
restricted/unrestricted MOs are handled. I would like to work on this if no one else is?

**Comment by berquist** [comment]
Nope, no one is working on it. However, this might be considered a breaking change, even if it's something that should be done. I would say to make the change if it isn't too troublesome, and it may require some discussion.

**Comment by langner** [comment]
I would say create another attribute now, and make the breaking change (can be list of arrays for now) hidden behind the `future` option we have (or whatever it's called).

**Comment by shivupa** [comment]
> hidden behind the `future` option
Can you explain how I would do this?

Also I'm going to add two new attributes `nsooccnos` and `nsocoeffs`

**Comment by langner** [comment]
The attributes are being added in #659.

**Comment by langner** [comment]
For the "future" features see [the flag](https://github.com/cclib/cclib/blob/04e55d2c26fdf5d9cdc211f10c4ce91f57dd5f44/cclib/scripts/ccget.py#L42). I think from there you can figure out how it's used. I don't we currently have any examples in the docs, but there are several experimental feature hidden there that break backwards compatibility and are waiting for version 2.x
