### ISSUE TITLE
ORCA parser does not include dispersion correction in scfenergies

### ISSUE THREAD

**Issue by theochemtheo** [cclib/cclib#660]
Hi,

Currently, the ORCA parser does not take into account dispersion corrections provided through post-SCF corrections, like the Grimme D3 correction.

I have attached an example below.

[wB97XD3_def2-SVP_toluene_S0_TDA6S_2-20.txt](https://github.com/cclib/cclib/files/2629257/wB97XD3_def2-SVP_toluene_S0_TDA6S_2-20.txt)

In this example, the pre-D3 SCF energy on the `Total Energy       :` line is `-306.98073026 Eh`, which is what cclib finds. However, the DFT+D3 energy is on the `FINAL SINGLE POINT ENERGY` line and is `-306.983847616167 Eh`.

I appreciate that this is possibly 'intended' behaviour, since strictly speaking, the D3 correction is post-SCF. However, this is inconsistent with, for example, Gaussian, since Gaussian includes the dispersion component in print outs of the SCF energy.

**Comment by ATenderholt** [comment]
Thanks for pointing this out and providing an example file. Do you agree to release the file under the public domain so we can include the file with our regression tests?

**Comment by theochemtheo** [comment]
Yes, I agree to releasing the file under public domain.

**Comment by langner** [comment]
Thanks, Theo. We deliberated about this before, for ORCA of all parsers, in #418. We did not come to a clear consensus. My own opinion is that `scfenergies` should be just the energy obtained after a self-consistent cycle. And I understand that would rule out the D3 correction which is an empirical thing - is that right? If so, then we should modify Gaussian to not parse the corrected energy, and parse it as a dispersion correction (or total dispersion energy if we prefer the total).

**Comment by theochemtheo** [comment]
Oh, apologies for not checking more thoroughly.

I agree that `scfenergies` should be only the energy that results from a self-consistent field. However, the D3 correction [only depends on the nuclear geometry](https://cms.mpi.univie.ac.at/vasp/vasp/DFT_D3_method.html). It does not depend on the SCF wavefunction in any way at all. I would therefore say it is entirely consistent to include it within the SCF energy, just as we include the nuclear repulsion energy in the SCF energy.

Also, from a pragmatic point of view, you can't guarantee that a Gaussian output will have a separable dispersion component, since [printing the dispersion component requires `#p`in the route](https://chemistry.stackexchange.com/a/65240).

**Comment by berquist** [comment]
I can't comment in depth right now (I need to revisit the other thread and my notes), but this poke moves dispersion further up the priority list.

> Also, from a pragmatic point of view

IIRC this was a problem with Q-Chem, and having it be a problem in multiple programs may change my opinion of how it's handled. Will revisit soon...

**Comment by ghutchis** [comment]
I'd like to chime in. Whatever people do, needs to be broadly advertised. I, for one, assumed that `scfenergies` would reflect the dispersion correction. Consider, if I do a DFT+D (for whatever dispersion correction), the intuition would be that `scfenergies` would reflect the end of that calculation. Otherwise, I'd have run a DFT calculation without dispersion.

I have a whole pile of energies that I need to go fix because we used `scfenergies` from ORCA calculations...

**Comment by langner** [comment]
It's great we're getting around to fixing this. It sounds like my intuition is in the minority and most people expect `scfenergies` to include any dispersion corrections, and I'm OK with that as well. If everyone agrees, let's go ahead and bake that into the docs and merge the ORCA fix.

**Comment by berquist** [comment]
Yes, let's do that.

**Comment by langner** [comment]
Since the ORCA dispersion fix is marked for `v1.6.2`, I'm pushing this one back as well.

**Comment by langner** [comment]
I think this is (partly) done - leaving around for v1.6.4 so we can make double sure.
