### ISSUE TITLE
Ensure dispersion correction is added to scfenergies for all packages

### ISSUE THREAD

**Issue by berquist** [cclib/cclib#664]
This is to help us keep track. It may not be relevant for all packages, but it should be investigated for each. Because this is relatively critical, the first pass should make sure `scfenergies` includes all relevant energies; for example, a 3-body energy may be optionally calculated, and might not be present in the final dispersion energy.

  * [ ] ADF (???)
  * [x] DALTON (???)
  * [x] Firefly (???)
  * [x] GAMESS-US (???)
~~  * [ ] GAMESS-UK (???)~~
  * [x] Gaussian (???)
~~  * [ ] Jaguar (???)~~
  * [x] Molcas (???)
  * [x] Molpro (???)
  * [x] MOPAC (???)
  * [x] NWChem (???)
  * [x] ORCA (issue: https://github.com/cclib/cclib/issues/660, PR: https://github.com/cclib/cclib/pull/418)
  * [x] Psi3 (???)
  * [x] Psi4 (???)
  * [x] Q-Chem (???)
  * [x] Turbomole (???)

**Comment by ghutchis** [comment]
MOPAC does not separate out the dispersion corrections. They’re included as part of the PM6 or PM7 energies.

**Comment by berquist** [comment]
That's what I thought. What about PM6-DH (if that's what its called)? Is that always the case?

**Comment by ghutchis** [comment]
No, I just tried a bunch of methods and they don’t give anything useful. I realized that cclib-data doesn’t have many MOPAC files. If you want to create an issue to generate more examples, I’d be happy to do that (frequency, CI, etc.)

**Comment by berquist** [comment]
The ORCA PR is using Hartree-Fock + D3 with Becke-Johnson damping. As discussed there, this is valid (there are D3(BJ) parameters for HF), and we should run with that for simplicity, since none of our jobs have dispersion correction present anyway.

**Comment by berquist** [comment]
# Programs

## NWChem (6.8)

https://github.com/nwchemgit/nwchem/wiki/Density-Functional-Theory-for-Molecules#disp----empirical-long-range-contribution-vdw

- limitations: D3(0) and D3(BJ) are available, but not for HF, because the parameters are not customizable. Usual functionals are present.
- print location: is displayed separately but also part of `Total DFT energy`, so is already part of `scfenergies`.

## Psi4 (1.2.1)

http://psicode.org/psi4manual/master/dftd3.html#sec-dftd3

- limitations: none
- print location: is displayed separately but also part of `Final Energy:`, so is already part of `scfenergies`.

## Q-Chem (5.1)

- limitations: none
- print location: already part of `scfenergies`

**Comment by langner** [comment]
This is great for keeping track. So I assume for each program we want to add regressions that include dispersion energies from various methods.

**Comment by langner** [comment]
Since some of the bugs cited here for specific parsers are marked for `v1.6.2`, I'm pushing this one back as well.

**Comment by berquist** [comment]
I've confirmed that the latest version of each package we support already includes the dispersion energy as part of the SCF energy, except for ORCA. I'm forced to ignore a number of packages because we just don't have access to them. So only the ORCA parser needs to be fixed.

I think the best action item would be to, for each package, add a pair of regression files:
- one that does not include the dispersion energy
- one that does include the dispersion energy

and assert that the SCF energy from the dispersion calculation equals the SCF energy from the non-dispersion calculation plus the separate empirical dispersion energy. This requires we [implement `dispersionenergies`](https://github.com/cclib/cclib/pull/418) and

> One possible answer is that `scfenergies` gives the dispersion-corrected energy, and `dispersionenergies` (or whatever we decide to call it) gives just the separable dispersion part (as done here), and `scfenergies - dispersionenergies` would give the nonempirical energy.

is basically this.

> I don't think scfenergies should include any such corrections, though, if they are not part of the self-consistent computation. This is the approach we've taken with `mpenergies` and `ccenergies` as separate number that should be added to `scfenergies`, and I think we should be consistent in that way. However, if we wanted to parse and provide some component of scfenergies, I think ideally it would be part of that attribute in the future. The particular case here is not that category IIUC.

Normally I would agree. But we've already seen that this is dangerous with ORCA (I made a comment that this happens but it didn't dawn on me), and normally this is added to the nuclear repulsion energy, which is part of `scfenergies`.

**Comment by ghutchis** [comment]
Do you need a set of ORCA regression files run? I have easy access to 3.x, 4.0, and 4.1 and would be happy to run them.

**Comment by berquist** [comment]
Nope, I've got all those versions locally. Thank you for the offer though. I'll fix it this weekend.

**Comment by langner** [comment]
@berquist Are we done here? If not, what remains to be done?

**Comment by berquist** [comment]
All the functionality is implemented, but I was struggling in https://github.com/cclib/cclib/pull/745 to get reference numbers consistent between programs.

**Comment by ghutchis** [comment]
Just saw these comments - based on the differences in dispersion energies, I think there's an issue in the D3 being used. Can you point me at the files - are they in the regression test repo?

**Comment by berquist** [comment]
All the work should be in the https://github.com/cclib/cclib/pull/745 branch, and nothing in `cclib-data`.
