### ISSUE TITLE
Add missing MOPAC examples

### ISSUE THREAD

**Issue by berquist** [cclib/cclib#665]
As mentioned in https://github.com/cclib/cclib/issues/664, we are missing many MOPAC examples for unit tests. This issue is to help figure out what attributes are  missing coverage, and check if new attributes are needed.

**Comment by langner** [comment]
> Also,
> 
> > It might be useful for some people to separate out the calculated heat-of-formation from the actual SCF total energy. We’ve found the latter to be more useful for machine learning, for example.

Is this specific to MOPAC?

**Comment by berquist** [comment]
Yes, I think so.

**Comment by langner** [comment]
Eric, can we close this for v1.6.3 or is there something actionable left here?

**Comment by langner** [comment]
> Eric, can we close this for v1.6.3 or is there something actionable left here?

I'm going to assume we can close this out.
