### ISSUE TITLE
Error parsing vibrational frequencies in ORCA 4.1.1

### ISSUE THREAD

**Issue by schneiderfelipe** [cclib/cclib#705]
Hi all,

`orcaparser.py` throws the following error when reading an output file from ORCA 4.1.1 (released December 2018):

```
In [1]: import cclib

In [2]: cclib.ccopen("methylpheophorbideB.out")
Out[2]: ORCA("methylpheophorbideB.out")

In [3]: of = cclib.ccopen("methylpheophorbideB.out")

In [4]: of
Out[4]: ORCA("methylpheophorbideB.out")

In [5]: of.parse()
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-5-464ffa4a8ac3> in <module>()
----> 1 of.parse()

/usr/local/lib/python3.6/dist-packages/cclib/parser/logfileparser.py in parse(self, progress, fupdate, cupdate)
    316             # Any attributes can be freely set and used across calls, however only those
    317             #   in data._attrlist will be moved to final data object that is returned.
--> 318             self.extract(inputfile, line)
    319 
    320         # Close input file object.

/usr/local/lib/python3.6/dist-packages/cclib/parser/orcaparser.py in extract(self, inputfile, line)
    939             vibfreqs = numpy.zeros(3 * self.natom)
    940             for i, line in zip(range(3 * self.natom), inputfile):
--> 941                 vibfreqs[i] = float(line.split()[1])
    942 
    943             nonzero = numpy.nonzero(vibfreqs)[0]

ValueError: could not convert string to float: 'factor'
```

[(The outfile is attached.)](https://github.com/cclib/cclib/files/2926679/methylpheophorbideB.zip)

Relevant lines in `orcaparser.py` (936--941):

    (...)
    if line[:23] == "VIBRATIONAL FREQUENCIES":
        self.skip_lines(inputfile, ['d', 'b'])

        vibfreqs = numpy.zeros(3 * self.natom)
        for i, line in zip(range(3 * self.natom), inputfile):
            vibfreqs[i] = float(line.split()[1])
    (...)

It looks like the new output is as follows:

```
(...)
-----------------------
VIBRATIONAL FREQUENCIES
-----------------------

Scaling factor for frequencies =  1.000000000  (already applied!)

   0:         0.00 cm**-1
   1:         0.00 cm**-1
   2:         0.00 cm**-1
   3:         0.00 cm**-1
   4:         0.00 cm**-1
   5:         0.00 cm**-1
   6:       -97.00 cm**-1 ***imaginary mode***
(...)
```

I'll try to do a PR if that's OK.

**Comment by ATenderholt** [comment]
We'd love a PR if you're willing to create one. Do you know if the problem was due to an ORCA 4.0 -> 4.1 change? Looks like we don't have 4.1 files yet, so might also be worth creating those.

**Comment by schneiderfelipe** [comment]
@ATenderholt I believe this new line about the scaling factor is new to ORCA 4.1.

I can rerun all tests from ORCA 4.0 in ORCA 4.1.1 and add the outputs as test data, if it's fine (maybe in a new PR?).

**Comment by ATenderholt** [comment]
We'd definitely appreciate re-running all of the tests with ORCA 4.1.1. I think we settled on a two-step process to maintain a history of test files:

1. Copy existing test files to new directory, and add to Git. 
2. Update test files and commit to Git.

Looks like @berquist did this for the ORCA 4.0 files: https://github.com/cclib/cclib/commits/master/data/ORCA/basicORCA4.0.

**Comment by schneiderfelipe** [comment]
Right, I updated PR #706.

**Comment by langner** [comment]
I think this is done. Thanks for taking care of this!
