### ISSUE TITLE
Deal with wide tables in RTD theme

### ISSUE THREAD

**Issue by langner** [cclib/cclib#709]
Currently, when pulling in updates for the RTD theme we use, I need to manually change the max-width CSS attribute, so that our wide tables render nicely. It would be nice to figure out how to do this automagically, or deal with the problem some other way (or find a better theme). Whatever.

**Comment by berquist** [comment]
I think this is not an issue anymore (https://cclib.github.io/data_dev.html#details-of-current-implementation).
