### ISSUE TITLE
Is it much fancier that redirect logs to stderr?

### ISSUE THREAD

**Issue by NKUCodingCat** [cclib/cclib#717]
Hey guys,

I had used an previous version of cclib(v1.6) as the parser of Gaussian09 log files in my [Gaussian Automator](https://github.com/NKUCodingCat/Gaussian-Automator/blob/master/run-g09.sh). But I found that the 1.6.1 version add a log class and send all logs to STDOUT. Is does makes me in trouble since logs and outputs are all mixed up. Besides, almost all of logging module set STDERR as default output stream, I cannot figure out the necessity that using STDOUT as log output.
So... is it better to use sys.stderr in this line?
https://github.com/cclib/cclib/blob/82ad8fa30a1f888ae6e51dbdd8c5bca480f5f1d0/cclib/parser/logfileparser.py#L194

thanks

**Comment by ATenderholt** [comment]
It looks like `ccopen` passes its kwd arguments, so perhaps you can just add `logstream=sys.stderr` to any place you call `ccopen` or related.

**Comment by langner** [comment]
Adam is right, but @NKUCodingCat has a point. Typically logging and other debugging messages are printed to stderr (https://stackoverflow.com/questions/4919093/should-i-log-messages-to-stderr-or-stdout).

**Comment by langner** [comment]
Trying out the switch to stderr in #718. At first glance parser tests look good, but maybe Travis will find something else.

**Comment by ATenderholt** [comment]
Travis is passing and nothing jumped out when I skimmed the logs, so I've merged #718. I'll mark this as closed. 

@NKUCodingCat, please let us know if there is anything else.

**Comment by NKUCodingCat** [comment]
@langner add `logstream=sys.stderr` works in my cases, thank you
