### ISSUE TITLE
Large number of logging messages printed

### ISSUE THREAD

**Issue by theochemtheo** [cclib/cclib#722]
Hi,

In version `1.6.1`, when parsing an output file, I get a large number of `INFO` level logging messages printed. I have tested this in `1.5.3` and this does not happen.

I have tested this on the ORCA 4.1 test file [`dvb_sp.out`](../blob/master/data/ORCA/basicORCA4.1/dvb_sp.out) but this is the case for Gaussian and Q-Chem also.

```
Python 3.4.6 (default, Mar 22 2017, 12:26:13) [GCC] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cclib
>>> cclib.io.ccread('dvb_sp.out')
<cclib.parser.data.ccData_optdone_bool object at 0x2b255c7f0f60
```

```
Python 3.6.6 |Anaconda, Inc.| (default, Jun 28 2018, 11:07:29)
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import cclib
>>> cclib.io.ccread('dvb_sp.out')
[ORCA dvb_sp.out INFO] Creating attribute metadata: {}
[ORCA dvb_sp.out INFO] Creating attribute charge: 0
...
[ORCA dvb_sp.out INFO] Creating attribute coreelectrons[]
<cclib.parser.data.ccData_optdone_bool object at 0x114f14e80>
```

I have only been able to test these on two different machines running different versions of python; however, [this google colab notebook](https://colab.research.google.com/drive/13_KA4t47QLZlQdu4U4fPURLTNoL07wPT) demonstrates the same issue.

Using the `logging` module, we can check on `1.6.1` to verify that the logging level is correct.
```
>>> import logging
>>> logging.getLogger('cclib')
<Logger cclib (WARNING)>
```

I have tried changing the logging level using
```
>>> logging.getLogger('cclib').setLevel(logging.ERROR)
>>> logging.getLogger('cclib')
<Logger cclib (ERROR)>
>>> cclib.io.ccread('dvb_sp.out')
[ORCA dvb_sp.out INFO] Creating attribute metadata: {}
[ORCA dvb_sp.out INFO] Creating attribute charge: 0
...
[ORCA dvb_sp.out INFO] Creating attribute coreelectrons[]
<cclib.parser.data.ccData_optdone_bool object at 0x11469aa90>
```

or other levels, but this does nothing.

Furthermore, changing the basic config level _increases_ the number of messages 
```
>>> logging.basicConfig(level=logging.ERROR)
>>> cclib.io.ccread('dvb_sp.out')
[ORCA dvb_sp.out INFO] Creating attribute metadata: {}
INFO:ORCA dvb_sp.out:Creating attribute metadata: {}
[ORCA dvb_sp.out INFO] Creating attribute charge: 0
INFO:ORCA dvb_sp.out:Creating attribute charge: 0
...
[ORCA dvb_sp.out INFO] Creating attribute coreelectrons[]
INFO:ORCA dvb_sp.out:Creating attribute coreelectrons[]
<cclib.parser.data.ccData_optdone_bool object at 0x1146b2a20>
```

This change cannot be reverted unless you close the session.

I am very confused as to what is happening here.

**Comment by vingman** [comment]
Just downgraded to 1.6 from 1.6.1 and the problem no longer happens

**Comment by berquist** [comment]
I am very confused and also annoyed about it, so I'll try and track this down soon.

**Comment by langner** [comment]
We recently changed the logging output so it that it goes to STDERR instead of STDOUT #718). But I guess that's not what you're complaining about. Should we lower our default logging level to WARNING or ERROR?

**Comment by berquist** [comment]
So it looks like we do not obey the global `logging` level, and instead set it on a per-file basis. If you do
```python
ccread(filename, loglevel=logging.WARNING)
```
or
```python
ccopen(filename, loglevel=logging.WARNING)
```
it should fix things.

> Should we lower our default logging level to WARNING or ERROR?

I vote ERROR. Right now, WARNING produces a lot of false positive messages that need to be fixed after an audit of how we set attributes in the parsers and using `check_change=False` where appropriate. It would also go along with the `ccget` default.

If there is a way for to respect a global logging level that's been set, rather than the default, we should do that too.

**Comment by theochemtheo** [comment]
Thanks @berquist, that does fix it for me.

If it's worth anything, I agree with setting the default to ERROR.
