### ISSUE TITLE
Cannot parse the inputfile section of an ORCA output

### ISSUE THREAD

**Issue by xxyxxyxyx1** [cclib/cclib#725]
cclib.io.ccread() fails when it tries to parse the inputfile that is printed near the top of my ORCA output file. 

The last part of the traceback:
```
~/anaconda3/lib/python3.7/site-packages/cclib/parser/orcaparser.py in extract(self, inputfile, line)
    135                 # Geometry block
    136                 elif line[0] == '*':
--> 137                     coord_type, charge, multiplicity = line[1:].split()[:3] 
ValueError: not enough values to unpack (expected 3, got 0)
```

My inputfile is correct, with a geometry block starting with:
`* xyz -4 1`

I have attached the output file. If anyone can recommend a method of circumventing this error in the meantime, I would appreciate it. 
Thanks

[cl2.out.txt](https://github.com/cclib/cclib/files/3101430/cl2.out.txt)

**Comment by berquist** [comment]
Thanks for the report! It's because of the embedding potentials.

Here is the relevant section from the 4.1.2 manual:

> - Dummy atoms are defined in exactly the same way as any other atom, by using “DA” as the atomic symbol.
> - Ghost atoms are specified by adding “:” right after the symbol of the element (see 8.1.6).
> - Point charges are specified with the symbol “Q”, followed by the charge (see 9.1.3).
> - Embedding potentials are specified by adding a “>” right after the symbol of the element (see 9.4.8).
> - Non-standard isotopes or nuclear charges are specified with the statements “M = ...” and “Z = . . . ”, respectively, after the atomic coordinate definition.
> - Fragments can be conveniently defined by declaring the fragment number a given atom belongs to in parentheses “(n)” following the element symbol (see 9.1.1).

We currently don't have any way of differentiating between these in cclib. It's also not well-defined what we do with things like ghost atoms. They also crash the ORCA parser:
```
! hf sto-3g verytightscf noautostart

* xyz 0 1
O : 7.439917 6.726792 7.762120
H : 7.025510 6.226170 8.467436
H : 8.274883 6.280259 7.609894
O   5.752050 6.489306 5.407671
H   6.313507 6.644667 6.176902
H   5.522285 7.367132 5.103852
*
```
and other parsers behave differently, with Psi4 and Q-Chem doing the "correct" thing:
```Attempting to read psi4.out
atomnos
array([8, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 8, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)
Attempting to read qchem.out
atomnos
array([8, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 8, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)
Attempting to read gaussian.out
atomnos
array([8, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 8, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2], dtype=int32)
```
where the ghost atoms are supposed to have a helium basis.

What should the embedding potential atoms be parsed as for `atomnos`? Should they be added at all? Point charges in the input file also crash the parser, but not when they're external and specified using `%pointcharges`, in which case they don't appear as atoms at all.

**Comment by langner** [comment]
Thanks for the analysis, Eric. Do you have an idea what we should do? IMO the first priority should be to get the file parsed, and use a reasonable default. Ideally we would handle ghost atoms in some way, although I don't think we have a convention about that.

**Comment by berquist** [comment]
I have the fix done, but just for this case, not the general ghost atoms or point charge cases. The result is embedding potentials are ignored everywhere (`atomcoords`, `atommasses`, `atomcharges`).

In the future everything should be unified with metadata for different "atom types", but with the representations we have now, having 0 for ghost atoms is ok but not great, and everything else is less clear to me. I can see what is in QCSchema currently.

**Comment by xxyxxyxyx1** [comment]
I think embedding potentials should be ignored in most situations, and certainly for the number of atoms. 

Embedding potentials were added to ORCA to solve a specific problem: if one wants to approximate an electrostatic environment by putting the quantum model inside a field of point charges, there will be unphysical flow of electrons towards the positive point charges. To fix this, a "boundary region" of embedding potentials is used, where the point charges are capped with valence-only basis sets that provide the necessary repulsion. 

So, we think of embeding potentials as "point charges, with some hackey repulsion added." I think they should be ignored in any situation where point charges are ignored.

**Comment by xxyxxyxyx1** [comment]
When might it be possible for me to use your fixed version of cclib? If it's a long way from being publically available, should I just delete the 'X>' from the input section of my output files? 

(I'm sorry if this is an odd question; I'm not really familiar with github / the versioning of software)

**Comment by langner** [comment]
I'm not sure what Eric means by "the fix is done", but I assume he has some branch with the fix, because I haven't seen a PR on this topic. Once we merge in his fix, you should be able to download and use it from the repository immediately.

**Comment by langner** [comment]
@xxyxxyxyx1 You should now be able to use the `master` branch of the repo to get the fix. Would you prefer to have a new packaged version?
