### ISSUE TITLE
'list' object has no attribute 'resize' in self.homos.resize([2])

### ISSUE THREAD

**Issue by alongd** [cclib/cclib#754]
Executing `data = ccparser.parse()`, I got the following error:
```python
   2023         ccparser = cclib.io.ccopen(str(job.local_path_to_output_file), logging.CRITICAL)
-> 2024         data = ccparser.parse()

site-packages/cclib/parser/logfileparser.pyc in parse(self, progress, fupdate, cupdate)
    327             #   in data._attrlist will be moved to final data object that is returned.
    328             try:
--> 329                 self.extract(inputfile, line)
    330             except StopIteration:
    331                 self.logger.error("Unexpectedly encountered end of logfile.")

site-packages/cclib/parser/gaussianparser.pyc in extract(self, inputfile, line)
   1033                         #  donated by Gregory Magoon (gmagoon).
   1034                         if (hasattr(self, "homos")):
-> 1035                             self.homos.resize([2])  # Extend the array to two elements
   1036                             self.homos[1] = i - 1  # 'HOMO' indexes the HOMO in the arrays
   1037                         else:  # otherwise (e.g. for O triplet) there is no alpha virtual orbital, only beta virtual orbitals, and we initialize the array with one element

AttributeError: 'list' object has no attribute 'resize'
```

**Comment by langner** [comment]
Hi Alon. Would you be willing to share the file you were parsing that caused this issue?

**Comment by alongd** [comment]
Sure, it should be this one:
[output.txt](https://github.com/cclib/cclib/files/3503954/output.txt)

**Comment by berquist** [comment]
This file parses for me using the current master branch. Can you find out what version you're using (with `cclib.__version__`)?

**Comment by alongd** [comment]
Yes, I'm using 1.6.1

**Comment by langner** [comment]
Seems like it was fixed sometime since then. I want to release 1.6.2 within the next week, otherwise you need to use master before that happens.

**Comment by langner** [comment]
I also checked in 1.6 which is the current version in Ubuntu/Debian and it parsed fine.

I also tried checking out `v.1.6.1` from the repo and the file parses fine:
```
$ git checkout v1.6.1
...
$ python
>>> import cclib
>>> cclib.io.ccopen('output.txt')
Gaussian("output.txt")
>>> cclib.io.ccopen('output.txt').parse()
[Gaussian /home/kml/output.txt WARNING] Number of basis functions (nbasis) has changed from 162 to 180
<cclib.parser.data.ccData_optdone_bool object at 0x7f691a1b8310>
```

I see the same thing in Python3 and Python2. Can anyone confirm this parsing issue in Anaconda for this file?

**Comment by berquist** [comment]
I have no parsing issue using 1.6.1 from conda-forge, which is the first cclib version to appear there. This must be another version, or perhaps some stale `pyc` files are left behind from a previous install? The first thing to try is uninstalling and reinstalling.

**Comment by langner** [comment]
It doesn't look like there's anything to fix. @alongd please re-open if you run into this again from a fresh install.
