### ISSUE TITLE
Travis CI seg fault

### ISSUE THREAD

**Issue by shivupa** [cclib/cclib#755]
Travis is seg faulting in some weird way affects #752 , (possibly) #753, and #751

**Comment by shivupa** [comment]
Might be fixed with #760  Current PRs will need to be rebased and also we need to delete the caches on current travis builds.

**Comment by langner** [comment]
This is the one thing I **really** want to get fixed before releasing v1.6.2.

**Comment by berquist** [comment]
This was fixed by https://github.com/cclib/cclib/pull/760 as confirmed by merging https://github.com/cclib/cclib/pull/762.
