### ISSUE TITLE
PyQuante does not support Python 3 (yet)

### ISSUE THREAD

**Issue by schneiderfelipe** [cclib/cclib#757]
Hi all,

I got myself interested in obtaining densities (I believe some QTAIM/ELF/NCI stuff can be easily implemented on top of cclib) and the code in `cclib.method.volume` seems perfect for that.
Unfortunately, it's heavily based on PyQuante (the lines [208](https://github.com/cclib/cclib/blob/master/cclib/method/volume.py#L208) and [227](https://github.com/cclib/cclib/blob/master/cclib/method/volume.py#L227) are critical), a Python 2 only library.

Is there a way around this?  It looks like PyQuante is only used for the spatial representation of wavefunctions. Could it be replaced (or a fallback be used in case PyQuante isn't available)?

**Comment by shivupa** [comment]
Hey sorry I saw your PR as well, but you could also try to add pyscf integration. There is the`eval_gto` functionality that could help.

**Comment by schneiderfelipe** [comment]
> Hey sorry I saw your PR as well, but you could also try to add pyscf integration. There is the`eval_gto` functionality that could help.

@shivupa Do you mean [eval_ao](https://sunqm.github.io/pyscf/dft.html?highlight=eval#pyscf.dft.numint.eval_ao)? By the way, thanks for mentioning pyscf, I didn't know about it.

**Comment by shivupa** [comment]
No worries and yes that's the one I was thinking of!

**Comment by berquist** [comment]
An option is to add [pyquante2](https://github.com/rpmuller/pyquante2/blob/6e34cb4480ae7dbd8c5e44d221d8b27584890c83/pyquante2/basis/cgbf.py#L57)/Psi4/pyscf/etc bridges, implement `volume.getbfs` for each one, and then pass this as a function pointer to `volume.wavefunction` and `volume.electrondensity` to abstract away this part of the implementation.

**Comment by berquist** [comment]
We have dropped Python 2 support, moved away from PyQuante to pyquante2, and Psi4 and pyscf bridges exist. https://github.com/cclib/cclib/issues/757#issuecomment-529069235 is still missing.

**Comment by amandadumi** [comment]
I just wanted to chime in and say I have a some (messy) work started that does exactly this for pyscf! I was working on mimicking the current data structures, but if you plan on changing this, I can certainly adjust.
