### ISSUE TITLE
Development docs always build from master, not the current checked-out branch

### ISSUE THREAD

**Issue by berquist** [cclib/cclib#766]
as discovered in https://github.com/cclib/cclib/pull/762.

**Comment by langner** [comment]
We might want to prioritize this for GSOC2020.

**Comment by berquist** [comment]
@langner Do you want to take it, or should someone else?

**Comment by langner** [comment]
> @langner Do you want to take it, or should someone else?

I can, although I don't know where to start. So if you have an idea, feel free to take the lead.

**Comment by berquist** [comment]
Done in #1309
