### ISSUE TITLE
Duplicate test method name in testutils.py

### ISSUE THREAD

**Issue by pandaxtc** [cclib/cclib#773]
In test/parser/testutils.py, there's two methods defined with the same name (test_elements): https://github.com/cclib/cclib/blob/173ee7091104a66506009c82f73b1b61991d174e/test/parser/testutils.py#L44-L58

Because of this, only the second test_elements actually runs. Should this be fixed?

**Comment by berquist** [comment]
Yes please!

**Comment by pandaxtc** [comment]
Opened a PR 👌
