### ISSUE TITLE
Switch from `pip` to `conda` in Travis

### ISSUE THREAD

**Issue by berquist** [cclib/cclib#782]
Because of https://github.com/openbabel/openbabel/issues/2067, we can no longer use `pip` to install Open Babel. However, thanks to Felipe's hard work in https://github.com/cclib/cclib/pull/758, it should be straightforward to make the full switch over.

Personally, I do not like `conda` at all, one reason being its slowness, especially on Travis (total time for a single build went up to 12 and a half minutes from 7 and a half on 3.7), but we don't have much choice unless we'd like to build just the Python bindings form scratch, and we're already using it for Psi4 anyway.

**Comment by berquist** [comment]
Oh, and this is in order to upgrade from Open Babel 2.4.1 to 3.0.0, which...do we want to?

**Comment by langner** [comment]
You mentioned in the other bug we're already using Conda... for what?

I personally don't mind much what we use on Travis, since this is just for testing, although I'd tend towards to lighter option (which means pip here). FTR though, I would like to continue supporting cclib in both pip and conda (although I understand that's not the issue at hand here).

**Comment by berquist** [comment]
> You mentioned in the other bug we're already using Conda... for what?

Psi4; the alternative is to download a tarball with a pre-built version, but we don't have anywhere to host it. Building it from source every time is worse, even with caching.

For Open Babel 3.0, there are breaking Python API changes. It doesn't look like even the latest Ubuntu distro [has it available](https://packages.ubuntu.com/search?keywords=openbabel&searchon=names&suite=all&section=all) so changing the PPA wouldn't work to get the compiled library. `conda` might just be simpler here...

> FTR though, I would like to continue supporting cclib in both pip and conda (although I understand that's not the issue at hand here).

At the cost of some CI complexity, maybe we can have some runs that test all the functionality (like bridges) with `conda` and have other runs that test core functionality but installed with `pip`? We would use a matrix in `.travis.yml` rather than just Python versions, and need to introduce some conditional logic in our tests to skip them when dependencies aren't installed.

**Comment by langner** [comment]
Ok then, let's do it.

**Comment by berquist** [comment]
I think this was done in some combination of #758, #881, #939, though in between #939 and switching to GitHub Actions in #983 we never fully switched.
