### ISSUE TITLE
Raman activities marked as Raman intensities

### ISSUE THREAD

**Issue by marcin-witkowski** [cclib/cclib#791]
https://cclib.github.io/data.html states that Raman intensities are returned with vibramans, which is not true, as Raman activities (calculated with CC software) are returned. Raman intensities are dependent on the excitation lines used in the experiment.

**Comment by langner** [comment]
Hi Marcin - thanks for the report. Please be more specific, in particular:
* Which parser are you referring to?
* Do you have an example logfile we can use?

**Comment by marcin-witkowski** [comment]
>     * Which parser are you referring to?

I am working with Gaussian parser, but I presume the issue is universal, as it is a problem with the documentation (particularly the file linked in the original post), rather than parsers themselves.

>     * Do you have an example logfile we can use?

To be honest, the files you already have are sufficient. Consider the file cclib\data\Gaussian\basicGaussian16\dvb_raman.out, particularly lines (e.g.) 982 and 983. cclib returns the contents of such lines with vibirs and vibramans. Line 982 contains _IR Inten(sities)_, and the output of vibirs is documented accordingly. However, line 983 contains _Raman Activ(ities)_, while the cclib documentation mistakenly states that vibramans returns Raman intensities. For the discussion on the relation between Raman activities and intensities see e.g. 10.1016/j.cplett.2004.12.096 (especially eq. 7).

**Comment by langner** [comment]
Thanks for clarifying, Marcin, I glanced over your original report much too quickly! That particular mention should be addressed by #791, and I changed two others I found with a brief search.

If you find anything else wrong, please do let us know. In particular, are the units for IR intensities and Raman activities correct?

**Comment by langner** [comment]
Should be all good here now.
