### ISSUE TITLE
T1 diagnostics from coupled-cluster methods

### ISSUE THREAD

**Issue by schneiderfelipe** [cclib/cclib#807]
Hi,

As a suggestion, cclib could read some extra information about coupled-cluster methods such as the T1 diagnostic, a ubiquitous way of checking multireference character:

```
----------------------
COUPLED CLUSTER ENERGY
----------------------

E(0)                                       ...     -1.101546711
E(CORR)(strong-pairs)                      ...     -0.039911635
E(CORR)(weak-pairs)                        ...      0.000000000
E(CORR)(corrected)                         ...     -0.039911635
E(TOT)                                     ...     -1.141458346
Singles Norm <S|S>**1/2                    ...      0.016072601
T1 diagnostic                              ...      0.011365045
```

(The above was taken from [this logfile](https://github.com/cclib/cclib/files/4311961/singlepoint.out.zip), the same example as in #806.)

**Comment by langner** [comment]
Could you elaborate of provide a reference where the usefulness of the T1 diagnostic is described?

**Comment by schneiderfelipe** [comment]
The T1 diagnostic is used for judging how reliable a single determinant calculation is. The value is proportional to the norm of the vector of first excitation amplitudes ("T1 hat" in CC methods). In general, a T1 diagnostic larger than 0.02 indicates enough multi-reference character to doubt the validity of CC methods in general. I believe the original proposal for the T1 diagnostic is due to [Lee and Taylor (1989)](https://doi.org/10.1002/qua.560360824).

**Comment by berquist** [comment]
Yes, I think that's the original reference. I agree that it is useful, I parsed it "by hand" in the past. Every CC program prints it. It isn't in QCSchema yet (https://github.com/MolSSI/QCSchema/blob/master/qcschema/dev/properties/cc_properties.py) either. This probably shouldn't be a top-level attribute, but it isn't metadata either. Maybe once `ccenergies` becomes more complex, as they're related.

**Comment by langner** [comment]
Thanks for the context - I think Eric's plan is good, although I don't see a way to incorporate it before 2.x without putting it in `metadata` for the time being. So I'd be supportive of doing that given there's a clear need and it's relatively easy to do.
