### ISSUE TITLE
Use extras_requires in setup.py for soft dependencies

### ISSUE THREAD

**Issue by schneiderfelipe** [cclib/cclib#833]
Using [`extras_requires`](https://setuptools.readthedocs.io/en/latest/setuptools.html#new-and-changed-setup-keywords) in `setup.py` might make it simpler to handle soft dependencies. This allows one to install cclib as

    $ pip install cclib  # default dependencies
    $ pip install cclib[extra_feature]  # default + dependencies for 'extra_feature'

**Comment by langner** [comment]
Do you have a specific improvement in the codebase in mind?

**Comment by schneiderfelipe** [comment]
> Do you have a specific improvement in the codebase in mind?

Currently, some features soft depend on extra packages. For instance, [searching for `find_package`](https://github.com/cclib/cclib/search?q=find_package&unscoped_q=find_package) in the codebase, we get the following soft dependencies (and the pieces that depend on them):

- Bio (`bridge.cclib2biopython.makebiopython`)
- openbabel (`from bridge.cclib2openbabel import makecclib, makeopenbabel, readfile`, `from io.ccio import fallback, ccframe` and alternative behavior in `io.cmlwriter.CML.generate_repr`, `io.filewriter.Writer.__init__`, `io.cjsonwriter.CJSON.as_dict`)
- PyQuante (`bridge.cclib2pyquante.makepyquante` and `method.volume.getbfs`)
- psi4 (`bridge.cclib2psi4.makepsi4`)
- pyvtk (`method.volume.Volume.writeasvtk`)
- periodictable (`method.nuclear.get_isotopic_masses`)
- scipy (`from method.nuclear import principal_moments_of_inertia, rotational_constants`)
- pandas (`scripts.ccframe.process_logfiles` and `io.ccio.ccframe`)

Today, if a user needs some of the above, they will have to install each package by themselves. But, sometimes it isn't obvious which package one needs. We could make it easier by listing all soft dependencies in `setup.py`, such that we could do something like

```bash
$ pip install cclib[ccframe,rotational]
```

and pip automatically installs pandas and scipy as well.

**Comment by berquist** [comment]
Unless there are objections to a lack of granularity, what about just an `all` target that includes everything?

**Comment by langner** [comment]
> Unless there are objections to a lack of granularity, what about just an `all` target that includes everything?

Does that mean we could go `pip install cclib[all]`?
