### ISSUE TITLE
AssertionError when parsing UHF/ROHF Psi output files 

### ISSUE THREAD

**Issue by rbenda** [cclib/cclib#841]
Good morning everyone,

I encounter a problem when parsing an output file of Psi4, for a Cu2+ UHF calculation (input :
---------------------------------------------------------------------
[output.log](https://github.com/cclib/cclib/files/4503441/output.log)

#! 6-31G(d) optimization of Cu(2+)
molecule {
2 2
 CU  0.00000000  0.00000000  0.00000000
}

set {
  scf_type pk
  basis 6-31G(d)
  reference uhf
}

set print 3
set print_basis True

thisenergy = energy('scf',return_wfn=True)
grad, wfn = gradient('hf', return_wfn=True)
fchk(wfn,'CU2_UHF_6-31Gd_psi4.fchk')
gdma(wfn)_

--------------------------------------------
When running 'ccget --list output.dat' (the file output.dat is 
[output.log](https://github.com/cclib/cclib/files/4503493/output.log) ; I get the following error message : 

"Attempting to read output.dat
Traceback (most recent call last):
  File "/home/rbenda/anaconda3/bin/ccget", line 10, in <module>
    sys.exit(ccget())
  File "/home/rbenda/anaconda3/lib/python3.7/site-packages/cclib/scripts/ccget.py", line 171, in ccget
    data = ccread(filename, **kwargs)
  File "/home/rbenda/anaconda3/lib/python3.7/site-packages/cclib/io/ccio.py", line 182, in ccread
    return log.parse()
  File "/home/rbenda/anaconda3/lib/python3.7/site-packages/cclib/parser/logfileparser.py", line 329, in parse
    self.extract(inputfile, line)
  File "/home/rbenda/anaconda3/lib/python3.7/site-packages/cclib/parser/psi4parser.py", line 506, in extract
    assert line.strip() == 'Final Occupation by Irrep:'
AssertionError"

It seems that the 'self.reference' variable in the psi4parser.py parsing code, is not correctly filled...
I have exactly the same problem if replacing 'uhf' by 'rohf' ; and for any other open shell system output.
For a closed-shell shell system (e.g. Na+) ; the parsing is correctly done.

I am using a recent cclib version (2019) ; it is strange as I saw the parsing of ROHF/UHF Psi4 calculations had already been solved, so I might forget something ...
Sorry if this problem is actually not a problem...
Thank you in advance,
Robert Benda

**Comment by shivupa** [comment]
Hi,
Thanks for reaching out. Let's see if we can get this sorted.

When I run `ccget --list output.log` on the current develop branch, I get the following output: 
```
Attempting to read output.log
cclib can parse the following attributes from output.log:
  atombasis
  atomcoords
  atommasses
  atomnos
  charge
  coreelectrons
  gbasis
  grads
  homos
  metadata
  moenergies
  mosyms
  mult
  natom
  nbasis
  nmo
  scfenergies
  scftargets
  scfvalues
```

This seems to be working correctly. 
Could you run the following and attach paste the output here: 
```
import cclib
print(cclib.__version__)
print(cclib.__file__)
``` 

How did you install `cclib`? Could you try to update and see if the problem persists?

**Comment by berquist** [comment]
Yes, parsing anything >= 1.2 was broken until I fixed it in https://github.com/cclib/cclib/pull/799/commits/402dd377ea5776b37c1741cc7b2277db23444c09. Until cclib 1.6.3 is released, you should be able to parse this with the current Git master.

**Comment by rbenda** [comment]
Thank you very much for your help.
I installed cclib following the https://cclib.github.io/how_to_install.html page ; using 'python -m pip install cclib' command if I remember well.
Redoing this command tells me :
'Requirement already satisfied: cclib in /home/rbenda/anaconda3/lib/python3.7/site-packages (1.6.2)
Requirement already satisfied: numpy in /home/rbenda/anaconda3/lib/python3.7/site-packages (from cclib) (1.18.1)
Requirement already satisfied: six in /home/rbenda/anaconda3/lib/python3.7/site-packages (from cclib) (1.14.0)'

and 
print(cclib.__version__)
print(cclib.__file__)

gives me :+1: 
1.6.1
/home/rbenda/anaconda3/lib/python3.7/site-packages/cclib/__init__.py

Actually I just solved my problem thanks to your help. I copied simply the last version of the PSI4 parser code 'psi4parser.py', and I have now the same output as yours ; with all attributes correctly parsed.

So my problem is solved, thank you !

Nevertheless, it is a bit strange as I installed cclib very recently (2 months ago roughly) and I did ont change anything in psi4parser.py code (juste made some 'print(..)' to see what was going wrong).
I join you the version I had of psi4parser.py (the one which was not working) : 
[psi4parser_OLD_py.log](https://github.com/cclib/cclib/files/4516514/psi4parser_OLD_py.log) 
(changed in .log so that it is accepted by the website).

I simply notice that roughly line 117, in my "old" (?!) version of psi4parser.py, I had :

        _# Determine whether or not the reference wavefunction is
        # restricted, unrestricted, or restricted open-shell.
        if line.strip() == "SCF":
            **self.skip_line(inputfile, 'author list')
            line = next(inputfile)**
            self.reference = line.split()[0]
            # Work with a complex reference as if it's real.
            if self.reference[0] == 'C':
                self.reference = self.reference[1:]_

while in the github most recent version that I just copied, there is :+1: 

           if line.strip() == "SCF":
            while "Reference" not in line:
                line = next(inputfile)
            self.reference = line.split()[0]
            # Work with a complex reference as if it's real.
            if self.reference[0] == 'C':
                self.reference = self.reference[1:]

Maybe the problem came from this (the 'unrestricted' flag was not correctly activated). It is strange ; I don't remember to have change this code (actually I am almost sure I did not ; there was no reason to  do it).

Thanks a lot ; the parsing of attributes works perfectly now  also for me both for UHF and ROHF,

Best regards,
Robert

**Comment by shivupa** [comment]
Yeah the version you have does not yet have the commit @berquist mentioned. 

I'm glad it's fixed, but in case anyone else stumbles on this I would recommend fixing this by uninstalling the version currently installed:
```
pip uninstall cclib
```
then downloading the zip of the [current master from github](https://github.com/cclib/cclib/archive/master.zip) and finally following the instructions for a manual install [here.](https://cclib.github.io/how_to_install.html#manual-download-and-install)

This will contain any changes that have come after the most recent package version, which are slated for the next release.

I'm going to close the issue though since this is working.

**Comment by langner** [comment]
In that case I will accelerate the 1.6.3 release somewhat. It's overdue anyway.
