### ISSUE TITLE
conda-forge package out of date

### ISSUE THREAD

**Issue by mskblackbelt** [cclib/cclib#844]
I tried installing `cclib` and `openbabel` from conda-forge. The current version of `openbabel` is 3.0.0 and the version of `cclib` is 1.6.2. When I try to do a `filewrite` operation, I get a `pybel not found` error. 

I noticed that pull  #787 is a fix for this. Can the conda-forge package be updated to reflect these changes?

**Comment by shivupa** [comment]
There is no v1.6.3 for `cclib` yet. Until we create the next release you could follow the steps below for a temporary fix:

I would recommend fixing this by uninstalling the version currently installed:
```
pip uninstall cclib
```
then downloading the zip of the [current master from github](https://github.com/cclib/cclib/archive/master.zip) and finally following the instructions for a manual install [here.](https://cclib.github.io/how_to_install.html#manual-download-and-install)

This will contain any changes that have come after the most recent package version, which are slated for the next release.

Let me know if you have any trouble.

**Comment by berquist** [comment]
The other less desirable solution is to install the Open Babel 2.4.1 package from conda-forge.

**Comment by langner** [comment]
The conda package will update automatically on the next release. I will try to push out the release soon.

**Comment by langner** [comment]
> The conda package will update automatically on the next release. I will try to push out the release soon.

Let's keep this open for now to makes sure this is the case after the release.
