### ISSUE TITLE
scanparm is a list of map objects

### ISSUE THREAD

**Issue by mskblackbelt** [cclib/cclib#851]
When importing a Gaussian PES scan, scanparm is a list of map objects. I can't find a clean way to extract a list of scan parameters without `list(map(list, molecule.scanparm))`. I'm sure I'm making that transform more complicated than necessary, but the fact remains that `molecule.scanparm` should consist of a flat list of numbers. 

https://github.com/cclib/cclib/blob/409e7f9ee87c02240b78eb1845177656e844159b/cclib/parser/gaussianparser.py#L977

**Comment by langner** [comment]
Ah, I guess this is something that happaned with Python3. Should be easily fixable.

**Comment by langner** [comment]
That's odd - it seems we have no test file for Gaussian with a surface scan. @mskblackbelt could you attach an example here perhaps so that we at least have a regression test?

**Comment by langner** [comment]
The map thing should be fixed by #862, but I looked at the code and unit tests and I think I know what's going on. The `dvb_scan` unit test logfile has a relaxed scan, whereas the code in the parser only seems to cover the unrelaxed case for which we don't have an example yet.

**Comment by mskblackbelt** [comment]
The output file is available [here](https://gist.github.com/mskblackbelt/57c4bac6ed172d16b1c10c6b0160893f). Let me know if you need something additional/different.

**Comment by mskblackbelt** [comment]
Input, for reference: 

```
%nproc=4
%mem=400MB
# HF 6-31G(d,p) scf=tight scan

h3o+ scan along umbrella mode

1 1
O 
X 1 a 
H 1 a 2 HOX
H 1 a 2 HOX 3  120.
H 1 a 2 HOX 3 -120.

a=0.961
HOX 135. 45 -1.

```
