### ISSUE TITLE
Parsing frequency jobs in linked calculations

### ISSUE THREAD

**Issue by mit-eremin** [cclib/cclib#871]
When parsing IR and Raman spectra from Q-Chem output files the current cclib combines all jobs from the output and create a "combined" spectrum. If one makes a TS job, it is often that calculation starts and finishes with frequency jobs.
I will be absolutely great, if there will be an opportunity to check the output file for frequency jobs and parse from only the last one.

**Comment by langner** [comment]
Sounds like a bug, because out intent is to parse and expose just the last output if there are multiple outputs. Do you have an example we could use for testing?

**Comment by mit-eremin** [comment]
Sure! This is an example with HSO2F. As a result of parsing (and then broadening) data.vibfreqs and data.vibirs I got this combined spectrum.
[HSO2F_TS.txt](https://github.com/cclib/cclib/files/4743849/HSO2F_TS.txt)
[HSO2F_TS_IR_gaussian_plot.pdf](https://github.com/cclib/cclib/files/4743850/HSO2F_TS_IR_gaussian_plot.pdf)

**Comment by mit-eremin** [comment]
Hi @berquist, any updates on this parsing frequencies when multiple frequency jobs are in the output?

**Comment by berquist** [comment]
Oh no, I missed this issue's first birthday. Hopefully it hasn't learned to talk yet. Thank you for bringing this to my attention. If you don't already have a fix for this, I will handle it.
