### ISSUE TITLE
Gaussian 09 Opt + TDA yields excited states data at every iteration

### ISSUE THREAD

**Issue by oliver-s-lee** [cclib/cclib#889]
Parsing a Gaussian 09 log file from optimising an excited state yields excited states data (etenergies etc...) from every round of the optimisation, not just the final energies.

This was surprising because, unlike atomcoords for example, etenergies and friends are rank 1 arrays, so all the excited states from every round of optimisation are together in a single array, rather than being split as for many other parsed properties.

A simple work around is to split etenergies where the energy suddenly decreases, or by the number of optimisation rounds (len(scfenergies) for example), but I'm not sure how stable a solution this is (wouldn't work if etenergies was re-ordered by increasing energy, for example).

I'm not sure if this is a bug or not, but I couldn't find this behaviour described in the docs so thought I'd post it.

I have an example log file, please let me know if it would be useful.

**Comment by shivupa** [comment]
Hi thanks for reaching out. Please do post the example log file that would be helpful!

**Comment by oliver-s-lee** [comment]
No worries, have done so:
[Benzene.Optimisation.tar.gz](https://github.com/cclib/cclib/files/4821532/Benzene.Optimisation.tar.gz)

**Comment by langner** [comment]
Thanks! Indeed it looks like a bug; `etenergies` and friends should have the last set of excited states.

From the [docs](http://cclib.github.io/data_notes.html#etenergies): There should be as many elements to this array as there are excited states calculated.
