### ISSUE TITLE
Switch to atomic units

### ISSUE THREAD

**Issue by langner** [cclib/cclib#89]
We might have had this discussion on the mailing list before, but it would be nice to be able to get all attributes in alternative units. Mostly atomic units for me (hartress, etc), since I find myself constantly converting to those.

It would be useful both in the parsers and ccopen/ccget.

**Comment by berquist** [comment]
Since this is a breaking change, should it go in the v2.0 milestone?

**Comment by langner** [comment]
Setting atomic as the default would be breaking, but adding the ability to switch could be done earlier.

**Comment by langner** [comment]
@berquist Do you think defaulting to atomic is desirable for 2.x?

**Comment by berquist** [comment]
Yes, absolutely.

**Comment by langner** [comment]
As per discussion, we are thinking to just switch for 2.x, but not enabling converting functionality. Store the unit in attribute classes, but don't plan to add convert method for now.

**Comment by berquist** [comment]
Here are all quantities (and perhaps more) that have units attached. I could use help in fleshing this out. What needs to be changed aside from the usual electronic energies?

| attribute          | current units    | future units |
|--------------------|------------------|--------------|
| atomcharges        |                  |              |
| atomcoords         | angstroms        |              |
| atommasses         | daltons          |              |
| atomspins          |                  |              |
| ccenergies         | eV               | hartree      |
| charge             |                  |              |
| dispersionenergies | eV               |              |
| enthalpy           | hartree/particle |              |
| entropy            | particle*kelvin  |              |
| etenergies         | 1/cm             | hartree      |
| etoscs             |                  |              |
| etdips             | ebohr            |              |
| etveldips          | ebohr            |              |
| etmagdips          | ebohr            |              |
| etrotats           | ??               |              |
| freeenergy         | hartree/particle |              |
| geotargets         |                  |              |
| geovalues          |                  |              |
| grads              |                  |              |
| hessian            |                  |              |
| moenergies         | eV               | hartree      |
| moments            | a.u.             |              |
| mpenergies         | eV               | hartree      |
| polarizabilities   | a.u.             | a.u.         |
| pressure           | atm              |              |
| scancoords         | angstroms        |              |
| scanenergies       | eV               | hartree      |
| scanparm           |                  |              |
| scfenergies        | eV               |              |
| scftargets         |                  |              |
| scfvalues          |                  |              |
| temperature        | kelvin           | kelvin       |
| time               | fs               |              |
| transprop          | etoscs           |              |
| vibanharms         | 1/cm             | 1/cm         |
| vibdisps           | delta angstrom   |              |
| vibfreqs           | 1/cm             | 1/cm         |
| vibfconsts         | mDyne/angstrom   |              |
| vibirs             | km/mol           |              |
| vibramans          | A^4/Da           |              |
| vibrmasses         | daltons          |              |
| zpve               | hartree/particle |              |
