### ISSUE TITLE
Gaussianparser HOMO value

### ISSUE THREAD

**Issue by elliotfarrar** [cclib/cclib#904]
When extracting the "homos" property from Gaussian .out files I am finding a value one lower than the HOMO should be. 

For example, the molecular orbital energies are contained on lines 560-571 from the Gaussian09 file "dvb_lowdin.log" from cclib-data:
```
 Alpha  occ. eigenvalues --  -10.02021 -10.02016 -10.00812 -10.00811 -10.00679
 Alpha  occ. eigenvalues --  -10.00678 -10.00605 -10.00591  -9.99233  -9.99233
 Alpha  occ. eigenvalues --   -0.80951  -0.75399  -0.71797  -0.69978  -0.66751
 Alpha  occ. eigenvalues --   -0.58869  -0.55892  -0.53167  -0.51017  -0.45744
 Alpha  occ. eigenvalues --   -0.43936  -0.41060  -0.39796  -0.39607  -0.37397
 Alpha  occ. eigenvalues --   -0.35115  -0.34729  -0.32451  -0.31125  -0.29278
 Alpha  occ. eigenvalues --   -0.28746  -0.26355  -0.21245  -0.19505  -0.15308
 Alpha virt. eigenvalues --    0.03742   0.09036   0.11061   0.18220   0.27253
 Alpha virt. eigenvalues --    0.33223   0.34073   0.37936   0.38145   0.41097
 Alpha virt. eigenvalues --    0.41195   0.42676   0.43964   0.45276   0.47826
 Alpha virt. eigenvalues --    0.52624   0.54582   0.57601   0.59944   0.62498
 Alpha virt. eigenvalues --    0.63971   0.68279   0.71724   0.77956   0.79458
```

https://github.com/cclib/cclib-data/blob/e2e677aa885c41f1e9e72eebac47640ac4c9fc17/Gaussian/Gaussian09/dvb_lowdin.log#L560-L571

There are 35 occupied orbitals for this structure (Alpha  occ. eigenvalues), meaning the HOMO should be the 35th orbital. However, with cclib I obtain df['homos'] = 34. This is a result of how the HOMO is parsed in Gaussianparser.py; after appending each  Alpha  occ. eigenvalue energy to a list, HOMO is defined as len(list)-1, as per lines 1159-1160 and 1179-1180:

https://github.com/cclib/cclib/blob/93e391fae1833ff04e3630ef8b986159ba2a7201/cclib/parser/gaussianparser.py#L1159-L1160

https://github.com/cclib/cclib/blob/93e391fae1833ff04e3630ef8b986159ba2a7201/cclib/parser/gaussianparser.py#L1179-L1180

Should I be interpreting this in a python sense (i.e. the first orbital is 0, hence homos = 34 refers to the 35th orbital)? Or is the value for the HOMO parsed by cclib one off, as a result of the -1 on lines 1159 and 1179?

I have also encountered this issue with Gaussian 16 files.

**Comment by shivupa** [comment]
First, thanks for a detailed issue that clearly explains what is going on!

> Should I be interpreting this in a python sense (i.e. the first orbital is 0, hence homos = 34 refers to the 35th orbital)? Or is the value for the HOMO parsed by cclib one off, as a result of the -1 on lines 1159 and 1179?

This is exactly it. [Here](https://github.com/cclib/cclib/issues/846#issuecomment-619178155) is a short discussion about it. It might seem confusing at first but once you start using the homo index to extract data out of other objects like `mocoeffs` or `moenergies` it becomes clear why it is this way.

**Comment by elliotfarrar** [comment]
Hi, thanks for the quick reply. Apologies for reasking an old question; somehow I missed the previous issue. I assume the option to use HOMO-1 for extraction from objects like moenergies was decided against because it's a bit more inuitive for users if homoenergy = moenergies['homo'], rather than having to subtract 1 each time?

**Comment by shivupa** [comment]
No worries about not seeing the old question. The previous question also spawned [this note](https://cclib.github.io/data_notes.html#homos) in the docs which I think addresses what the confusion is. (I'm pointing these out for posterity's sake in case others stumble upon this issue). 

cclib stores the index for zero-indexed number system where as Gaussian for example is printing for a one-indexed number system.

**Comment by elliotfarrar** [comment]
Thanks for the clarification.
