### ISSUE TITLE
Jaguar Vibrational Parsing Fails on normal modes <=6 Version 7.x

### ISSUE THREAD

**Issue by lg345** [cclib/cclib#911]
There is a rare use case for Jaguar 7.x (and possibly 8.x). If you perform a vibrational calculation and there are 6 or less normal modes (linear diatomic or up to 4 atoms) then Jaguar only prints one block of displacements and only one line break after the vibrational section. Typically Jaguar will print a block, a line break, then the next block and one line break after the entire section. Which means after the final block of displacements we will have two line breaks. In jaguarparser.py line 668 and 669 it skips the block ending line break to finish the block then 669 reads in the first line of the next block. If we are at the end of the vibrational section then this next line will be an empty line and we will properly exit the while loop defined on line 629
However, in the case of 6 or less normal modes then Jaguar has no need to print the after block line break and only prints the single line break to finish the section.
This means line 668 will skip that final section line break and 669 will read in next section which is no longer the vibrational section and we will have a ValueError as it attempt to parse the next section. The unit test for Jaguar has more than 6 normal modes and will not encounter this error. I attach an H2 calculation output. 
[H2-6-31G-OPT.FREQ.J.txt](https://github.com/cclib/cclib/files/4968471/H2-6-31G-OPT.FREQ.J.txt)

**Comment by berquist** [comment]
Although the error is appearing because of the number of normal modes, and the PRs I've made also have this in the title, it is actually due to the terminating condition of the harmonic frequency section simply being different.  Changing this without implementing an exact calculation of how many normal modes there are worked.
