### ISSUE TITLE
Add Horton proatom density generation template

### ISSUE THREAD

**Issue by berquist** [cclib/cclib#931]
After reading https://github.com/cclib/cclib/pull/926 and http://theochem.github.io/horton/2.1.1/user_postproc_aim.html#horton-atomdb-py-build-a-pro-atom-database, we need to include all the files necessary to regenerate https://github.com/cclib/cclib/blob/8585b23f0eee1574603e2b7e8dad61e605b7c01f/test/method/atoms.h5. This includes the template file and any accessory files.

**Comment by mscho527** [comment]
@berquist 

The template file for Psi4 is in the `horton` documentation. The only change that was necessary for Psi4 was to add `mv *.molden atom.default.molden` in line 25 of `run_psi4.sh` script that was auto-generated by `horton` -- it looked like the filename changed between versions. I can add this as a footnote in `cclib` documentation if this would be necessary.
