### ISSUE TITLE
moldenwriter.py IndexError

### ISSUE THREAD

**Issue by cpdfzigler** [cclib/cclib#937]
[H2O_def2SVPD_singlet.log](https://github.com/cclib/cclib/files/5144559/H2O_def2SVPD_singlet.log)
[H2O_def2SVPD_singlet.molden.zip](https://github.com/cclib/cclib/files/5144561/H2O_def2SVPD_singlet.molden.zip)
[H2O_def2SVPD_triplet.log](https://github.com/cclib/cclib/files/5144566/H2O_def2SVPD_triplet.log)

#### This was emailed to the cclib-users. Adapted here at the request of langer
Hi cclib Developers,
I encountered an issue with ccwrite when the outputype is set to 'molden' or 'wfz'. The error and trace back are below. The issue appears to be with handling spin-unrestricted orbital sets. Open shell systems give the error, and closed shell systems generate only the alpha set, no beta. By checking the attributes, ccread appears to read and parse the files (gamess.log) perfectly. I've been able to write my own python script to use the ccread output to generate correctly formatted molden files, but it's not obvious to me why moldenwriter.py is passing the index error.<br>
Here is the code I'm trying to run (where gmslogpath = the full path to the gamess .log file and mldndest = the path to where the resulting molden file is written):
```python
            gmslogObj = ccread(gmslogpath)
            mldnObj = ccwrite(gmslogObj,'molden',mldndest)
```
For a .log from a spin unrestricted calculation, ccwrite does not pass the error below, but only the Alpha set of orbitals is passed to the molden file. I've attached the log file for the uDFT result for a singlet calculation and the molden file that results from using the code above.

---------------------------------------------------------------------------
``` Python
IndexError                                Traceback (most recent call last)
<ipython-input-50-a9f587f2ced0> in <module>
     13             mldndest = join(root,mldndest)
     14             gmslogObj = ccread(gmslogpath)
---> 15             mldnObj = ccwrite(gmslogObj,'molden',mldndest)
     16 
     17 

~\.conda\envs\compchem\lib\site-packages\cclib\io\ccio.py in ccwrite(ccobj, outputtype, outputdest, indices, terse, returnstr, *args, **kwargs)
    379                             indices=indices, terse=terse,
    380                             *args, **kwargs)
--> 381     output = outputobj.generate_repr()
    382 
    383     # If outputdest isn't None, write the output to disk.

~\.conda\envs\compchem\lib\site-packages\cclib\io\moldenwriter.py in generate_repr(self)
    209 
    210             molden_lines.append('[MO]')
--> 211             molden_lines.extend(self._mo_from_ccdata())
    212 
    213         # Omitting until issue #390 is resolved.

~\.conda\envs\compchem\lib\site-packages\cclib\io\moldenwriter.py in _mo_from_ccdata(self)
    164         spin = 'Alpha'
    165         for i in range(mult):
--> 166             for j in range(len(moenergies[i])):
    167                 if has_syms:
    168                     lines.append(' Sym= %s' % syms[i][j])

IndexError: list index out of range

```

**Comment by langner** [comment]
For reference, the mailing list thread: https://sourceforge.net/p/cclib/mailman/cclib-users/thread/CAGwqgjeNPb63OoPXK7RA_pWC4oRMzx8muU9RdNzGqHsdA_F6Hw%40mail.gmail.com/#msg37096038

For some reason Sourceforge doesn't show the latest email from Aug 28th there, so I'll copy it here just FTR:
> Sure. I've attached an arbitrary spin unrestricted DFT calculation for triplet water.
> Here is the code I'm trying to run (where gmslogpath = the full path to the games .log file and mldndest = the path to where the > resulting molden file is written):
> ```python
>             gmslogObj = ccread(gmslogpath)
>             mldnObj = ccwrite(gmslogObj,'molden',mldndest)
> ```
> I've also noticed that for a spin unrestricted result, only the Alpha set of orbitals is passed to the molden file. I've attached the log > file for the uDFT result for a singlet calculation and the molden file that results from using the code above.

I believe the files in the email are the same ones uploaded here.
