### ISSUE TITLE
conda failures in Travis CI `before_install` don't cause the build to error

### ISSUE THREAD

**Issue by berquist** [cclib/cclib#941]
According to https://docs.travis-ci.com/user/job-lifecycle/#breaking-the-build,

> If `before_install`, `install` or `before_script` returns a non-zero exit code, the build is **errored** and stops immediately.

However, if you look at https://travis-ci.com/github/cclib/cclib/jobs/379292280 (the 3.7 build for https://github.com/cclib/cclib/pull/939/commits/58c20cc32e3cfaa564501d69a1e517ece12f72ff), even though the conda dependency solver failed, the build continued. I tried performing a similar unresolvable conda env creation, and conda does return 1 if it can't resolve dependencies.

Maybe a solution is to `set -e` locally and then `set +e` before exiting that step (https://github.com/travis-ci/docs-travis-ci-com/issues/1672)?

**Comment by langner** [comment]
@berquist Is this something you wanted to check out for v1.6.4?

**Comment by berquist** [comment]
@langner It's not a solved problem, but it isn't present right now because everything is working again, so debugging this is low priority for me.

**Comment by berquist** [comment]
We are moving away from Travis via #973.
