### ISSUE TITLE
Gaussian: object has no attribute 'scftargets'

### ISSUE THREAD

**Issue by BalticPinguin** [cclib/cclib#962]
Dear developers,
being new here, I'd first like to thank you for this nice project: this is very helpfull and having written a parser myself, I highly appreciate this tool!

But with a recent Gaussian log-file, I get an error:
````
[Gaussian init.log ERROR] Encountered error when parsing.
[Gaussian init.log ERROR] Last line read:  RMSDP=3.71D-02 MaxDP=2.23D-01              OVMax= 1.90D-01

Traceback (most recent call last):
  File "parse.py", line 30, in <module>
    main(sys.argv[1:])
  File "parse.py", line 17, in main
    data_ini=file_ini.parse()
  File "/home/tm162/.local/lib/python3.6/site-packages/cclib/parser/logfileparser.py", line 335, in parse
    self.extract(inputfile, line)
  File "/home/tm162/.local/lib/python3.6/site-packages/cclib/parser/gaussianparser.py", line 765, in extract
    if len(self.scftargets[0]) == 3:
AttributeError: 'Gaussian' object has no attribute 'scftargets'
````

I use the `1.6.4` release with [this script](https://gist.github.com/BalticPinguin/139c98dd58275634fbe22a65abc15878) and, while working properly on other files, it fails when being used with [this](https://gist.github.com/BalticPinguin/2b39322446f72bc4bbb0320f228956a9) logfile.

Since the script is basically a simplified version of the ``ccwrite``-tool, I suspect that this is not the problem?

I'm looking forward to any response and hope that we can fix this issue soon.

Best regards,
Hubert

**Comment by langner** [comment]
Thanks for the report and for the example logfile, Hubert. Looks like it is a bug, caused by an exception we made for BOMD (which is what this is, it seems)

**Comment by BalticPinguin** [comment]
>  caused by an exception we made for BOMD (which is what this is, it seems)

Actually, the calculation itself is just single point.

Please let me know if I can help you further with it. But I guess you are much faster doing the right fixes as a complete newbie on this code...

**Comment by berquist** [comment]
We are always accepting of fixes, and we are not always faster, even if we have the time...if you want to hack on cclib, then we would be happy to guide you through a patch if you submit a draft PR. It's totally up to you; I don't think anyone is working on this right now.

**Comment by langner** [comment]
Regression added to cclib/cclib-data#138
