### ISSUE TITLE
setup.py needs scipy for install_requires

### ISSUE THREAD

**Issue by lg345** [cclib/cclib#967]
Since scipy is a dependency for cclib it needs to be added to the install_requires of setup.py. Otherwise a fresh install will miss it and fail when it is called in cclib/parser/utils.py

**Comment by lg345** [comment]
It must be greater than scipy 1.2.0 to have scipy.spatial.transform

**Comment by langner** [comment]
As per dev discussion, we will add scipy as a hard dependency.

**Comment by langner** [comment]
See #970

**Comment by berquist** [comment]
Closed by #970, thanks for the report!
