### ISSUE TITLE
Documentation Issues

### ISSUE THREAD

**Issue by amandadumi** [cclib/cclib#969]
Hello! A few small things have gone awry with the docs on the github.io page.

Two examples I've noticed so far:
1.) The parsed data table formatting at: https://cclib.github.io/data.html. with "Couldn’t find cython becke routine" being printed right before the table should begin.
2.) Search functionality. Specifically, when i search anything, I get the expected search results, though when I click them they return a "page not found" error. 

 I will try to take a look, I'm not as familiar with the docs generation for cclib. It may be a quick fix that is obvious to someone else.

**Comment by langner** [comment]
Hmm, the tables do indeed seem broken.

**Comment by Dariusrussellkish** [comment]
Hi I'd like to bump this as well. Really hard to tell what's supported at the moment with the broken tables. I'm more than happy to give a go at fixing the table if you could give me a quick point at where best to start looking.
