### ISSUE TITLE
Move from Travis to GitHub Actions?

### ISSUE THREAD

**Issue by berquist** [cclib/cclib#973]
https://github.com/MolSSI/cookiecutter-cms/issues/122 is a good breakdown of why we might want to move, in particular https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing. That article hides that OSS projects will now need to apply for build minutes, and they're going to track usage.

It is really unfortunate that GitHub Actions is confusing, but I've seen enough examples that I think we can move over.

Doing so would possibly affect #952 and #941, make #960 obsolete, and require rethinking #782.

**Comment by ghutchis** [comment]
I'm happy to help - I worked through a lot of this with avogadro and openbabel.

The good news is that there are many examples and also some really useful pre-packaged actions.

**Comment by berquist** [comment]
Done in #983 and #1017.
