### ISSUE TITLE
Use the `is` operator instead of `!=`

### ISSUE THREAD

**Issue by hodovani** [cclib/cclib#991]
Use the `is` operator instead of `!=` [here](https://github.com/cclib/cclib/blob/master/test/bridge/testhorton.py#L183) to compare to None, because `!=`  calls __eq__ which is slower and error-prone.

**Comment by berquist** [comment]
Thanks for the catch. I hope that in the near-ish future, we can use mypy to find these.

**Comment by hodovani** [comment]
@berquist should I create PR to fix this?

**Comment by berquist** [comment]
Sure, go ahead.
