### ISSUE TITLE
Units for parsed energies

### ISSUE THREAD

**Issue by LaTruelle** [cclib/cclib#998]
The units in the parsed energies seem to be non-coherent. For instance: `ccget freeenergy dvb_ir.out` returns `-382.164915` (in Hartree) when `ccget scfenergies dvp_ir.out` returns `array([-10403.13745031])` in eV, as specified in the documentation.
Is there a way to make them coherent within the code easily, or at least to document all these fields? (I did not find freeenergy and enthalpy in the documentation)

**Comment by berquist** [comment]
1. There should be units in http://cclib.github.io/data.html for these fields, though others may be incomplete.
2. There is a general inconsistency between the thermochemistry units (which are atomic) and the electronic units (which are all in eV). This is an old issue (#89) and I think the solution is to have atomic units be the default for 2.0.
